### ISSUE TITLE
OpsWorks deregister EcsCluster from Stack

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#1001]
Please help
to deregster ECSCluster from OpsWorks stake using deregisterEcsCluster
according to the documentation "Deregisters a specified Amazon ECS cluster from a stack"
but I'm not find away to provide the Stake Id. it receives only the ECSCluster Arn

**Comment by kiiadi** [comment]
@bmagic39 apologies for the extended delay here - according to the OpsWorks docs cluster to stack is a one-to-one relationship. Since a cluster can only be registered with one stack there's no need to provide both ID's on the de-register operation.

http://docs.aws.amazon.com/opsworks/latest/APIReference/API_RegisterEcsCluster.html
