### ISSUE TITLE
How to get data from AWS managed ElasticSearch using java.

### ISSUE THREAD

**Issue by srikanthonchip** [aws/aws-sdk-java#1007]
In Aws_iot i created a thing(device) and published messages to a topic say "trucks/truck1234" and i created Elasticsearch domain and stored those messages in that elasicsearch domain to analyze further using kibana.upto this is fine. Now i want to read that published messages data from Elasticsearch to my application using java.
i have followed the steps from the given bellow link:

https://aws.amazon.com/blogs/mobile/analyze-device-generated-data-with-aws-iot-and-amazon-elasticsearch-service/

can anyone please suggest how to achieve it??

**Comment by dagnir** [comment]
Hi @srikanthonchip, it's not possible to retrieve data from Elasticsearch using the SDK, since the Elasticsearch client is only meant as a control plane client (i.e. configuring Elasticsearch). To retrieve data, you'll need a client to talk to Elasticsearch's REST API like Jest. Please see the first part @kiiadi's response here https://github.com/aws/aws-sdk-java/issues/861#issuecomment-251788032 for additional information.

**Comment by dagnir** [comment]
I'm going to go ahead and close this issue because it looks like there's no issue with the SDK here and this more of a usage question. Please note that we are moving to using GitHub primarily to track SDK bugs and feature requests and are asking customers to please direct usage questions to StackOverflow (tagged with [`aws-java-sdk`](http://stackoverflow.com/questions/tagged/aws-java-sdk)).

**Comment by amihaiemil** [comment]
@srikanthonchip I think the easiest way to communicate with any AWS web service is through their [core sdk](https://github.com/aws/aws-sdk-java/tree/master/aws-java-sdk-core) which offers an HTTP client and an API to sign the requests properly.

However, I found the sdk to be very messy (took me days to figure things out), so I wrapped the HTTP requests and Signing process inside some decorators. Here is how I did it (example with ElasticSearch service) 

http://www.amihaiemil.com/2017/02/18/decorators-with-tunnels.html
