### ISSUE TITLE
AmazonSQSBufferedAsyncClient skips AsyncHandler callback

### ISSUE THREAD

**Issue by gadamsciv** [aws/aws-sdk-java#1023]
I ran into a problem with AmazonSQSBufferedAsyncClient.receiveMessageAsync (sdk version 1.11.87), where AsyncHandler callbacks aren't always called. This is because QueueBuffer.receiveMessage calls future.setBuffer after calling receiveBuffer.receiveMessageAsync. That method calls satisfyFuturesFromBuffer, and if there are prefetched receive message batches available, it will call fufillFuture (no, that's not a typo), which will trickle through to QueueBufferFuture.setSucess. Unfortunately, in this circumstance, QueueBufferFuture.issuingBuffer is not yet set (it won't be set until the next line in QueueBuffer.receiveMessageAsync), so callback.onSuccess is not called (see QueueBufferFuture.setSuccess line 69). 

```
package test;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.concurrent.Future;

import org.junit.Before;
import org.junit.Test;

import com.amazonaws.handlers.AsyncHandler;
import com.amazonaws.services.sqs.AmazonSQSAsync;
import com.amazonaws.services.sqs.AmazonSQSAsyncClientBuilder;
import com.amazonaws.services.sqs.buffered.AmazonSQSBufferedAsyncClient;
import com.amazonaws.services.sqs.model.ReceiveMessageRequest;
import com.amazonaws.services.sqs.model.ReceiveMessageResult;

public class AwsSqsBufferedAsyncClientTest {

	private static final String SQS_QUEUE_URL = "<queue_url>";
	
	private AmazonSQSAsync sqs;
	
	@Before
	public void before() {
		sqs = new AmazonSQSBufferedAsyncClient(AmazonSQSAsyncClientBuilder.standard().build());
//		sqs = AmazonSQSAsyncClientBuilder.standard().build();
	}
	
	private class SignalReceivedAsyncHandler implements AsyncHandler<ReceiveMessageRequest, ReceiveMessageResult> {
		
		private boolean signalReceived = false;
		
		public boolean isSignalReceived() {
			return signalReceived;
		}

		@Override
		public void onError(Exception exception) {
			signalReceived = true;
		}

		@Override
		public void onSuccess(ReceiveMessageRequest request, ReceiveMessageResult result) {
			signalReceived = true;
		}
		
	}
	
	@Test
	public void testReceive() throws Exception {
		for (int i = 0; i < 10; i++) {
			SignalReceivedAsyncHandler handler = new SignalReceivedAsyncHandler();
			Future<ReceiveMessageResult> future = sqs.receiveMessageAsync(
					new ReceiveMessageRequest()
						.withQueueUrl(SQS_QUEUE_URL)
						.withMaxNumberOfMessages(10)
						.withWaitTimeSeconds(1), 
					handler);
			future.get();
			assertThat(handler.isSignalReceived()).withFailMessage("iteration: %d, AsyncHandler callbacks were not called!", i).isTrue();
		}
	}
}
```

The unit test above fails for me reproducibly. Switching to non-buffered AmazonSQSAsyncClient resolves the issue.

**Comment by przemos** [comment]
Had the same problem with SendAsync side. Eventually turned into wrapping Future<SendMessageResult> as that in turns works flawlessly.

**Comment by gadamsciv** [comment]
@shorea Why was this issue closed?

**Comment by shorea** [comment]
Apologies, I was cleaning up some old issues and thought this one had reached a resolution. Was @przemos suggestion not viable?

**Comment by gadamsciv** [comment]
Wouldn't it be better to call future.setBuffer before calling receiveBuffer.receiveMessageAsync? This would avoid users from having to troubleshoot and figure out that they need to use a workaround? I also don't think it would cause any regression or backward compatibility issue.

**Comment by millems** [comment]
Sorry about the delay on this one!

It should be fairly rare that the handler isn't invoked. The scheduler would have to ignore the queue's thread for a very long time (at least the duration of the HTTP request) or the assigned queue would have to be ignored by the completing thread (it's not volatile), so it's very unlikely to be seen in regular processing. 

The test you provided above fails more frequently than normal because the handlers are invoked in a separate thread than the one completing the future, so it's relatively likely the future will be completed before the handler is invoked. In particular, the future is usually completed before the handler is executed. That's definitely a bit odd, but we aren't able to change it for backwards compatibility reasons.

That said, there's still the potential race condition you raised if the thread blocks just before the buffer is set, but I had to manually schedule the threads to make it happen. 

To be honest, I'm not sure why the buffer is required to not be null in order to complete the future. That seems incorrect. I'll see if anyone else can spot the reasoning behind that. If not, we can remove the null check to fix the issue.

**Comment by gadamsciv** [comment]
You say that it should be rare for the handler to not be invoked. What about my unit test is different from normal usage that causes it to fail more often? I'm also not sure what backward compatibility reasons could be preventing fixing this. It seems like a straightforward bug to me.

**Comment by millems** [comment]
Sorry, I did a poor job explaining things.

There are two issues at play here:
1. The `QueueBuffer` sets a back-reference to itself on the future _after_ it sends the async request, but the future requires the `QueueBuffer` in order to invoke the callback.
2. The future invokes the callback asychronously _after_ completing the future.

(2) is definitely not very intuitive. In V2 we have a similar interface on our async clients, and we only complete the future after the callback completes.

(1) is a bug that we will definitely fix, but it won't cause the test you provided to succeed. Because the test validates the callback is invoked after the future is completed, (2) introduces false positives.

To take (2) out of the equation to see the relative frequency of (1) we'll need to wait a certain amount of time for the async callback to be executed, independently of the response future being completed (see below). I ran this test a few times, and it didn't fail. I was able to get (1) to happen by adding a long sleep before setting the back-reference, to give the response time to come in.

```Java
package com.amazonaws;

import com.amazonaws.handlers.AsyncHandler;
import com.amazonaws.services.sqs.AmazonSQSAsync;
import com.amazonaws.services.sqs.AmazonSQSAsyncClientBuilder;
import com.amazonaws.services.sqs.buffered.AmazonSQSBufferedAsyncClient;
import com.amazonaws.services.sqs.model.ReceiveMessageRequest;
import com.amazonaws.services.sqs.model.ReceiveMessageResult;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

public class MyTest {

    private String queueUrl;

    private AmazonSQSAsync sqs;

    @Before
    public void before() {
        this.sqs = new AmazonSQSBufferedAsyncClient(AmazonSQSAsyncClientBuilder.defaultClient());
        this.queueUrl = sqs.createQueue("queue-" + UUID.randomUUID().toString())
                           .getQueueUrl();
    }

    @After
    public void cleanup() {
        sqs.deleteQueue(queueUrl);
    }

    private class SignalReceivedAsyncHandler implements AsyncHandler<ReceiveMessageRequest, ReceiveMessageResult> {

        private CompletableFuture<Void> handlerInvokedFuture = new CompletableFuture<>();

        @Override
        public void onError(Exception exception) {
            handlerInvokedFuture.complete(null);
        }

        @Override
        public void onSuccess(ReceiveMessageRequest request, ReceiveMessageResult result) {
            handlerInvokedFuture.complete(null);
        }

    }

    @Test
    public void testReceive() throws ExecutionException, InterruptedException {
        for (int i = 0; i < 10; i++) {
            SignalReceivedAsyncHandler handler = new SignalReceivedAsyncHandler();
            sqs.receiveMessageAsync(
                    new ReceiveMessageRequest()
                            .withQueueUrl(queueUrl)
                            .withMaxNumberOfMessages(10)
                            .withWaitTimeSeconds(1),
                    handler)
               .get();

            try {
                handler.handlerInvokedFuture.get(10, TimeUnit.SECONDS);
            } catch (TimeoutException e) {
                Assert.fail("Handler was not invoked after 10 seconds of receiving the response: " + e.getMessage());
            }
        }
    }
}
```

**Comment by gadamsciv** [comment]
Ah, I think I understand now. That makes sense.

**Comment by millems** [comment]
We've pushed a change that removes the race condition described in (1) above, but as noted you'll unfortunately still need to wait for the async callback to happen, because the future is completed parallel to the handler being invoked.

This change will go out with the next release.
