### ISSUE TITLE
Version number not set to 1.11.101-SNAPSHOT in aws-java-sdk-osgi/dependency-reduced-pom.xml

### ISSUE THREAD

**Issue by freemansoft** [aws/aws-sdk-java#1060]
This file was missed when the new milestone release was created aws-java-sdk-osgi/dependency-reduced-pom.xml

**Comment by kiiadi** [comment]
are you saying the dependency-reduced-pom.xml isn't included in the JAR?

**Comment by freemansoft** [comment]
The version number in dependency-reduced-pom.xml seems to lag pom.xml by one version.  The dependency-reduced-pom.xml is on the previous number (release) while the pom.xml is on the current snapshot.

**Comment by kiiadi** [comment]
My understanding is that the `dependency-reduced-pom.xml` is used as an interim step when packaging the actual pom into the OSGI jar (same is true for the `aws-java-sdk-bundle`) - I'm not sure it's intended to be use used directly. Arguably it shouldn't even be included in the repository (you'll see the `aws-java-sdk-bundle` deliberately puts it into the build directory so that it's not included in the source repository - https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-bundle/pom.xml#L78). 

What's the use-case exactly? What are you trying to do with the `dependency-reduced-pom.xml`?

**Comment by kiiadi** [comment]
Closing due to lack of response, please re-open if you feel this is an issue with the SDK.
