### ISSUE TITLE
Make Builder Params Public

### ISSUE THREAD

**Issue by gorzell** [aws/aws-sdk-java#1065]
Is there any reason that the `protected final AwsSyncClientParams getSyncClientParams() {` in `AwsClientBuilder` can't be publicly accessible?  There are instances where I would like to use the builder for everything except creating the client instance, and I would like to use the non-deprecated client constructor that takes the params instead (basically the same thing the build is doing, except when doing it myself I can mix in additional functionality).

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/client/builder/AwsClientBuilder.java#L353

**Comment by kiiadi** [comment]
What are you wanting from the params that you can't get from the instance of the builder you have?

**Comment by gorzell** [comment]
I would like to be able to use this constructor `AmazonCloudFormationClient(AwsSyncClientParams clientParams)` and it would be nice to able to get the `clientParams` instance from the builder, which does have it, but does not expose it.
ex:
```scala
val clientParams = AmazonCloudFormationClient.builder
  .withRegion(Regions.US_WEST_2)
  .withCredentials(credentialProviderWithProfile("test"))
  .getSyncClientParams()

val client = new AmazonCloudFormationClient(clientParams) with UpdateDockerStack
```
Because of the way I think scala works you are required to do the composition at instance creation so that the compiler can handle it.

**Comment by kiiadi** [comment]
ok so you're effectively extending it with a mixin; we've got a pattern in `TransferManager` where there's a protected constructor that accepts a `TransferManagerBuilder` this allows you to extend `TransferManager` but still create it with the builder. Take a look: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/TransferManager.java#L332

We'd have to add this pattern onto the service clients but then you'd be able to do something like

```scala
class CloudFormationWithUpdateDockerStack(builder: AmazonCloudFormationClientBuilder) 
                                        extends AmazonCloudFormationClient(builder) 
                                        with UpdateDockerStack
```

Do you think that would satisfy your use-case?

**Comment by gorzell** [comment]
That looks like a pretty good option, although I don't understand why that constructor needs to be protected.  I would prefer not to even have to extend the existing client, just mix in my extras directly.

```scala
val client = new AmazonCloudFormationClient(builder) with UpdateDockerStack
```

**Comment by kiiadi** [comment]
@gorzell wanted to understand a bit more about the use-case here - what is `UpdateDockerStack`? Is there are reason this has to be used as an extension mix-in rather than through some sort of composition pattern? We're designing a new major version and making some changes to how clients are created and I want to make sure we have this case covered.

In answer to why the above couldn't just be `public`, we're trying to encourage adoption of creating the client via the builder - we've done this by deprecating all of the public constructors in an effort to allow the code to 'self-document'. Whilst I agree exposing a public constructor that takes a builder still forces the builder pattern, I worry a little that new adopters of the SDK will assume they *have* to then create clients with this pattern:

```java
AmazonCloudFormationClientBuilder builder = AmazonCloudFormationBuilder.standard().withRegion(...)...
AmazonCloudFormation client = new AmazonCloudFormationClient(builder)
```

By making the constructor `protected`, I think it's more obvious that creating the instance directly is really a 'special' use-case and encourages the (arguably) simpler use of the standard mechanism of `builder.build()`. We could address this with documentation and examples - but as I as I want to full understand your use-case before we go down this road.

We definitely want the SDK to be flexible and allow customers to use their prefered design patterns however as you can appreciate we also want to have some control over how the SDK evolves and limiting some options gives us more freedom to evolve without causing backwards compatibility issues.

**Comment by kiiadi** [comment]
As another​ example of why we're​ encouraging creation via the builder is we're looking at potentially creating different underlying implementation versions of the clients based on arguments supplied to the builder. S3 for example we could potentially choose between the regular `AmazonS3Client` and the `AmazonS3EncryptionClient` based on the existence (or not) of encryption materials on the builder.

**Comment by kiiadi** [comment]
@gorzell the other option might be to use a [`DynamicProxyClass`](https://docs.oracle.com/javase/8/docs/technotes/guides/reflection/proxy.html)

I'm still not entirely sure what you're trying to do - you mention pagination and wrapping/unwrapping the responses - however surely you're not able to actually change the interface of AmazonCloudFormation right?

**Comment by gorzell** [comment]
This is a bit more abstract, but the general idea is that I would like to add functionality to the clients that are provided by the SDK.  The best way I can think of to do that is to use a mix-in that is typed (e.x. a scala selftyped trait) to the interface, since this is all higher level functionality that shouldn't care about the actual client implementation.

Generally I would like to split these mix-ins up based on their functionality and allow the user to then compose them based on the use case.  As an example you might have something like this:

* ExceptionHandling
* PaginationHandling
* Unwrapped

Then ideally you could do something like this:
```scala
val client = new new AmazonCloudFormationClient(clientParams) with ExceptionHandling with PaginationHandling with Unwrapped
```

I agree that this does have the negative side effect of not being able to let the builder dynamically chose an implementation.  But I can't think of a better way to add this functionality and extending a given implementation to get access to the constructor you need seems confusing, but is a valid work around.

**Comment by gorzell** [comment]
You can't change the interface directly, but you can add additional interfaces/traits to it so that the resulting object has the composite functionality of all of the interfaces.

**Comment by debora-ito** [comment]
Hi @gorzell,

The SDK team has reviewed the feature request list for V1 and decided not to implement this since they're concentrating efforts on V2 new features. Please give V2 a try and send us your feedback.

Feel free to reach out if you have any questions or comments.
