### ISSUE TITLE
S3: During upload of ".jar" files Metadata Content-Type should be set to "application/x-java-archive"

### ISSUE THREAD

**Issue by thomas-klambauer** [aws/aws-sdk-java#1073]
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/resources/mime.types
does not have a listing for "jar" files.

This causes the default Metadata content-type=application/octet-stream to be set and delivered as HTTP response header field to browsers.

This causes an issue with browsers:
* IE 11.953.14393.0
* Edge Microsoft Edge 38.14393.0.0 
because those browsers when encountering a URL with X.jar and content-type=application/octet-stream will suggest as save-as-filename X.zip

If the content-Type were "application/x-java-archive" those browser would suggest the correct X.jar filename.

The S3 web console **also** automatically sets this content-type already when uploading a .jar file - so this seems desired and already accepted.

**Comment by dagnir** [comment]
Hi @thomas-klambauer, I'll need to look into whether adding an entry for JARs in that file is the right thing to do since it's technically a behavior change. For now, as a workaround, you should be able to set the content type by setting it via [`ObjectMetadata#setContentType`](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/ObjectMetadata.html#setContentType-java.lang.String-)

**Comment by thomas-klambauer** [comment]
Thanks! For my use case I'll end up likely using the Content-Disposition header (setting that as Metadata during the upload) - as there isn't a content-type for each file extension.

**Comment by dagnir** [comment]
Going to ahead and close this for now. If you'd like to open this as a feature request, please feel free to reopen.
