### ISSUE TITLE
Generated hashCode() should be improved 

### ISSUE THREAD

**Issue by SBozhko** [aws/aws-sdk-java#1079]
Seems like a code generator which is used for Kinesis model is not aware of classes without fields. Example class: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-kinesis/src/main/java/com/amazonaws/services/kinesis/model/AddTagsToStreamResult.java

Hashcode example:
```
@Override
    public int hashCode() {
        final int prime = 31;
        int hashCode = 1;

        return hashCode;
    }
```

This code is confusing. There is unused final parameter `final int prime = 31;`.

**Comment by debora-ito** [comment]
Hello! Just a quick update letting you know that the SDK team has reviewed the feature request list for V1 and this looks like a great candidate for a community PR, which we’ll help merge in and support.

**Comment by avishkarnikale** [comment]
Hi @debora-ito , I would like to contribute, since the class is fieldless ( and there are others in the same package as well), 
1) Would it make sense to send super.hashCode() as a return value?
2) Is this change needed in the already generated classes (change the method directly in the class)
OR does the class generation codebase needs to change (if yes, I would need some pointers to the same)

Also, toString() seems to just send "{}", 
super.toString() or some other strategy should be applied for the same as well.
