### ISSUE TITLE
The bucket is in this region: null

### ISSUE THREAD

**Issue by clayclayclay** [aws/aws-sdk-java#1100]
Hello, I created a service instance in `Cloud Foundry` platform, I got some environment parameters, including `access_key_id`, `secret_access_key`, `bucker`, `uri`, `host`, `username`. 
But When I coding with AWS S3 SDK, following some tutorials, it always occured `Error:The bucket is in this region: null. Please use this region to retry the request (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: 2DDBC8C9B1D18ECB)`.
Could anyone give me some advice?
Thank you!

**Comment by kiiadi** [comment]
The `AmazonS3Client` needs to be configured with the same Region as the S3 bucket resides in. Can you give a full code sample showing how you're creating the `AmazonS3` instance?

**Comment by clayclayclay** [comment]
@kiiadi Hi, Kiiadi.
The AmazonS3 creating process is in the `Cloud Foundry` platform. The details operation is by Cloud Foundry CLI, like below shown:
```
cf create-service objectStore s3 {myObjectStoreName}
```

I think it's better to provide some code about creating AmazonS3Client, it's like below shown:
```
private final static String REGION = "us-west-1";

    private AmazonS3 AmazonS3ClientFactory() {
        if (s3 == null) {
            BasicAWSCredentials basic = new BasicAWSCredentials(accessKeyId, secretKey);
            s3 = AmazonS3ClientBuilder.standard().withCredentials(new AWSStaticCredentialsProvider(basic))
                    .withRegion(REGION).build();
        }
        return s3;
    }
```
If I don't provide the `REGION` , it will occured the error:
```
com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
```
But I followed some tutorials, they all don't provide the region. And I think it will provide a default region. So, for now I don't know how to do.

**Comment by kiiadi** [comment]
@clayclayclay I'm not overly familiar with Cloud Foundry so I can't tell you how the `AmazonS3` instance is created.

Regarding your code-sample for creating the client, the exception you're seeing when you leave off region is expected behaviour. When configured via the builder all clients must provide a region either explicitly through a `withRegion` call or implicitly through a configuration file (see the "Default Region Provider Chain" [here](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html#automatically-determine-the-aws-region-from-the-environment)).

We are working to update all the tutorials that are owned by Amazon, unfortunately there are still plenty of examples out there that are out of date.

This issues log is intended to track bugs and feature requests **only** (see the [Getting Help](https://github.com/aws/aws-sdk-java/#getting-help) section of our README). Usage questions like this are better serviced by the community and for that we're directing customers to StackOverflow. The community is much broader than just AWS staff and you may even find others who've experience with Cloud Foundry and the AWS SDK's who'll be better placed to help. If you're still having trouble please create a question using the AWS Java SDK tag ([aws-java-sdk](http://stackoverflow.com/questions/tagged/aws-java-sdk)) on StackOverflow. Feel free to post the link to it here for continuity.

On the other-hand if you do feel that this is a bug with the SDK please feel free to re-open the issue.

**Comment by clayclayclay** [comment]
@kiiadi  Thank you! I almost fix it.

**Comment by kiiadi** [comment]
Great!

**Comment by arungupta12** [comment]
Hi Kiladi 
The bucket is in this region: null. Please use this region to retry the request (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect;
I am facing the same problem , i had tried accessing the bucket using java sdk  with all regions one by one ,but unable to access the bucket and error above mentioned occured every time.
please help!
Also can you tell me if i can access a bucket owned and created by super user of amazon account and i am being a IAM user to that super user and all what i can operate on that bucket is only write operation inside a folder in that bucket i.e i dont have permissions to delete that bucket and creating directly a folder in that bucket , but i am able to create sub folders, this all i had tried using Web View,
Final Query : Can i access that bucket and write objects to that bucket in this scenario.
Thanks

**Comment by clayclayclay** [comment]
@arungupta12 
Hi, arungupta12.I also have faced the same problem : the bucket is in this region: null. I just think maybe I can give you some ideas.
I want to which version do you use and how do you create the AmazonS3 client :)

**Comment by kiiadi** [comment]
@arungupta12 regarding the permissions based questions that'll depend on how you've configured the permissions on the bucket and the particular IAM policy in use on the account. I'm no expert when it comes to permissions - you may be better off posting a question to the [amazon-iam](http://stackoverflow.com/questions/tagged/amazon-iam) tag on stack overflow.
