### ISSUE TITLE
Buffered version of AmazonCloudWatchClient

### ISSUE THREAD

**Issue by amagnus** [aws/aws-sdk-java#1109]
Hello,

I was wondering if something is in the works to add a buffered version of AmazonCloudWatchClient in the SDK?

We have been happily using AmazonSQSBufferedAsyncClient with SQS.

**Comment by millems** [comment]
To clarify, you mean a client to which you can write cloud watch events, and they will be buffered until an explicit call to some kind of a flush() method is made, or a size/time limit is encountered?

**Comment by amagnus** [comment]
That's correct. That would enable us to minimize the quantity of cloudwatch calls by automatically making requests in batches of 20 items (which is the max for putMetricData for instance).

**Comment by millems** [comment]
Cool, I understand the feature request. Feel free to list off any specific features here that we might not think of that would be beneficial to you. We'll be sure to consider them if we implement something like this.

**Comment by anoopgarlapati** [comment]
Hi, this feature would be great for us too. Is there any estimate on this?

**Comment by debora-ito** [comment]
@amagnus @anoopgarlapati 

The SDK team are concentrating efforts on V2 new features so they decided not to implement this one in V1. It's still being considered for V2, you can track the issue here: https://github.com/aws/aws-sdk-java-v2/issues/165. 

I'll go ahead and close this, please feel free to comment on the V2 issue with your use case and reach out if you have further questions.
