### ISSUE TITLE
How to specify a certificate for API Gateway's Stage using SDK API?

### ISSUE THREAD

**Issue by brainoutsource** [aws/aws-sdk-java#1146]
`CreateStageRequest` doesn't allow specifying the client certificate ID, and I can't find a request that 'attaches' a certificate to a Stage either.

**Comment by dagnir** [comment]
Hi, looks like you're looking for [`UpdateStageRequest`](http://docs.amazonaws.cn/zh_cn/AWSJavaSDK/latest/javadoc/com/amazonaws/services/apigateway/model/UpdateStageRequest.html)

It's a little funky because there's no `certificate` member, you need to specify it as a path, according to the API documentation for [`stage:update`](http://docs.aws.amazon.com/apigateway/api-reference/link-relation/stage-update/)

Here's a sample snippet:

```java
UpdateStageResult updateStageResult = apig.updateStage(new UpdateStageRequest()
        .withStageName("beta")
        .withRestApiId("MY_API_ID")
        .withPatchOperations(new PatchOperation()
                .withOp("replace")
                .withPath("/clientCertificateId")
                .withValue("MY_CERT")));

```

**Comment by brainoutsource** [comment]
Oh, wow. Thank you!

**Comment by dagnir** [comment]
You're welcome. Glad that helped!
