### ISSUE TITLE
Include a SystemPropertyRegionProviderChain in the DefaultAwsRegionProviderChain

### ISSUE THREAD

**Issue by ejain** [aws/aws-sdk-java#1158]
The DefaultAWSCredentialsProviderChain includes a SystemPropertiesCredentialsProvider, which reads credentials from two `aws.*` system properties (if no credentials are found in environment variables). Would be nice to similarly support specifying the default region through an `aws.region` system property (especially since the DefaultAwsRegionProviderChain can't be overridden, see #1157).

**Comment by shorea** [comment]
Just to give you a quick update, we are implementing this and it's currently in internal review. Hope to have it out this week.

**Comment by shorea** [comment]
We had an internal discussion and the general consensus is to have the following level of precedence to stay consistent with how our credentials are loaded.

Environment Variable -> System Property -> ~/.aws/config -> Instance Metadata Service

This is not quite as intuitive since System properties should take precedence over environment variables (since they are more specific) but it is more consistent with how we handle other system settings so the team felt this would be less surprising. Does the precedence above work for your use case?

**Comment by ejain** [comment]
Doesn't matter for my use case (not setting any environment variables). Being consistent with how credentials are loaded sounds like a good call.

**Comment by shorea** [comment]
Thanks, pushing this today and will get it publicly released sometime next week.
