### ISSUE TITLE
S3 TransferManager Batched Uploads using InputStreams

### ISSUE THREAD

**Issue by axelfontaine** [aws/aws-sdk-java#117]
My application generates a number of objects in memory which are then uploaded to an S3 bucket.

With the current implementation, I have to either
- Upload the objects on by one
- Write the objects to disk and then batch upload them

It would be nice if there would be something like uploadInputStreamList() similar to the uploadFileList method.

**Comment by abhinavmishra14** [comment]
Hey, I have the same issue. It looks like amazon has not worked on this yet. 
Have you came across any other solution ? 

-Abhinav

**Comment by debora-ito** [comment]
Hi @axelfontaine, the SDK team has reviewed the feature request list for V1, and since they're concentrating efforts on V2 new features they decided to not implement this one in V1. It still being considered for the TransferManager refactor in V2, see the referenced issue above. I'll go ahead and close this one.

Please feel free to comment on the V2 issue with your use case, and reach out if you have further questions.
