### ISSUE TITLE
Differences in parallel S3 download versus Ruby AWS SDK and Boto3

### ISSUE THREAD

**Issue by ffeldhaus** [aws/aws-sdk-java#1172]
While reviewing S3 downloads using different AWS SDKs I discovered that the Ruby AWS SDK and Boto3 (Python AWS SDK) are using a different method for parallel S3 downloads than the Java AWS SDK. 

In the Ruby and Python SDKs the parallel S3 download is achieved via multiple, parallel HTTP content range requests. 

In the Java SDK the parallel S3 download is achieved via Multipart Downloads. The [`getPartCount` function of the `ServiceUtils` class](https://github.com/aws/aws-sdk-java/blob/7844c64cf248aed889811bf2e871ad6b276a89ca/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/ServiceUtils.java#L515) retrieves the part count via a HTTP HEAD request with query string `?partNumber=1`. The response contains the HTTP header key `x-amz-mp-parts-count`. Unfortunately I couldn't find this in the official AWS S3 documentation.

With the number of parts, the [`downloadInParallel` function of the `DownloadCallable` class](https://github.com/aws/aws-sdk-java/blob/7844c64cf248aed889811bf2e871ad6b276a89ca/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/DownloadCallable.java#L174) then downloads the file using multiple HTTP GET requests with query string `?partNumber=<part number>`. Unfortunately I couldn't find this in the official AWS S3 documentation.

Why is the Java AWS SDK using a different method for parallel S3 downloads than Ruby and Python? 

Is there an advantage of using Multipart Downloads versus multiple content range requests?

**Comment by varunnvs92** [comment]
>> Why is the Java AWS SDK using a different method for parallel S3 downloads than Ruby and Python?
There is no particular reason. We got customer requests to support parallel downloads and we started with partNumber approach to quickly get the feature to customers. Later we want to move to ranged downloads but we had other priority tasks and didn't get time to revisit the feature.

>> Is there an advantage of using Multipart Downloads versus multiple content range requests?
Not that I am aware of. I think Range requests is a better approach because it supports all downloads unlike partNumber approach which only supports objects uploaded in parts. We are planning to release a new version of the SDK later this year. We will look into using content range requests in the new major version. 

>> Unfortunately I couldn't find this in the official AWS S3 documentation.
I could not too. I will raise a ticket to S3 team about this. You can also directly reach to service team via AWS Forums.
https://forums.aws.amazon.com/forum.jspa?forumID=24
