### ISSUE TITLE
How to push table with Map<Long, UUID> to DynamoDB.

### ISSUE THREAD

**Issue by gandhihardik17** [aws/aws-sdk-java#1193]
@DynamoDBTable(tableName = "Folder")
public class FolderRecord {
@DynamoDBHashKey(attributeName = "TenantAndFolderID")
    private EntityKey key;

@DynamoDBAttribute(attributeName = "Shards")
    private Map<String, UUID> shards;
}

The above code works for me.

But when I change the Map to Map<Long, UUID> ,
@DynamoDBTable(tableName = "Folder")
public class FolderRecord {
@DynamoDBHashKey(attributeName = "TenantAndFolderID")
    private EntityKey key;

@DynamoDBAttribute(attributeName = "Shards")
    private Map<Long, UUID> shards;
}

it gives error that  requires @DynamoDBTyped or @DynamoDBTypeConverted

**Comment by dagnir** [comment]
Hi, yes this is a limitation of the `DynamoDB` API. In `DynamoDB`, maps are [expected to be `String` to `AttributeValue`](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html#DDB-Type-AttributeValue-M) which is why your first example works. As the error says, you can provided your own custom converter to convert the Longs to String and back.

**Comment by dagnir** [comment]
I'm gonna go ahead and close this issue. Please feel free to reopen if you have further questions.
