### ISSUE TITLE
Add method to DynamoDBMapper to create a new TableMapper with config overrides

### ISSUE THREAD

**Issue by matiaslb** [aws/aws-sdk-java#1201]
There should be a method that complements [newTableMapper](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapper.html#newTableMapper-java.lang.Class-) with the following signature:

```
public <T,H,R> DynamoDBTableMapper<T,H,R> newTableMapper(Class<T> clazz, DynamoDBMapperConfig config) 
```

that returns a DynamoDBTableMapper instance that uses a DynamoDBMapper config that is the result of merging the original config of the DynamoDBMapper and the one passed as argument.

**Comment by debora-ito** [comment]
@matiaslb,

the SDK team has reviewed the feature request list for V1, and since they're concentrating efforts on V2 new features they decided to not implement this one in V1. It's still being considered for the DynamoDB Mapper refactor in V2, see the referenced issue above. I'll go ahead and close this one.

Please feel free to comment on the V2 issue with your use case, and reach out if you have further questions.
