### ISSUE TITLE
New S3 Warning Poses Question

### ISSUE THREAD

**Issue by rdifalco** [aws/aws-sdk-java#1203]
In one part of our system we get an S3Object, check its eTag in our system to see if we've retrieved it before and then either read it's contents or close the S3Object. I've noticed you now give this error when we do not read it and just close it. 

```
Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
```
So this begs the question, would you like us to be using 2 round trips to S3 for this? One for its metadata and then another to read it? Is there a good technical reason to make two round trips other than to avoid this message? Doesn't it introduce an atomicity issue? i.e. Read metadata, S3 becomes consistent, read Object that is different from the metadata?

Or is this warning message really necessary?

**Comment by dagnir** [comment]
Hi @rdifalco,

The primary reason we added the warning message is because closing the object stream without reading the data forces the SDK to terminate the connection so the client can't take advantage of connection pooling and increases CPU load especially under high transfer volume. It's there to make the issue known to users so they can avoid it if possible.

If you've tested it and you're okay with the performance hit (for example you don't see duplicates very often) then it's probably safe to ignore.

Regarding the second part of your question, I'm afraid I don't have a good answer for it. Would the metadata change between object PUT's? If not, you could always compare the eTag values from the HEAD and GET requests to ensure the content hasn't changed between the two reads. Another way might be using bucket versioning to retrieve the exact version specified in the HEAD request.

**Comment by rdifalco** [comment]
That works, thanks @dagnir.

**Comment by dagnir** [comment]
Great! Going to go ahead and close this.
