### ISSUE TITLE
com.amazonaws.util.SdkRuntime.shouldAbort() should rather use Thread.currentThread.isInterrupted()

### ISSUE THREAD

**Issue by michaelwiles** [aws/aws-sdk-java#1263]
Currently the shouldAbort method is:

```
   public static boolean shouldAbort() {
        return Thread.interrupted();
    }

```
This method of checking for an interrupt on the thread clears the interrupt flag. This means that any upstream code that also checks for interrupt will get false.

There may be a reason why this interrupt check is used (the one that clears the interrupt flag), would like to know what the thinking for this is.

Should rather be:

    public static boolean shouldAbort() {
        return Thread.currentThread().isInterrupted();
    }

This method of checking for interrupt does not clear the interrupt flag.

**Comment by dagnir** [comment]
I don't have context on why `interrupted()` is used, but the [javadoc](https://github.com/aws/aws-sdk-java/blob/0f9f935d99e7720705f1946767303a173a974da7/aws-java-sdk-core/src/main/java/com/amazonaws/util/SdkRuntime.java#L21-L23) suggests that the decision was intentional.

Interestingly in v2, we switched to using `isInterrupted()`: https://github.com/aws/aws-sdk-java-v2/blob/027abcf5e8ea90b8d339ddd98042afb16495c756/core/src/main/java/software/amazon/awssdk/util/SdkRuntime.java#L21-L26
