### ISSUE TITLE
MultiObjectDeleteException InternalError retry

### ISSUE THREAD

**Issue by jamie-everlaw** [aws/aws-sdk-java#1307]
Hi,

I've been running into an issue where AmazonS3Client.deleteObjects is throwing a MultiObjectDeleteException and the individual errors are all InternalErrors.

I can see from [error best practices](http://docs.aws.amazon.com/AmazonS3/latest/dev/ErrorBestPractices.html) that it's recommended to retry InternalErrors, but [API retries](http://docs.aws.amazon.com/general/latest/gr/api-retries.html) seems to indicate that the SDK will automatically retry requests with InternalErrors. Does deleteObjects not retry requests when encountering an InternalError? What about deleteObject (singular)?

I'm using 1.11.97

Thanks in advance,
Jamie

**Comment by shorea** [comment]
We won't retry a MultiObjectDeleteException since that's treated as a 200 but we would retry InternalErrors from singular deleteObject calls.

I've opened https://github.com/aws/aws-sdk-java-v2/issues/165 to track potential improvements to batch style call in the V2 SDK. It's likely to fall out of scope for GA but I think it could be a useful addition to the SDK and something we are definitely interested in exploring.

**Comment by jamie-everlaw** [comment]
@shorea Thanks so much for the response - I'll go ahead and retry the InternalErrors as individual calls then.
