### ISSUE TITLE
CredentialsProvider type error

### ISSUE THREAD

**Issue by quattrozhou** [aws/aws-sdk-java#1312]
https://github.com/aws/aws-sdk-java/blob/293156398cfc79b2beb29b98e84147942f165d4c/src/samples/AmazonSimpleQueueService/SimpleQueueServiceSample.java#L59

AWSCredentials credentials = null;
credentials = new ProfileCredentialsProvider().getCredentials();

AmazonSQS sqs = AmazonSQSClientBuilder.standard()
.withCredentials(credentials)     <----- Error
.withRegion(Regions.US_WEST_2)
.build();

Error line will complain that credentials is AWSCredentials, not AWSCredentialsProvider.

this error exist in AWSJavaSDKExternalRelease = 1.11.x;
chanzhou@

**Comment by millems** [comment]
The builder only takes credential providers, by design. I'd suggest passing the profile credentials provider directly to the builder, but if you want to be sure the credentials never change you can pass it a set of pre-created credentials by wrapping them in an [`AWSStaticCredentialsProvider`](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/AWSStaticCredentialsProvider.java).

**Comment by shorea** [comment]
Idea for V2. Have BasicAwsCredentials implement AwsCredentialsProvider so customers can just pass that in if they want (but do not have the AwsCredentials interface extend the provider to avoid cases like this where the provider should be passed in).

**Comment by millems** [comment]
In V2, credentials provider is just a functional interface, so they can do
withCredentials(() -> credentials).

**Comment by shorea** [comment]
Fair enough.
