### ISSUE TITLE
Data Pipeline Cloud formation Issue - Stuck in RUNNER state - Seems to be IAM role issue 

### ISSUE THREAD

**Issue by kusharora02** [aws/aws-sdk-java#1317]
[backup1.txt](https://github.com/aws/aws-sdk-java/files/1337153/backup1.txt)
Hi Everyone,

I have an issue in which I am creating data pipeline which take backup of dynamodb to S3 through cloud formation  and pipeline goes to error after 20-20 mint of waiting for runner. seems to be an issue with IAM role I am attaching to the data pipeline.

can some one please help on this. attaching the cf which  take input of 

ddb table name and bucket name.

**Comment by kusharora02** [comment]
LOgs:
27 Sep 2017 12:00:41,312 [ERROR] (TaskRunnerService-df-017074712NG3FUOV38W7_@EmrClusterForBackup_2017-09-27T11:28:58-0)  private.com.amazonaws.services.datapipeline.poller.PollWorker: Poller threw exception
private.com.amazonaws.AmazonServiceException: User: arn:aws:sts::340345914830:assumed-role/sdsd-DataPipelineResourceRole-1573ME5DHN4BY/i-00600a12ac075f3ac is not authorized to perform: datapipeline:PollForTask (Service: DataPipeline; Status Code: 400; Error Code: AccessDeniedException; Request ID: 7be417c6-a37b-11e7-ac30-1fa3cce9c725)
	at private.com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1391)
	at private.com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:904)
	at private.com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:609)

**Comment by millems** [comment]
Hey kusharora02,

Unfortunately we're only really able to help with issues in the Java SDK or things we know off the top of our heads. I'm not sure what your exact error is other than making sure your role has permission to perform 'datapipeline:PollForTask'.

Because this question pertains to data pipeline, you might have more luck asking on stack overflow using the [amazon-data-pipeline](https://stackoverflow.com/questions/tagged/amazon-data-pipeline) tag or on the AWS support forums.

**Comment by varunnvs92** [comment]
Feel free to reopen if you still face the issue.
