### ISSUE TITLE
Improve handling of identifiers with whitespace around them

### ISSUE THREAD

**Issue by dmmiller612** [aws/aws-sdk-java#1320]
Hello,

I recently noticed that if I create a custom table through glue from the awscli or use the crawler, I can query data through Athena using glue immediately with no problems. However, if I use the exact same configuration through the java sdk to build a table through glue (which successfully creates the table) and try to query from the table in athena, I get an internal error. I have triple checked the configuration that it is identical to the table configuration (from the cli or crawler) that works. Do you have any idea what could be causing this? I can provide a query ID to the internal server errors, if needed.

Dependency is newest version: <version>1.11.204</version>

**Comment by dmmiller612** [comment]
By the way, I actually found the bug in my own code. Basically one field had white space in it, and it was really hard to detect. Not sure if the sdk would want to either validate this scenario or trim the white space.

**Comment by millems** [comment]
It's a bit tricky to handle this in the SDK. Table names with white-space around them are technically valid, and could be created using a different SDK, console or an HTTP request. Trimming or rejecting them would make the tables impossible to interact with via the Java SDK. 

Even just logging a heads up when there is a field with whitespace around it could be disruptive to users that intend for that whitespace to be present. It's probably not intentional for a table name, but it would be tough for us to tell in general.

I'll see if an alternate solution comes to mind. Let me know if you can think of anything!

**Comment by dmmiller612** [comment]
I think that is valid.
