### ISSUE TITLE
Buffered version of AmazonKinesisFirehoseClient

### ISSUE THREAD

**Issue by kliakos** [aws/aws-sdk-java#1343]
Similar request to #1109 , but for Amazon Kinesis Firehose.

It will help reduce both cost and resource usage in clients that directly POST data to Kinesis Firehose.

**Comment by shorea** [comment]
+1. It's unlikely we'll get to this soon but we've discussed having a more general batch utility for V2. 

https://github.com/aws/aws-sdk-java-v2/issues/165

**Comment by debora-ito** [comment]
Hi @kliakos,

the SDK team has reviewed the feature request list for V1, and since they're concentrating efforts on V2 new features they decided to not implement this one in V1. It's still being considered for V2, you can track the referenced issue in the previous comment. I'll go ahead and close this one.

Please feel free to comment on the V2 issue with your use case, and reach out if you have further questions.
