### ISSUE TITLE
HTTP retries are logged as debug

### ISSUE THREAD

**Issue by flozano** [aws/aws-sdk-java#136]
I think when a service needs a retry (eg: DynamoDB throughput is exceeded), I want to have the logs of HTTP retries in AmazonHttpClient (pauseExponentially), but it seems I would _have_ to enable DEBUG log in the whole class:

```
        if (log.isDebugEnabled()) {
            log.debug("Retriable error detected, " +
                    "will retry in " + delay + "ms, attempt number: " + retries);
        }
```

This would make my log really chatty.

Would it be possible to raise a little the logging level of this statement? If not, could it be possible to make it configurable or maybe separate it to a different logger (together with any logging statement that makes sense to use in production)?

**Comment by Dicee** [comment]
Hi, I don't think the above really helps, because one common ask would be to figure out after how many retries the request succeeded. You can't do that by implementing a retry condition since it has no visibility on whether the retry will fail or succeed. To do what we would really like to do, the SDK would either need to perform the logging by itself (with perhaps some way to enable or disable it), or expose an interface/class that covers the entire retry workflow, not just a small part which decides if a request should be retried or not after a failure, or some other way for people to plug logic in, such as letting them configure a RetryHandler (just a consumer of some object containing metadata about the failed attempt) and a SuccessHandler (consumer of an object containing the number of retries, the original request etc).
