### ISSUE TITLE
Unable to listObjects from GCS bucket

### ISSUE THREAD

**Issue by gnanamalarvizhi** [aws/aws-sdk-java#1381]
I am unable to listObjects from GCS bucket with the following using aws-java-s3:1.11.228,

ClientConfiguration clientConfiguration = new ClientConfiguration();
clientConfiguration.setSignerOverride("S3SignerType");
AWSCredentials awsCredentials = new BasicAWSCredentials("XX", "XXX");
AmazonS3 amazonS3Client = AmazonS3ClientBuilder.standard()
                .withCredentials(new AWSStaticCredentialsProvider(awsCredentials))
                .withClientConfiguration(clientConfiguration)
                .withEndpointConfiguration(
                        new AwsClientBuilder.EndpointConfiguration("https://storage.googleapis.com", "Multi-Regional"))
                        .build();

 amazonS3Client.listObjects(bucketName);

Getting this error,

` com.amazonaws.services.s3.model.AmazonS3Exception: Invalid argument. (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: null; S3 Extended Request ID: null), S3 `Extended Request ID: null

But I am able to perform getObjects and putObjects operations properly without any issues.

 Questions:

 1. What is the argument I missed here.
 2. I think region is the problem. How do I pass the GCS region to AWS properly instead of multi-regional?
 3. What is the difference between bucket location and bucket region

**Comment by varunnvs92** [comment]
Does GCS mean Google cloud storage regions? S3 is AWS service and our SDK works only for aws regions. See below link for list of aws regions.
http://docs.aws.amazon.com/general/latest/gr/rande.html

The region you pass for [EndpointConfiguration](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/client/builder/AwsClientBuilder.java#L453) is used for signing. So it should the region where the bucket is located. For example if your buckets are in us-west-2 region, you would pass "us-west-2" instead of "Multi-Regional".

>What is the difference between bucket location and bucket region

Both are same

I am also surprised how you were able to successfully call getObjects and putObjects. Multi-regional is not an officially recognized aws region and you should be getting error.

**Comment by varunnvs92** [comment]
I didn't notice the google endpoint you are using. This means you are sending requests to a endpoint that is not maintained by AWS. This looks like a 3rd party app maintained by Google. This is not our product and we can't help you with this issue. 

Can I know the motivation for using GCS over AWS endpoints?

**Comment by varunnvs92** [comment]
Feel free to reopen if you have SDK related questions.
