### ISSUE TITLE
Support passing null to a DynamoDBTypeConverter

### ISSUE THREAD

**Issue by csimmons0** [aws/aws-sdk-java#1408]
The DynamoDBTypeConverted annotation and the DynamoDBTypeConverter interface do not allow a converter to change null into something else. I avoid using nullable pointers in all of my code, choosing to use Optional instead. I would like to be able to use a DynamoDBTypeConverter to change null fields into empty Optionals. I've already written a converter to do this, expecting it to work, but I just noticed that it's not working because the SDK doesn't pass null to a converter.
```
public class OptionalConverter<Clazz> implements DynamoDBTypeConverter<Clazz, Optional<Clazz>>
{
    @Override
    public Clazz convert(Optional<Clazz> object)
    {
        return object.orElse(null);
    }

    @Override
    public Optional<Clazz> unconvert(Clazz object)
    {
        return Optional.ofNullable(object);
    }
}
```

**Comment by csimmons0** [comment]
I've never implemented an annotation before, but I'm thinking I may be able to implement this by adding a property like "passNull" with a default value of false to DynamoDBTypeConverted.

**Comment by arungupta2008** [comment]
Any updates on this feature? I am also looking for this feature.

**Comment by debora-ito** [comment]
@csimmons0 @arungupta2008 

The SDK team has reviewed the feature request list for V1 and decided not to implement this one, since they're concentrating efforts on V2 new features. It's still being considered for the DynamoDB Mapper refactor in V2, see the referenced issue above. I'll go ahead and close this.

Please feel free to comment on the V2 issue with your use case, and reach out if you have further questions.
