### ISSUE TITLE
Question about using AmazonS3Builder vs. new AmazonS3Client

### ISSUE THREAD

**Issue by nezihyigitbasi** [aws/aws-sdk-java#1423]
Creating an `AmazonS3Client` with the builder API (`AmazonS3Builder`) vs. the `AmazonS3Client` constructor behaves differently: the former throws an exception if the region is not explicitly set (`Unable to find a region via the region provider chain.  etc. etc.`).

Which region can I use to get the same behavior with the `AmazonS3Client` constructor?

I am using version `1.11.165`.

**Comment by dagnir** [comment]
The deprecated no-arg constructor `new AmazonS3Client()` will default to `us-east-1`, so the equivalent with the builder is

```java
        return AmazonS3ClientBuilder.standard()
                .withRegion(Regions.US_EAST_1)
                .build();
```

Note that the error is because [`DefaultAwsRegionProviderChain`](https://github.com/aws/aws-sdk-java/blob/986a6f93ecc3d0593b5d9a38d1cf8ef04251538b/aws-java-sdk-core/src/main/java/com/amazonaws/regions/DefaultAwsRegionProviderChain.java#L20) could not find a suitable region from the execution environment. If you have an SDK config file under `~/.aws/config` for example, then it will use the region given in the default profile. See here for more information http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html
