### ISSUE TITLE
Cognito - AliasExistsException

### ISSUE THREAD

**Issue by mataide** [aws/aws-sdk-java#1424]
I set the cognito to allow users signin with username or email as alias.

But when I signup a new user with the same email (verified) before.
No AliasExistsException is throw.

I need to verify it with the trigger PreSignup?
What I need to do to wont allow an user register with an email already used.

**Comment by dagnir** [comment]
Hi @mataide this looks like a Cognito usage question. Since we have limited bandwidth to respond to issues, we reserve GitHub only for issues with the SDK itself. Can you please open a question over on [StackOverflow](http://stackoverflow.com/questions/tagged/aws-java-sdk) or open a [support case](https://console.aws.amazon.com/support/) per our [`README`](https://github.com/aws/aws-sdk-java/blob/1.11.254/README.md#getting-help)?

**Comment by mataide** [comment]
Already have this question there: https://stackoverflow.com/questions/44742574/when-a-user-is-signing-up-does-amazon-cognito-automatically-check-if-their-emai/44769161#44769161

But in my case it doesnt happen, so its a bug or a mistake?
