### ISSUE TITLE
Support for cli 'compose' command

### ISSUE THREAD

**Issue by Supagoat** [aws/aws-sdk-java#1429]
I don't see a way in the Java API to do what the ecs cli 'compose' command does.  Are there plans to add that to the Java API?

**Comment by kiiadi** [comment]
Are you referring to this : [ecs-cli compose](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose.html) ? This is actually an ECS specific utility rather than something exposed generically through the AWS CLI : https://aws.amazon.com/cli/

I admit I'm not hugely familiar with Docker but it seems that this is very much a utility for scripting deployments - probably not something that would have huge demand in the Java application space. At this time I don't think it's likely we'll be adding support for this to the Java SDK in the near future.

That said we do accept pull requests - or if you wanted to create a separate github project for this we would be happy to take a look.
