### ISSUE TITLE
CJK Characters are not listed in S3 Object listing

### ISSUE THREAD

**Issue by samrajcse** [aws/aws-sdk-java#1432]
We have few files in S3 with CJK characters. Those files are not listed with the valid format. This issue is also available in AWS s3 console too. 

Please look into this ASAP.

**Reference Screenshot:**

![image](https://user-images.githubusercontent.com/696988/34525522-400224cc-f0c5-11e7-811f-1c9e47b6383a.png)

**Comment by kiiadi** [comment]
@samrajcse how do these keys appear when you call listObjects via the AWS CLI? `aws s3api list-objects --bucket YOUR_BUCKET_NAME` can you give me some of the unicode code points so that I can try to reproduce?

Whilst S3 Object Keys' can be any valid UTF-8 string, S3 does have some recommended naming guidelines outlined [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-keys).

**Comment by shorea** [comment]
@samrajcse I am closing this issue due to no response. Feel free to reopen if problem persists.
