### ISSUE TITLE
Error: "The authorization header is malformed"

### ISSUE THREAD

**Issue by nezihyigitbasi** [aws/aws-sdk-java#1451]
We have a user report saying that he is getting 

```
The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'
````

after (I believe) moving from the deprecated `new AmazonS3Client(...)` to the new `AmazonS3ClientBuilder`. 

Previously I raised a question about how to set the region properly in #1423 and based on that we set it to `us-east-1` with the new builder API and I guess that's causing this problem.

In the working version [here](https://github.com/prestodb/presto/blob/c5e1b7c1b636f4d45fcb3e9bd542d13d58de9a43/presto-hive/src/main/java/com/facebook/presto/hive/s3/PrestoS3FileSystem.java#L631-L666) is how we create a new s3 client.

And [here](https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/s3/PrestoS3FileSystem.java#L624-L675) is the version that throws this error (I suspect L671 is causing the issue).

Note that `pinS3ClientToCurrentRegion` is `false` when the user gets the error. The problem goes away when `pinS3ClientToCurrentRegion` is set to `true`, but the user has buckets in multiple regions so that's not an option.

**Comment by millems** [comment]
By default, the builder-created client does not work cross-region. You can enable cross-region behavior with [setForceGlobalBucketAccess(true)](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Builder.html#setForceGlobalBucketAccessEnabled-java.lang.Boolean-).

**Comment by nezihyigitbasi** [comment]
So the default behavior with the deprecated `AmazonS3Client` constructors was different (enabling global bucket access), just curious what was the reason behind this behavior change?

**Comment by millems** [comment]
We wanted people to explicitly opt-in to the behavior so that they can understand the risks of enabling the feature:
1. There's an extra latency hit accessing buckets other than the ones for which your client is created. This is both because the bucket has to travel farther physically (eg. us-west-2 to us-east-1) and because the first time the bucket is accessed, the SDK must make an initial call to AWS to determine the correct bucket region.
2. At this time, there can be extra cost to the object owner when objects are downloaded to other regions (consult the transfer pricing guide for the latest details: https://aws.amazon.com/s3/pricing/).
3. If you are in a VPC or have firewall rules that restrict access to other regions, attempts to access buckets in other regions could result in a connect timeout instead of an error message notifying you of the bucket being in another region.
4. There are (nearly) no other services for which the SDK offers this kind of resource region discovery. For every other service, you must understand the region of the resource you're interacting with. If someone were to assume that the S3 client behaved like every other AWS service client, they would have been incorrect.

**Comment by nezihyigitbasi** [comment]
>>  For every other service, you must understand the region of the resource you're interacting with. 

In our case the system ([Presto](http://prestodb.io)) may access buckets from different regions, so I guess it makes sense to have an s3 client per region. But then how can I get the region of a particular bucket to create an s3 client for that particular region? (I know that there is an aws method `getBucketLocation()` for that, but you need to have a client to call it, I need the region before I create a client).

**Comment by spfink** [comment]
You can call getBucketLocation() or HeadBucket using a client that is not in us-east-1 and get back the region for that bucket. So have one client that you use to call HeadBucket and then once you determine the bucket's region switch to that client for further operations.

**Comment by shorea** [comment]
@nezihyigitbasi If you do need to access buckets in multiple regions I recommend using the force global bucket access option that @millems mentioned instead of doing your own bucket discovery. Bucket discovery can be quite complex and there's a lot of edge cases to consider, the SDK already has that implemented so it's a better option for you.

**Comment by ReneI** [comment]
>
