### ISSUE TITLE
Ant build of kinesis sample is broken

### ISSUE THREAD

**Issue by Ohadbasan** [aws/aws-sdk-java#1460]
Trying to run the sample project of amazon kinesis.
the ant build seems to be broken.
running "ant compile" fails on

'aws-sdk-java/src/third-party does not exist.'

**Comment by dagnir** [comment]
@Ohadbasan You will need to have the SDK JAR's in `aws-sdk-java/src/third-party` as that's where the build expects the JARs to be. If you're trying to do this from a clone of the repo it won't work because those JARs are not included in the repo. You can either build the SDK JARS yourself and add them to the directory, or download the ZIP distribution of the SDK which will contain both the sample code and the required JARs.

**Comment by dagnir** [comment]
Closing this issue. Please feel free to reopen if the guidance above doesn't work.
