### ISSUE TITLE
how can I preprocess input data before making predictions in sagemaker?

### ISSUE THREAD

**Issue by algoscale1** [aws/aws-sdk-java#1530]
I am calling a Sagemaker endpoint using java Sagemaker SDK. The data that I am sending needs little cleaning before the model can use it for prediction. How can I do that in Sagemaker.

I have a pre-processing function in the jupyter notebook instance which is cleaning the training data before passing that data to train the model. Now i want to know if i can use that function while calling the endpoint or is that function already being used?
I can show you my code if you want?

**Comment by dagnir** [comment]
Hi @algoscale1 since this is a usage question, could you please post the question on [StackOverflow](http://stackoverflow.com/questions/tagged/aws-java-sdk) and tag it with `aws-java-sdk`? We use the GitHub issues page for bugs and issues with the SDK only, since we have limited bandwidth to address them.

**Comment by algoscale1** [comment]
Ok thanks
