### ISSUE TITLE
Cloud watch does not give data point on metrics updating time

### ISSUE THREAD

**Issue by MrAta** [aws/aws-sdk-java#1553]
I'm using AWS Java SDK to connect to CloudWatch and monitor my t2 instance.
I'm using this code to fetch the CPUCreditBalance metric every 10 seconds. I know that the metric is updated every 5 minutes. This code works fine and prints out the value every 10 seconds except that exactly on the time that CloudWatch is updating the metric, it does not return any value and encounters an exception.

          GetMetricStatisticsRequest request = new GetMetricStatisticsRequest()
                .withStartTime(new Date(new Date().getTime() - 300000))
                .withNamespace("AWS/EC2")
                .withPeriod(60 * 60)
                .withMetricName("CPUCreditBalance")
                .withStatistics("Average")
                .withDimensions(Arrays.asList(instanceDimension))
                .withEndTime(new Date());
            int credits = 0;
            try {
                GetMetricStatisticsResult result = cw.getMetricStatistics(request);
                credits= result.getDatapoints().get(0).getAverage().intValue();
                System.out.println("Got current credits: " + credits);
            } catch (Exception e) {
                System.out.println("Got exception: " + e.toString());
            }
            Thread.sleep(10*1000);    // sleep for 10 secs
        }`

Is this something related to the CloudWatch back-end or my code?

**Comment by MrAta** [comment]
@shorea 
Index out of bound exception on `result.getDatapoints().get(0)`

**Comment by zoewangg** [comment]
Hi @MrAta, from the [GetMetricStatisticsRequest Doc](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/cloudwatch/model/GetMetricStatisticsRequest.html#withEndTime-java.util.Date-), endTime is exclusive, extending end time might help.

Since this is a service-specific question, the AWS forums, stack overflow or AWS support may be a better place to engage the service team and get better support.

https://forums.aws.amazon.com/forum.jspa?forumID=138
