### ISSUE TITLE
Possible timing side-channels

### ISSUE THREAD

**Issue by nilizadeh** [aws/aws-sdk-java#1565]
Dear AWS SDK for Java developers,

We think that we might have found some timing side-channels in the following classes (method equals()) listed bellow, and we believe there could be more of the same vulnerability in other classes:

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-secretsmanager/src/main/java/com/amazonaws/services/secretsmanager/model/GetSecretValueResult.java

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-iot/src/main/java/com/amazonaws/services/iot/model/Certificate.java

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-api-gateway/src/main/java/com/amazonaws/services/apigateway/model/Authorizer.java

They may be due to 1) the use of if branches for different secret values and 2) the use of String.equals for comparison which returns as soon as a character does not match. Both of them can cause a timing side channel, which could be used by a potential attacker to obtain knowledge about the hidden secret values.

Do you agree with our findings?

Thanks,
Shirin Nilizadeh
Postdoctoral Researcher
CyLab
CMU Silicon Valley

**Comment by varunnvs92** [comment]
I don't have much knowledge about the timing side channels attack. Based on my quick reading, I don't understand how this attack can be applied on these classes. Actual processing of request and response generation is done on service end. The response is sent over http to the SDK and SDK unmarshalls the response into these POJOs. 

I don't see how the SDK is affected. Maybe this is due to my limited knowledge on the side channel attack. If you think SDK is affected, Please provide more information about the attack scenario. Fyi, these classes are generated and changing them will break customers.

**Comment by nilizadeh** [comment]
Thanks for the quick response. If an attacker can time the execution of methods "equals" on a secret value, it can infer some information about it since there is a relationship between the secret and execution time. But if method "equals" is never called to compare actual secret data or if it is not possible for an attacker to perform time measurements then this is not a concern.

**Comment by varunnvs92** [comment]
The method "equals" is called by the SDK user in their application. It is a local call. So the attacker can't call the method or time the method unless attacker already has access to the application (in which case timing issue is not a concern). So I guess the SDK is not affected by this issue. Does my explanation make sense?

**Comment by nilizadeh** [comment]
In that case then probably SDK is not affected by this issue, however depending on how the user applications are implemented and call "equals" on secret data then still there is a chance that this vulnerability can be used. Do you think that such scenarios are possible?

**Comment by varunnvs92** [comment]
"equals" is a local call, so data is not sent on the network. To compute the equals method execution time, attacker has to have access to the application or hosts running the application. In this case, as attacker has already access to application they can directly get the data instead of going for the timing attack. So I don't think this attack is applicable for the "equals" method.

**Comment by nilizadeh** [comment]
In principle an attacker can time the execution even without having access to the application but indeed this seems of very limited concern.

**Comment by varunnvs92** [comment]
Yep, I don't see a concern in this case. Resolving the issue. Feel free to reopen if you have more details and believe SDK has a vulnerability.
