### ISSUE TITLE
S3 TransferManager incompatible with AWS X-Ray

### ISSUE THREAD

**Issue by willvk** [aws/aws-sdk-java#1572]
Having a few problems trying to trace a component, such as TransferManager, which manages its own thread pool. My guess would be to write your own extends of ExecutorService and then use the setExecutor(). This seems invasive and I think that integration between TransferManager and Xray should be provided more easily.

This issue/feature is similar to the one raised in the python library;
[python github issue 52](https://github.com/aws/aws-xray-sdk-python/issues/52)

Currently we have pulled the use of Transfer Manager and have reverted to just serially calling it for each part of our multipart upload, due to S3 Segment Not Found which results when the threads try to execute the upload.

Ideally Transfer Manager would be enhanced to be more compatible with Xray by enabling the TransferManagerBuilder to take a .withTraceEntity(Entity segment), which could then be injected into the new threads within that threadpool.
[Injecting Trace Entity](https://docs.aws.amazon.com/xray/latest/devguide/scorekeep-workerthreads.html)

**Comment by debora-ito** [comment]
Hi @willvk the SDK team has reviewed the feature request list for V1, and since they're concentrating efforts on V2 new features they decided to not implement this one in V1. It's still being considered for the TransferManager refactor in V2, see the referenced issue above. I'll go ahead and close this.

Please feel free to comment on the V2 issue with your use case, and reach out if you have further questions.

**Comment by Zhenye-Na** [comment]
Hey, are there any updates for this issue?
