### ISSUE TITLE
Do you really need joda-time?

### ISSUE THREAD

**Issue by ptahchiev** [aws/aws-sdk-java#1580]
Can't you just use `java.time.LocalDateTime` instead? If you really need joda-time, then I suggest you mark the dependency as compile scope and do some checks if the user has included it in their classpath.

**Comment by millems** [comment]
Unfortunately LocalDateTime was added in Java 8, and we need to maintain compatibility with Java 6. Because joda-time classes are exposed in our public APIs, we won't be able to make it just a compile-time dependency without a lot of customer headache.

We've removed joda-time as a dependency in V2 of the SDK, which is currently in developer preview: https://github.com/aws/aws-sdk-java-v2
