### ISSUE TITLE
Please remove finalize() method in class InstanceProfileCredentialsProvider

### ISSUE THREAD

**Issue by mhankus** [aws/aws-sdk-java#1610]
Currently InstanceProfileCredentialsProvider uses finalize() to cleanup resources (it implements Closable, and close() method is doing the same cleanup). Due to existence of finalize() method, object is not garbage collected, and stays in memory until it is too late to reclaim it (there is not guarantee that finalize() will be called, but it must be called for object to be garbage collected). Additionally any exception in finalize is ignored - so it is very hard to be sure that it is executing correctly)

Additionally finalize() is deprecated starting Java 9 - so relaying on deprecated methods in a long run will be problematic.

https://docs.oracle.com/javase/9/docs/api/java/lang/Object.html#finalize--

Currently it is causing some problems as shown below 

![image](https://user-images.githubusercontent.com/6095361/40877734-2708ceb2-6686-11e8-82fa-0e5915fd8ee0.png)

**Comment by zoewangg** [comment]
Hi, I'm not sure if we can get to it soon but `InstanceProfileCredentialsProvider` in v2(currently in developer preview) doesn't have `finalize()`. https://github.com/aws/aws-sdk-java-v2/blob/master/auth/src/main/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProvider.java

**Comment by millems** [comment]
Unfortunately I don't believe removing `finalize()` is possible. Some people are using it as the only way to clean up their resources, and while that's incorrect it would break them very badly to remove it now. We are ensuring that finalizers aren't relied on for object lifecycle management in 2.0 where upgrading customers should expect behavioral changes.

If you make sure to call `instanceProfileCredentialsProvider.close()`, the finalizer won't do anything, so it shouldn't bottleneck your GC. If you're running into issues with your GC really hating finalizers for some reason, a single `InstanceProfileCredentialsProvider` can be cached and shared throughout the application so that it won't ever need to be GC'd.

**Comment by mhankus** [comment]
Thank you for trying. Problem with finalize() is different. Calling close() will not help, because:
1. finalize() must be called for object to be garbage collected
2. Every object instance keeps reference to Classloader which loaded that class
3. Classloader keeps references to all classes which it loaded

so by implementing finalize() in object, you make graph of ALL classes reachable by GC - so it will not be released from memory. Single finalize() method keeps tens or hundred of megabytes of memory. It must be called to free this memory

**Comment by millems** [comment]
It's unusual that a classloader would hold a reference to all the classes it loaded, since a single classloader is usually long-lived. That's true whether or not the class has a finalizer.

FInalizers are surprisingly common. For instance, `ThreadPoolExecutor`, a very common class provided by the JVM, uses a `finalizer` to shut down. 

Are you trying to diagnose a memory leak? The existence of a finalizer should not cause one, unless the object takes a long time to finalize.
