### ISSUE TITLE
AmazonS3ClientBuilder instantiate amazonS3 client even though credentials are null or invalid

### ISSUE THREAD

**Issue by MkJha** [aws/aws-sdk-java#1625]

**Comment by MkJha** [comment]
Its quite strange that it checks for region(null/invalid) case but ignores validation for critical attributes like access key and secret key

**Comment by varunnvs92** [comment]
Amazon S3 allows customers to enable anonymous access where anyone can access the resources. In that case, credentials can be null and are valid.

What specific validations are you referring to about region?

**Comment by MkJha** [comment]
Thanks @varunnvs92  for the quick help. For region
1.  if you pass an invalid region(eu-west-1234 instead eu-west-1), the client gets instantiated. In ideal case it should not be the case. 
2. AmazonS3 client are region specific, so by mistake/unknowingly if you perform any action on a bucket which doesn't belong to the region passed while instantiating client; it goes ahead. So for example , while uploading file to different region bucket , transfer manger goes ahead and in the end status is failed

**Comment by varunnvs92** [comment]
>> if you pass an invalid region(eu-west-1234 instead eu-west-1), the client gets instantiated. 

We don't do client side validation to ensure we are compatible with future regions. For example, an old SDK (1.10.x) will not have information about the new regions added recently. But if customer using the old SDK uses any of the new regions, it still works as we just send requests to that endpoint. What would happen if we do client side validation? The call fails because the old sdk doesn't know about the new region even though its valid. Now customers has to upgrade to latest SDK to use new regions which is not ideal. This is the reason we don't do client side validation.

>> AmazonS3 client are region specific

This is not entirely true. Amazon S3 supports both global and regional endpoints (its always recommended to use regional endpoint). s3.amazonaws.com is the global endpoint. When a request is sent to this endpoint, it automatically figures out the correct region and forwards the request there. This was legacy behavior and we can't turn it off as it will break customers. 
As I mentioned before, we don't do client side validation as we can't exactly know the customer's intention (using global endpoint vs regional endpoint). Doing client side validation involves find bucket regions via API call which adds extra latency. Most customers don't prefer this.

I hope this answers your questions. Let me know if you have more questions.

**Comment by MkJha** [comment]
Yes, it make sense. I have one final question after that we can close this:

1. When you say "Amazon S3 supports both global and regional endpoints (its always recommended to use regional endpoint). s3.amazonaws.com is the global endpoint." 

When i use latest aws Java sdk, if i don't want to specify a specific region, what region to pass while 
instantiating client(in a sense client not tied to specific region). I mean when region is not specified, i would like to kepp my client global so that i can talk to buckets of any region . How can i do that?

**Comment by varunnvs92** [comment]
S3 us-east-1 endpoint acts as the global endpoint. Look for us-east-1 endpoints for S3 in this [doc](https://docs.aws.amazon.com/general/latest/gr/rande.html). You can see they don't follow same pattern as other regions. I am not sure why it was designed like that but the current recommendation is to use regional endpoints whenever possible.

To use global endpoint, create s3 client with constructor and not specific a region. If you are using client constructors, there is an ```enableForceGlobalBucketAccess``` method. As I mentioned,  this is discouraged as SDK has to internally do a HEAD API call to find the bucket region and then execute the actual call you requested. This involves additional latency. There can be other behavioral edge cases while using the global endpoint.

**Comment by varunnvs92** [comment]
Feel free to reopen if you have more questions. Thank you
