### ISSUE TITLE
Unable to complete transfer: Connection pool shut down

### ISSUE THREAD

**Issue by gravindran2412** [aws/aws-sdk-java#1629]
I am using transfermanager to upload file to s3. But on calling waitForCompletion, it is throwing the below exception:
Unable to complete transfer: Connection pool shut down

Here is my code:
`@Bean
  public TransferManager s3TransferManager(AmazonS3 amazonS3) {
      return TransferManagerBuilder.standard().withS3Client(amazonS3).build();
  }`

`  Upload xfer = s3TransferManager.upload(bucketName, keyPrefix+"/test_file.csv", file);
        try {
			xfer.waitForCompletion();
		} catch (AmazonClientException | InterruptedException e) {
			e.printStackTrace();
		}`
Exception:
`com.amazonaws.AmazonClientException: Unable to complete transfer: Connection pool shut down`
Thanks!

**Comment by varunnvs92** [comment]
The error indicates that the underlying connection pool is being shutdown while the transfer is in progress. It happens when a thread closes the s3 client or calls shutdownNow on transfer manager. Is the transfer manager shared across multiple threads? 
Is it possible that the Transfer Manager is being shut down by another thread?

**Comment by varunnvs92** [comment]
Feel free to reopen if you still have the issue.
