### ISSUE TITLE
Deregister Directory from Workspaces service/application

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#1634]
Hi
I’m trying to delete Directory through SDK
But it turned to be that this directory previously registered with Workspaces service
Now I can’t delete it without Deregistering this directory from WAM
I know how this done from the console… but how I can do this using SDK?? I’m not able to find any api for that

**Comment by varunnvs92** [comment]
We auto-generate the clients using specific service models. This repo is mainly for tracking bugs and feature requests in the SDK core. We have limited knowledge of all services. For questions on using a specific service, I would say engage directly with service team through AWS forums or post it on stack overflow to involve wider user community. See our [getting-help](https://github.com/aws/aws-sdk-java#getting-help) guide. Thank you.

I could not find any relevant APIs for the action you want. Its possible that I could not recognize them due to my limited knowledge of Workspaces service. Found couple of official docs. Hope they help. If not, I would suggest asking the question on stack overflow and AWS forums.
https://forums.aws.amazon.com/thread.jspa?threadID=172989
https://docs.aws.amazon.com/directoryservice/latest/admin-guide/ms_ad_delete.html
