### ISSUE TITLE
SDKClientException: Unable to execute HTTP request: The target server failed to respond

### ISSUE THREAD

**Issue by justinborromeo-toast** [aws/aws-sdk-java#1642]
I'm using the Kinesis Client Library to run Integration Tests against a Kinesis stream running locally using LocalStack.  The LocalStack container is running with SSL enabled as the Kinesis Producer Library requires that.  When I try to connect to my local kinesis streams and list the stream names, I receive `SDKClientException: Unable to execute HTTP request: The target server failed to respond` and `Caused by: org.apache.http.NoHttpResponseException: The target server failed to respond` errors.`

My code is as follows:
````
@RunWith(LocalstackDockerTestRunner.class)
@LocalstackDockerProperties(services={"kinesis"}, environmentVariableProvider = LocalstackEnvironmentVariableProvider.class)
public class EmafIT{
    @Before
        public void setup() throws Exception {
            AmazonKinesis kinesis = DockerTestUtils.getClientKinesis();
            ListStreamsResult streams = kinesis.listStreams();
        }
}
````

Is this an issue with how I set my KCL or Localstack up?

If you need any more info, let me know.

**Comment by dagnir** [comment]
Hi @justinborromeo-toast, as the error suggests, the client is not able to open a connection to the mock server. It looks like you've already opened a similar issue on LocalStack's page: https://github.com/localstack/localstack/issues/813. At the moment this doesn't look like the issue is being caused by the SDK; I would suggest following up with the LocalStack devs to see if maybe there's some extra initialization steps needed.

**Comment by bobtiernay-okta** [comment]
May be related to https://github.com/aws/aws-sdk-java/issues/1212
