### ISSUE TITLE
Release 1.11.374 does not seem to be published to Maven Central yet?

### ISSUE THREAD

**Issue by sopel** [aws/aws-sdk-java#1697]
Hi Team,

According to the CHANGELOG, you have released version [1.11.374](https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111374-2018-07-25) about 12 hours ago. The Maven artifacts do not yet seem to be available in Maven Central though (sample search for [aws-java-sdk-cloudformation](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.amazonaws%22%20AND%20a%3A%22aws-java-sdk-cloudformation%22)).

Is there an expected delay between the release commit here and the artifacts being available in Maven Central, or has there been a hiccup in the CD pipeline this time around?

Many thanks,
Steffen

**Comment by zoewangg** [comment]
Thanks for reporting and we are actively investigating it right now. Meanwhile, you can still use the latest version by downloading 1.11.374 jar from https://sdk-for-java.amazonwebservices.com/latest/aws-java-sdk.zip

**Comment by zoewangg** [comment]
The root cause is there was some delay in the OSS SonarType syncing jobs that release the artifacts to Maven Central and it's resolved now. Apologies for the delay.

You should be able to use 1.11.374 or the latest version 1.11.375(as of July 27th 2018) from Maven. https://search.maven.org/#artifactdetails%7Ccom.amazonaws%7Caws-java-sdk-cloudformation%7C1.11.375%7Cjar
