### ISSUE TITLE
Waiter for CloudFormation does not terminate

### ISSUE THREAD

**Issue by hoegertn** [aws/aws-sdk-java#1712]
When trying to delete a stack that cannot be deleted due to exports, the stack end with the state `UPDATE_COMPLETE`. This is not a valid end state for the `stackDeleteComplete` waiter in `AmazonCloudFormationWaiters`. Therefore the waiter never reaches the end.

see https://github.com/jenkinsci/pipeline-aws-plugin/issues/116 for a problem caused by this

**Comment by shorea** [comment]
What's the expected behavior? These seems like it should be a failure terminal state as the stack was not deleted.

**Comment by loukou007** [comment]
When trying to delete an already used stack, an exception is fired with a status reason "Export xxxxxxx cannot be deleted as it is in use by xxxxx" which is an expected behavior. The problem here is that "STATUS" is not updated and takes the value of the latest status. The expected behavior is to update "STATUS" with "DELETE_FAILED" 
![screenshot from 2018-07-30 10-29-11](https://user-images.githubusercontent.com/29372722/43786094-22825550-9a68-11e8-8740-6f67bc5d714b.png)

**Comment by millems** [comment]
We've gotten a list of delete failure conditions from CloudFormation and are working to integrate them into the waiter. We're also double checking the update and create waiters are correct, while we're at it.
