### ISSUE TITLE
LambdaInvokerFactory does not support plain string inputs

### ISSUE THREAD

**Issue by MikeFHay** [aws/aws-sdk-java#1743]
I have a Lambda which takes a string as an input. Trying to call this Lambda using LambdaInvokerFactory fails, as the invoker json-encodes the string before sending it. I see that the Jackson ObjectMapper used by the invoker can be customized, but I don't see any way to make it not json-encode the output.

Incomplete example code:
```
interface MyLambda {
    @LambdaFunction(functionName = "MyFunction")
    String myFunction(String input)
}

public void test() {
    MyLambda invoker = LambdaInvokerFactor.builder()(...).build(MyLambda.class);
    invoker.myFunction("{\"Please don't json-encode this string\": \"no\"}");
}
```

Workaround is to just use AWSLambda#invoke directly.

**Comment by zoewangg** [comment]
What exception did you get?
What version of lambda client are you using?

**Comment by MikeFHay** [comment]
There's no exception, the client successfully sends data to the Lambda, it's just the wrong data (it treats my plain text input as a json string value and escapes it before sending it). The context is I have a Java Stream-handling Lambda which does its own JSON-deserialization. This works fine for any non-magical client sending plain json Strings, but not for LambdaInvokerFactory which assumes its input is not json and needs transformed into json, even when the input is a single String, not an object.

I'll get back to you re: versions but I believe I'm using a very recent version.

**Comment by millems** [comment]
Yeah, it looks like we're just calling [ObjectWriter.writeValueAsString](https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/ObjectWriter.html#writeValueAsString(java.lang.Object)) on the parameter. We would probably need to enable custom serializers to be specified on the parameter, function or `LambdaInvokerFactory` or to be able to support this in a backwards-compatible way.

Marking as a feature request.

We're focusing effort on the [API Gateway generated SDKs](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-generate-sdk.html) nowadays instead of lambda proxies directly, so I'm not sure if we will be able to get to this anytime soon. Pull requests are always welcome, though!
