### ISSUE TITLE
CI failing sometimes with IdleConnectionReaperTest

### ISSUE THREAD

**Issue by davidmoten** [aws/aws-sdk-java#1745]
From https://travis-ci.org/aws/aws-sdk-java/jobs/421303699. 
```
Failed tests: 
  IdleConnectionReaperTest.maxIdle_HonoredOnClose:85 
Wanted but not invoked:
httpClientConnectionManager.closeIdleConnections(
    10000,
    MILLISECONDS
);
-> at com.amazonaws.http.IdleConnectionReaperTest.maxIdle_HonoredOnClose(IdleConnectionReaperTest.java:85)
Actually, there were zero interactions with this mock.
```

**Comment by millems** [comment]
It's not a great test, since it relies on global state, but I'm not entirely sure why it's failing since tests should run in serial right now...

**Comment by millems** [comment]
We never set `shuttingDown` back to false in the connection reaper. There's even a comment saying that. Why though?

**Comment by millems** [comment]
Nevermind, it's an instance variable. Getting some caffeine...

**Comment by millems** [comment]
Made a change to immediately check stale connections when the idle connection reaper is started instead of waiting 60 seconds. That will give the scheduler 60 seconds more to run our reaper thread. 30 seconds already seems like plenty, but there's no other obvious reason for this failure and it'll speed our build up by 60 seconds.

**Comment by millems** [comment]
This change will go out today. Thanks again for your report.
