### ISSUE TITLE
DynamoDB PaginatedList should use IDynamoDBMapper interface instead of concrete DynamoDBMapper

### ISSUE THREAD

**Issue by efenderbosch** [aws/aws-sdk-java#1802]
As title. Makes extending and mocking some things difficult.

**Comment by debora-ito** [comment]
The SDK team has reviewed the feature request list for V1 and this one looks like a great candidate for a community PR, which we’ll help merge in and support.

**Comment by kmbotts** [comment]
This looks pretty dirt simple to do. looking for some contribution work in the evenings. I'll need some assistance with unit tests, for some reason they hate me. The V2 has a wiki for developers, but can't seem to find the wiki for the V1 repo.

For the fix, I plan on deprecating the constructors that use concrete class and add new ones that accept the interface. Probably don't even need to go that far really, but will fix based on team's preference.

**Comment by dratler** [comment]
Hi @debora-ito ,  @kmbotts 
Is this still open for the grab ?

**Comment by kmbotts** [comment]
I’m not actively working on it. I recall it being a cascade of changes and didn’t see a super simple fix that I liked. Worth another pair of eyes I suppose.

**Comment by debora-ito** [comment]
@efenderbosch we don't have plans to make this change before going into [Maintenance Mode](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/). If this issue is still relevant in v2 please open a [new issue](https://github.com/aws/aws-sdk-java-v2/issues/new/choose) in the v2 repo.

#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)
