### ISSUE TITLE
S3Client does not delete part files after a download was cancelled.

### ISSUE THREAD

**Issue by zgrkpnr** [aws/aws-sdk-java#1807]
When a download is started using `com.amazonaws.services.s3.transfer.TransferManager` and it completes then part files are deleted after they are merged into a single file. 

However, if we call `cancel()` on `com.amazonaws.services.s3.transfer.Download` those part files stay there indefinitely. Moreover, transfer continues a couple of seconds after we call `cancel()`, before it actually stops all the progress.

I assume the information is enough to identify the problem. If further info or example code is required I would be pleased to provide.

**Comment by serkantuna** [comment]
I have the same problem and I debugged the code. I see that cancel functionality is not working properly for multipart downloads. When you call cancel on a Future object, I expect the callable to throw exception and do some cleanup. 

In this case, I see a catch block in DownloadCallable that is supposed to cancel the parts.

 ```
catch (Throwable t) {
            // Cancel all the futures
            for (Future<File> f : futureFiles) {
                f.cancel(true);
            }
            // Downloads aren't allowed to move from canceled to failed
            if (download.getState() != TransferState.Canceled) {
                download.setState(TransferState.Failed);
            }
            if (t instanceof Exception)
                throw (Exception) t;
            else
                throw (Error) t;
        }
```


But I observe that the code does not go into this catch block because the future object of the monitor has changed to a CompleteMultipartDownload.

When I look at the CompleteMultipartDownload class, I don't see any catch block to do cleanup when there is an interrupt. So, Download.abort() method does not work for multipart downloads.

**Comment by millems** [comment]
Thanks for your patience on this issue. We're currently focused primarily on 2.x of the SDK, but if enough customers express support for this change being made in 1.11.x we will consider spending some effort to investigate it. 

We use +1s on the original issue to gauge support.

**Comment by debora-ito** [comment]
Closing for staleness and low interest (upvotes or recent comments).
