### ISSUE TITLE
[DynamoDB] Scan with annotated class still retrieves undeclared attributes

### ISSUE THREAD

**Issue by BigChief45** [aws/aws-sdk-java#1814]
I am performing a scan on a DynamoDB table like this:

```java
List<MyItem> items;
AmazonDynamoDB dynamoClient = DynamoDBClientFactory.createClient(getCredentials());
DynamoDBMapperConfig config = DynamoDBMapperConfig.builder()
                    .withTableNameResolver(new DynamicDynamoDBTableNameResolver(dynamoDBTableName))
                    .build();

DynamoDBMapper mapper = new DynamoDBMapper(dynamoClient, config);
items = mapper.scan(MyItem.class, new DynamoDBScanExpression());
```

My `MyItem` class is annotated as follows:

```java
public class MyItem {

  @Override
  @DynamoDBHashKey(attributeName = "id")
  public String getId() {
    return id;
  }

  // More annotated fields to retrieve from DynamoDB
}
```

When doing the scan, it seems that even fields that are **_not declared_** in the `MyItem` class are still fetched from DynamoDB and loaded into memory. I am experiencing memory errors because of this, and I can see in a memory dump that indeed other attributes in the DynamoDB table that I do not want to fetch are still being fetched.

**Comment by debora-ito** [comment]
Hi @BigChief45, from the DynamoDB [documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html):

A Scan operation reads every item in a table or a secondary index. By default, a Scan operation returns all of the data attributes for every item in the table or index. You can use the ProjectionExpression parameter so that Scan only returns some of the attributes, rather than all of them.

In the SDK, you can configure the ProjectionExpression in [DynamoDBScanExpression](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBScanExpression.html). Please also check the ProjectionExpression [documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ProjectionExpressions.html) for more info and examples of use.

**Comment by BigChief45** [comment]
@debora-ito 

Thanks for your reponse. This did the trick.

However I feel it's a bit counter-intuitive when using an annotated class. Maybe it should be added in the doc that all fields are still fetched by default even when using an annotated class? Can't remember seeing it in the DynamoDBMapper docs page.
