### ISSUE TITLE
 AWS.CognitoIdentityServiceProvider doen't have idp( facebook,google etc) signUp/signIn

### ISSUE THREAD

**Issue by yannick-fernand** [aws/aws-sdk-java#1929]
Hi, i am using cognito in backend app java. Is there a way to sign up/ sign in facebook/google/ etc user with his facebook/google access token ? 

We don't want to use the build in UI. The flow we want is: 

1. our ui login with facebook/google and get the access token 
2. send the access token to our backend 
3. we sign in or sign up the user in cognito user pool by giving the access token (you don't propose this) 
4. we do some actions after that (like update data in or data base) and return the cognito access token

**Comment by debora-ito** [comment]
Hi @yannick-fernand, I'm not sure if I understand the question.

In step 1 aren't you authenticating the user with their social sign-ins through the user pool and getting the access tokens? Why do you need to authenticate them again in step 3?

**Comment by yannick-fernand** [comment]
hi,
the step 1 . We have react UI that use our facebook/Google Login to get the access token.
in the step 2 we send the  facebook/Google access token to our backend and we want to use it to sign up and sign in the user pool

**Comment by debora-ito** [comment]
So this is the flow you're asking for:

**Your** app facebook/google credentials -> get an access token A from Cognito user pool -> use access token A to get a new user access token B

?

**Comment by yannick-fernand** [comment]
Not really. My app Facebook/Google get  an access token A from facebook/Google directly not cognito and I want to use the access token A to :
1) add a new user in the user pool using the token A (sign up)
2) get a cognito token B in exchange of the token A (sign in)

**Comment by debora-ito** [comment]
Ok, and this is different from this [Authenticate with a Third Party and Access AWS Services with an Identity Pool ](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-scenarios.html#scenario-identity-pool) scenario because you also want to add and authenticate this user to the Cognito User Pool using only the third-party token, correct?

If that's the case, I don't see anything like this on the Cognito API, and that's why the SDK does not provide it. I will open an internal ticket to confirm it with the service team, and I also suggest to post your issue in the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=173) as you may get a more specialized support from them.

**Comment by debora-ito** [comment]
I'll close this because it's not an issue with the SDK. I will update when we hear back from the Cognito team.
