### ISSUE TITLE
Flow: Injecting POJOWorkflowDefinitionFactoryFactory in WorkflowWorker 

### ISSUE THREAD

**Issue by sukrit007** [aws/aws-sdk-java#194]
We should have a way to inject POJOWorkflowDefinitionFactoryFactory in WorkflowWorker so that, we can provide our own extended implementation for the same.

Refer:
https://github.com/aws/aws-sdk-java/blob/master/src/main/java/com/amazonaws/services/simpleworkflow/flow/WorkflowWorker.java#L30

**Comment by breedloj** [comment]
Hey Sukrit,

I noticed that this issue has been open for a long time with no responses.  Is this still a feature you'd like to see in SWF?

**Comment by sukrit007** [comment]
For using Flow with other languages (node, python), this was an important piece that was missing.  

We had submitted a PR couple of years back :  

https://github.com/aws/aws-sdk-java/pull/189#issuecomment-133238277

**Comment by ctrimble** [comment]
Hello @breedloj, I work with @sukrit007 .  Any word on this?  We have been running a fork for some time and it would be nice to get back on the main SDK.  We really just need a way to get all of the type information out of band, so that other languages do not need to understand Java's type system.

Please let me know if there is anything I can do to help move this forward.

**Comment by manikandanrs** [comment]
This issue was moved to aws/aws-swf-flow-library#1
