### ISSUE TITLE
Dax client with DynamoDBMapperConfig.ConsistentReads.CONSISTENT always reads from DDB table instead of returning from Cache

### ISSUE THREAD

**Issue by Venkat2811** [aws/aws-sdk-java#1983]
Hello Team,

Great work with SDKs !

I would like to know why Dax client with `DynamoDBMapperConfig.ConsistentReads.CONSISTENT` always reads from DDB table instead of returning from Cache ?

My initial understand was that DDB and DAX APIs behave in same way.  So, if `DynamoDBMapperConfig.ConsistentReads.CONSISTENT` is for strongly consistent read on DDB table internal storage replicas, shouldn't it be strongly consistent read among dax cluster nodes in case of DAX?

Would be great if you could explain the reason for this behavior.

Thanks,
Venkat

**Comment by debora-ito** [comment]
Hi @Venkat2811, here's an explanation from the DAX [docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.consistency.html#DAX.consistency.strongly-consistent-reads):

**Strongly Consistent and Transactional Reads**
To perform a strongly consistent GetItem, BatchGetItem, Query, or Scan request, you set the ConsistentRead parameter to true. DAX passes strongly consistent read requests to DynamoDB. When it receives a response from DynamoDB, DAX returns the results to the client, but it does not cache the results. **DAX cannot serve strongly consistent reads by itself, because it is not tightly coupled to DynamoDB. For this reason, any subsequent reads from DAX would have to be eventually consistent reads, and any subsequent strongly consistent reads would have to be passed through to DynamoDB**.

DAX handles TransactGetItems requests the same way it handles strongly consistent reads. DAX passes all TransactGetItems requests to DynamoDB. When it receives a response from DynamoDB, DAX returns the results to the client, but it does not cache the results.

**Comment by Venkat2811** [comment]
Okay, thank you.
