### ISSUE TITLE
why kinesis Record doesn't provide shardId info

### ISSUE THREAD

**Issue by nianglao** [aws/aws-sdk-java#2021]
When I use Apache Spark + Kinesis Integration, I need to know the shardId of each records to keep offset by application. However, in Kinesis SDK, Record class doesn't contain SetShardID/GetShardID. Thus I need to hack codes to use SetPartitionKey/GetPartitionKey to store the shardId info.

My question is why not provide methods to set and get shardId in Record?

Is there any way I can get shardId from partitionKey easily?

**Comment by debora-ito** [comment]
What determines which shard in the stream a Record is assigned to is the `partition key`, it is used to calculate a MD5 hash that will map the record to a shard based on hash key ranges of the shards. That's why you would not see a `setShardID()` method in Record for example.

If you need to control to which shard a record is going, you may use the same `partition key` in records that you want to go to the same shard. Another way to obtain the shardId is through the `PutRecordResult` when using the [PutRecord](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/kinesis/AmazonKinesisClient.html#putRecord-com.amazonaws.services.kinesis.model.PutRecordRequest-) API.

But this is a service specific question and I'm not an expert on Amazon Kinesis, so I'd suggest you reach out to the Kinesis team in the AWS Developer Forums, and give them details of your use case - https://forums.aws.amazon.com/forum.jspa?forumID=169

**Comment by nianglao** [comment]
Thanks for your reply. @debora-ito.
I will post this in AWS Forums.
