### ISSUE TITLE
Upload - recover size

### ISSUE THREAD

**Issue by chsi13** [aws/aws-sdk-java#2049]
Hi.

I got this warning ``` No content length specified for stream data.  Stream contents will be buffered in memory and could result in out of memory errors. ```

And as I don't want my stream  to be load in memory (I want streaming files end to end).

So I go to switch calls to putObject by calls to TransferManager.upload().

But I would like to recover the full size of uploaded attachment. And this info is not  provided by the UploadResult type.

What's the solution ? HEAD request after Upload ??

**Comment by debora-ito** [comment]
Hi @chsi13, TransferManager.upload() still buffers the stream contents in memory when you do not provide a content-length, it does not stream files end to end.

With that said, and since you need the file size anyway, specifying the content-length in the upload request will make the TransferManager upload significantly more efficient.

To answer your original question, yes a head operation (or [AmazonS3Client.getObjectMetadata()](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html#getObjectMetadata-java.lang.String-java.lang.String-)) will return the object size through the content-length header.

**Comment by chsi13** [comment]
Hi @debora-ito. So the only way to stream end to end is by provided the content length ??

And yes actually I use the put object method. Why switch to transfer manager type will be more efficient ?

Thanks for the answer

**Comment by chsi13** [comment]
Hi. Anyone ?

**Comment by debora-ito** [comment]
> So the only way to stream end to end is by provided the content length ??

Yes. Providing the content-length is required by the S3 API, and when it's not provided upfront the SDK will attempt to buffer the stream into memory to get its size.

> Why switch to transfer manager type will be more efficient ?

TransferManager is a high-level library that can parallelize uploads depending on the size of object and the configuration you use. Take a look at the [Multipart Upload page](https://docs.aws.amazon.com/AmazonS3/latest/dev/usingHLmpuJava.html) in S3 documentation or at this [blog post](https://aws.amazon.com/blogs/developer/parallelizing-large-uploads-for-speed-and-reliability/) for an overview of TransferManager functionalities.

Gonna go ahead and close this since there's no issue with the SDK. Please feel free to reach out if you have further questions.
