### ISSUE TITLE
FleetStateCode & FleetActivityStatus string values do no not match values returned by API

### ISSUE THREAD

**Issue by bhedavivek** [aws/aws-sdk-java#2050]
https://github.com/aws/aws-sdk-java/blob/97efc78381273489b0d6bd0dc4744584c066184b/aws-java-sdk-ec2/src/main/java/com/amazonaws/services/ec2/model/FleetStateCode.java#L28

String values defined in `FleetActivityStatus` and `FleetStateCode` have hyphens but values returned by APIs have underscores. 
FleetStateCode:
  - DeletedTerminating
    SDK string value: "deleted-terminating", Actual value returned: "deleted_terminating"

FleetActivityStatus:
  - PendingFulfillment
    SDK string value: "pending-fulfillment", Actual value returned: "pending_fulfillment"

Am I supposed to be using different enums to check Fleet status?

**Comment by debora-ito** [comment]
Hi @bhedavivek, thank you for reporting this. The `FleetStateCode` and `FleetActivityStatus` enums are auto-generated based on internal service model files, so I'll contact the EC2 team and forward them your request, will update here when they respond.

**Comment by bhedavivek** [comment]
any updates on this?

**Comment by debora-ito** [comment]
Hi @bhedavivek the enum values for FleetActivityStatus and FleetStateCode were updated on SDK version `1.11.631`. 

https://github.com/aws/aws-sdk-java/blob/abfbc7cb0e8751a8e1b42396287d415e7e91b8ee/aws-java-sdk-ec2/src/main/java/com/amazonaws/services/ec2/model/FleetStateCode.java#L27-L28

Unfortunately we were not able to keep the same keys because they are generated based on the value.

Closing this, feel free to reopen if you have further questions.
