### ISSUE TITLE
Lexmodelbuilding GetSlotTypeRequest is throwing InvalidSignatureException when version is $LATEST

### ISSUE THREAD

**Issue by nibinki** [aws/aws-sdk-java#2060]
i am facing issue while pulling checksum of the slot which is already exists . if i use $LATEST in the code . if i use any other character say "6"/"7" then it will go through . I am using same credentials in all the case 
GetSlotTypeRequest getSlotTypeRequest = new GetSlotTypeRequest().withName("DocumentType").withVersion("$LATEST")

following is the error. I think this is a bug in SDK . Please help

com.amazonaws.services.lexmodelbuilding.model.AmazonLexModelBuildingException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. (Service: AmazonLexModelBuilding; Status Code: 403; Error Code: InvalidSignatureException; Request ID: 397e8824-adcf-11e9-a475-6f0169c202bd)

**Comment by debora-ito** [comment]
Hi @nibinki, what version of the SDK are you using? And what version of Apache `httpclient` are you using?

This issue is probably caused by using `httpclient-4.5.7` or newer, Apache made breaking changes and it impacted some AWS APIs, you can read more details about it on #1919.

Upgrading to the latest released version of the SDK (`1.11.597` as of today) should fix the issue. You can also use `httpclient-4.5.5` or `httpclient-4.5.6`.

**Comment by nibinki** [comment]
thanks a lot :) . closing issue

**Comment by nibinki** [comment]
Issue fixed after upgrading to latest sdk version and updating httpclient
