### ISSUE TITLE
NullPointer on getProxyPasswordEnvironment

### ISSUE THREAD

**Issue by fraadsbrandth** [aws/aws-sdk-java#2070]
Introduced between 1.11.602 and 1.11.603.
Tested with aws-java-sdk-s3.

If you have Environment variable "HTTP_PROXY" or "HTTPS_PROXY" set without userInfo part of the URI you get a NullPointerException when library is checking if there is a a proxy password as part of the URI.

```
Caused by: java.lang.NullPointerException
	at com.amazonaws.ClientConfiguration.getProxyPasswordEnvironment(ClientConfiguration.java:950)
	at com.amazonaws.ClientConfiguration.getProxyPassword(ClientConfiguration.java:977)
	at com.amazonaws.ClientConfiguration.<init>(ClientConfiguration.java:377)
	at com.amazonaws.client.builder.AwsClientBuilder.resolveClientConfiguration(AwsClientBuilder.java:169)
	at com.amazonaws.client.builder.AwsClientBuilder.access$000(AwsClientBuilder.java:54)
	at com.amazonaws.client.builder.AwsClientBuilder$SyncBuilderParams.<init>(AwsClientBuilder.java:505)
	at com.amazonaws.client.builder.AwsClientBuilder.getSyncClientParams(AwsClientBuilder.java:441)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
```

Previously (1.11.602) this was handled in a catch block when accessing `httpProxy.getUserInfo()` that returned null as proxy password if any exception occurred.
While it now in 1.11.603 results in a NullPointerException since `httpProxy.getUserInfo()`is null.

[Code from 1.11.602](https://github.com/aws/aws-sdk-java/blob/1.11.602/aws-java-sdk-core/src/main/java/com/amazonaws/ClientConfiguration.java#L877)

[Code from 1.11.603](https://github.com/aws/aws-sdk-java/blob/1.11.603/aws-java-sdk-core/src/main/java/com/amazonaws/ClientConfiguration.java#L874)

**Introduced with these changes:**
https://github.com/aws/aws-sdk-java/commit/65cd7e62ed4b304f22dfc06cb383c434df28c26e#diff-f91b7dd5b56ee19883f751e608dc43a8

**Comment by dagnir** [comment]
Thanks for the bug report. We'll get a fix out soon!

**Comment by dagnir** [comment]
Hi, we've added a fix for this upstream and it will be included in the next release.

**Comment by woldieJDI** [comment]
This is a little bug, but should I be concerned?   Why didn't your test suite blow up in 1.11.603 when this bug was introduced?  I wonder what was the worldwide cost of this little bug was.  

_Please_ TDD the API libs if you're not already.

**Comment by fraadsbrandth** [comment]
I referenced a test in the project i experienced the issue so that I don't upgrade to a version with this issue, using [System Rules](https://stefanbirkner.github.io/system-rules/#EnvironmentVariables). So it could be added a test similar to this, quite easy since it crashes on initialization of the client.

**Comment by debora-ito** [comment]
@woldieJDI In a project of the size of the SDK it's hard to cover every use case, but every time we find and fix a bug, we write unit tests to make sure there's no regression later on. 
If you or your customers have been impacted by this, please send us feedback so we can work in improving our process.

@fraadsbrandth the fix was released in version `1.11.610`, can you try it out and check if you still see the issue?

**Comment by fraadsbrandth** [comment]
Yes, update to 1.11.611 today and it works!

**Comment by woldieJDI** [comment]
@debora-ito I don't buy it.  That code was originally written without a test first; and there's no way a change like that could have survived existing test cases.  I'm not running around with my pants on fire over this, and believe me, I have written more than my fair share of untested code so I have been to the place where you are coming from.  BUT ... The stakes are so much higher for this codebase.  Your userbase is massive.  You have a responsibility to write production code with tests first.

**Comment by bmaizels** [comment]
Hi @woldieJDI , thank you for your comments and candidness. I think I can speak for the whole team here when I say that we categorically agree with everything you said, and personally speaking I am a strong TDD advocate and practitioner so it's great to hear another voice support the practice. The stakes are indeed very high and we always reflect in a self-critical way on these kinds of errors and figure out what changes we need to make so that we can do better going forward. We don't like relying on our customers to point out when we miss things, but we are grateful that they do nonetheless.

**Comment by woldieJDI** [comment]
@bmaizels and that's why you all are making the big bucks!

Our team has our own version of the "Quality is Job 1" slogan that captures our commitment to quality and motivate developers to TDD: "Don't screw this up".  Please feel free to steal that for use in the AWS boiler rooms.
