### ISSUE TITLE
com.amazonaws.util.StringUtils dependency Conflict 

### ISSUE THREAD

**Issue by mamup11** [aws/aws-sdk-java#2071]
In my project I use `aws-java-sdk` with version `1.11.602` to interact with aws S3 mostly, and now I need to add a new dependency that has as a dependency `aws-android-sdk-apigateway-core` with version `2.3.0` and then an error happens as so:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call the method com.amazonaws.util.StringUtils.trim(Ljava/lang/String;)Ljava/lang/String; but it does not exist. Its class, com.amazonaws.util.StringUtils, is available from the following locations:

    jar:file:/Users/mateo/.m2/repository/com/amazonaws/aws-android-sdk-core/2.3.0/aws-android-sdk-core-2.3.0.jar!/com/amazonaws/util/StringUtils.class
    jar:file:/Users/mateo/.m2/repository/com/amazonaws/aws-java-sdk-core/1.11.602/aws-java-sdk-core-1.11.602.jar!/com/amazonaws/util/StringUtils.class

It was loaded from the following location:

    file:/Users/mateo/.m2/repository/com/amazonaws/aws-android-sdk-core/2.3.0/aws-android-sdk-core-2.3.0.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of com.amazonaws.util.StringUtils

```

I went ahead and remove that new dependency and try to import manually `aws-android-sdk-apigateway-core` with version `2.14.1` thinking that the issue may be the version of this dependency but the error still happends.

Any Idea how to solve it?

**Comment by debora-ito** [comment]
@mamup11 it looks like you're having a conflict of StringUtils classes that have exactly the same package name, one in [aws-java-sdk-core](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/StringUtils.java) and one in [aws-android-sdk-core](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-core/src/main/java/com/amazonaws/util/StringUtils.java). Your application was looking for the _trim()_ method that's present in aws-java-sdk-core, but did not find it since it loaded the class from aws-android-sdk-core.

Check your application classpath dependency order, maybe making it load the aws-java-sdk-core StringUtils class will solve the issue.

**Comment by mamup11** [comment]
Hard for my to believe but that was exactly de solution, I just changed the order on my pom and everything works like a charm, thanks
