### ISSUE TITLE
Add default constructors to metadata classes

### ISSUE THREAD

**Issue by Sarkos** [aws/aws-sdk-java#2072]
I am currently working with Textract and wanted to serialize and deserialize the GetDocumentTextDetectionResult using JSON ObjectMapper. However, it includes classes such as SdkHttpMetadata and ResponseMetadata which do not have default constructors, so I am unable to deserialize them.

**Comment by debora-ito** [comment]
We are closing stale v1 issues before going into [Maintenance Mode](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/), so I'll go ahead and close this feature request. If this issue is still relevant in v2 please open a [new issue](https://github.com/aws/aws-sdk-java-v2/issues/new/choose) in the v2 repo.

#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)
