### ISSUE TITLE
CloudFormation - No fail on empty changesets option when updating/creating stack

### ISSUE THREAD

**Issue by youngpayters** [aws/aws-sdk-java#2099]
There is the following deploy command for cloudformation has the following option: --no-fail-on-empty-changeset

https://docs.aws.amazon.com/cli/latest/reference/cloudformation/deploy/index.html#options

There is no such command on the API for this.

**Comment by debora-ito** [comment]
@youngpayters, actually there is no `deploy` API available for the SDKs, the `deploy` operation and its --no-fail-on-empty-changeset option are exclusive to the AWS CLI.

Can you elaborate on which operation would you like to see this option?

**Comment by youngpayters** [comment]
Hi @debora-ito, the request(s) that I was mainly looking for were the requests to create and update cloudformation stacks.

I would expect to have some options on the following classes to allow for failures where the stack has not changed and not throw exceptions:
[CreateStackRequest](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-cloudformation/src/main/java/com/amazonaws/services/cloudformation/model/CreateStackRequest.java)

[UpdateStackRequest](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-cloudformation/src/main/java/com/amazonaws/services/cloudformation/model/UpdateStackRequest.java)

**Comment by youngpayters** [comment]
This is the exception I do get if there are no changes made:
```
com.amazonaws.services.cloudformation.model.AmazonCloudFormationException: No updates are to be performed. 
```

And I don't really want to parse the error message in order to know what has occurred. So I think the potential changes here is either have a specific exception that I can handle or allow failures in this instance.

**Comment by debora-ito** [comment]
I'm not sure if the option applies to CreateStackRequest because the stack is being created for the first time, maybe you meant CreateChangeSetRequest?

In any way, the SDK will only support this feature if the change comes from the service API, so I'll reach out to the Cloudformation team asking for the feature. 

In addition, I recommend you post your request on the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=92) so you can reach out to the Cloudformation team directly.
