### ISSUE TITLE
DynamoDBMapper.generateCreateTableRequest() - Forcing ProjectionType.KEYS_ONLY for all LSI

### ISSUE THREAD

**Issue by adaofeliz** [aws/aws-sdk-java#214]
Hi,

it seems that it's not possible by using the DynamoDBMapper to create a table with a LSI that protects all the Attributes.

This feature is importante for iteration of the table using the DynamoDBMapper.query(). 

Why can't this be configurable in the DynamoDBIndexRangeKey Annotation?

I'm more than happy do the change and create a merge request, if you agree to accept it.

Thanks,

Adao

**Comment by pauloubuntu** [comment]
I know I might be a little late for the party but I must express how sad it's to not have it implemented by now =/

**Comment by jbuddha** [comment]
This will be a good feature.

**Comment by dbubenheim** [comment]
Is there any chance that this feature will be implemented soon, either on table or attribute level? Thanks in advance!

**Comment by debora-ito** [comment]
@adaofeliz @PauloMigAlmeida @jbuddha @dbubenheim

the SDK team has reviewed the feature request list for V1, and since they're concentrating efforts on V2 new features they decided to not implement this one in V1. It still being considered for the DynamoDB Mapper refactor in V2, see the referenced issue above. I'll go ahead and close this one.

Please feel free to comment on the V2 issue with your use case, and reach out if you have further questions.
