### ISSUE TITLE
ConversionSchemas should also consider annotation DynamoDBTypeConverted besides the now deprecated DynamoDBMarshalling

### ISSUE THREAD

**Issue by tungpham** [aws/aws-sdk-java#2144]
If `@DynamoDBMarshalling` is marked as deprecated, then you should also take the recommended  `@DynamoDBTypeConverted` into account as well. Currently, there's no way to add `@DynamoDBTypeConvertedJson` to the unmarshallerSet

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/ConversionSchemas.java#L1301

**Comment by debora-ito** [comment]
We don't have plans to make this change in v1. 

We are closing stale v1 issues before going into [Maintenance Mode](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/), so if this issue is still relevant in v2 please open a [new issue](https://github.com/aws/aws-sdk-java-v2/issues/new/choose) in the v2 repo.

#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)
