### ISSUE TITLE
Role.getTags() returning empty list

### ISSUE THREAD

**Issue by anilcs81** [aws/aws-sdk-java#2167]
I am trying to get the tags associated with an IAM Role and the getTags() method on Role object returned by listRoles() is returning empty list. The same issue exists for IamUser as well.

**Comment by debora-ito** [comment]
Hi @anilcs81, 

calling the listRoles() API with wire logging turned on I noticed that the response does not contain the Tags info in the Role structure. That's why getTags() is returning an empty list.

This is a service side issue, so I'll contact the IAM team. We suggest you also try to reach out to the team directly by raising this in the [AWS Developer Forum](https://forums.aws.amazon.com/forum.jspa?forumID=76) or contacting the AWS Customer Support.

**Comment by anilcs81** [comment]
Any fix in pipeline for this?

**Comment by debora-ito** [comment]
No word from the IAM team yet.

**Comment by debora-ito** [comment]
Just tested this, and the tags are now present in `GetRole()` response.
