### ISSUE TITLE
Describe Beanstalk Environments doesn't throw an exception if you don't have IAM permissions

### ISSUE THREAD

**Issue by msiebert** [aws/aws-sdk-java#2202]
When I make a call through the Beanstalk Client to describe environments, the API returns an empty list if I explicitly deny IAM permissions for Beanstalk. It should throw an exception so we can detect the difference between not having any environments vs not having permissions.

Note: looks like using `aws elasticbeanstalk describe-environments` exhibits the same behavior.

**Comment by debora-ito** [comment]
@msiebert can you tell more about how you denied IAM permissions for Beanstalk, so I can try to reproduce?

**Comment by msiebert** [comment]
Yeah, so I just did an explicit deny through IAM. The statement looked like this:

```
       {
            "Sid": "VisualEditor1",
            "Effect": "Deny",
            "Action": "elasticbeanstalk:*",
            "Resource": "*"
        }
```

**Comment by debora-ito** [comment]
Got it, thank you for reporting this. I'll open an issue with the service team behind the ElasticBeanstalk API and will let you know when they respond.

**Comment by debora-ito** [comment]
@msiebert the ElasticBeanstalk team replied, they are aware of the problem and will work in returning an AccessDenied error instead of an empty list.

So I'll go ahead and close this. Once they make the change in their API you'll start to see it in the SDK. Feel free to reach out if you have further questions.
