### ISSUE TITLE
Client builder seems to always load com.amazonaws.auth.DefaultAWSCredentialsProviderChain which is expensive

### ISSUE THREAD

**Issue by ocind** [aws/aws-sdk-java#2211]
For AmazonDynamoDBClientBuilder the recommended way to initialize the client is
`AmazonDynamoDBClientBuilder.standard().withCredentials(...).build()`

As I read in various other issues (such as https://github.com/aws/aws-sdk-java/issues/1774), DefaultAWSCredentialsProviderChain is expensive to create and should be avoided. However, there is no way not to load DefaultAWSCredentialsProviderChain while using the AmazonDynamoDBClientBuilder.

There was `AmazonDynamoDBClient(AWSCredentialsProvider awsCredentialsProvider)` however it has already been deprecated. https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/AmazonDynamoDBClient.java#L283

Is there a way to initialize AmazonDynamoDBClient without loading DefaultAWSCredentialsProviderChain to minimize cold start time?

I noticed that the SDK team does not consider new improvements for V1 anymore and focusing on V2 SDK development instead. We really wanted to move to v2 sdk however the lack of DynamoDb high level client in v2 really hinders us from doing so. It has been 2 years since V2 SDK is considered GA without a high level client. Hopefully it could be completed soon!

**Comment by debora-ito** [comment]
Hi @ocind, the DefaultAWSCredentialsProviderChain is more expensive because it will search for credentials in the whole [credential provider chain](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html). To avoid this search you can explicitly provide the credentials to the client builder using `.withCredentials()`. The linked docs have examples of how to specify a credential provider, or even specify the access_key_id and secret_access_key directly.

Regarding the DynamoDB high level library for V2, the team is actively working on it. There are several PRs being worked on (look for the ones that mention DynamoDB enhanced preview), you can track the development status (https://github.com/aws/aws-sdk-java-v2/issues/35) and you can read an overview of the refactored library here: https://github.com/aws/aws-sdk-java-v2/blob/master/services-custom/dynamodb-enhanced/README.md 

Participation is welcome, we'll be glad to hear your feedback on any stage of its development.

**Comment by ocind** [comment]
hi @debora-ito thank you for the response! 

I was wondering when `AmazonDynamoDBClientBuilder.standard()` is called, has it already load the  DefaultAWSCredentialsProviderChain when .standard() is called?

When AmazonDynamoDBClientBuilder.standard().build() is used, do you know whether DefaultAWSCredentialsProviderChain is loaded when .standard() is called or when .build() is called? I was having a hard time to debug if this is really the case. 

I was suspecting that .standard() basically loads all the default parameters first (which includes DefaultAWSCredentialsProviderChain) and so anyway DefaultAWSCredentialsProviderChain has already been loaded when .standard() is called and we cannot fully avoid initializing DefaultAWSCredentialsProviderChain when building the client using `AmazonDynamoDBClientBuilder`

I noticed that in AmazonS3ClientBuilder this is the case as can be seen on https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3ClientBuilder.java#L46

The .standard() method actually still loads DefaultAWSCredentialsProviderChain anyway by initializing `S3CredentialsProviderChain`. So the best thing that I can do actually is not to use any kind of `.withCredentials()` method while using the builder since anyway the builder already loads `DefaultAWSCredentialsProviderChain` at first.

I saw some github issues' response such as https://github.com/aws/aws-sdk-java/issues/1774#issuecomment-426431217 in which it seems to be recommended to specify a credentials providers to improve cold start performance. As mentioned above, I think this is actually not the case (at least for `AmazonS3ClientBuilder`) and such recommendation (using `.withCredentials()`) actually will make cold start even worse since now extra works needs to be done to again load some credentials. I think such recommendation needs some clarification.

Can you help me to clarify if it is the case?

>There are several PRs being worked on (look for the ones that mention DynamoDB enhanced preview).
Yes, I have been following the development closely as well :)

**Comment by ocind** [comment]
Ah apparently this is very similar to this issue reported in V2: https://github.com/aws/aws-sdk-java-v2/issues/749 for which [this commit](https://github.com/aws/aws-sdk-java-v2/commit/1fafd9e87a0dd913f276705feddffcff719927a1) is fixing

**Comment by ocind** [comment]
hi @debora-ito I noticed that this issue does not happen with `AmazonDynamoDBClientBuilder` but only with `AmazonS3ClientBuilder` as seen [here](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3ClientBuilder.java#L46)

Do you have any suggestion on how to load `AmazonS3Client` without loading `S3CredentialsProviderChain()`? :pray:

**Comment by debora-ito** [comment]
@ocind I'm sorry for the long silence, this issue slipped through the cracks. A lot has changed since 2020! We talked about DynamoDB Enhanced client and it is now generally available.

Unfortunately we don't have plans to change the `AmazonS3Client` code in v1 as the team is focused in working in v2 features. We know that migrating to SDK v2 is not an easy task, but SDK v2 has some features that will help improve startup time when using Lambda, like the option to use a lighter HTTP Client like UrlConnection. More info: https://aws.amazon.com/blogs/developer/tuning-the-aws-java-sdk-2-x-to-reduce-startup-time/

I'll go ahead and mark to this auto-close soon. Let me know if you have any more questions.
