### ISSUE TITLE
Use of AWSCredentialsProvider by aws-java-sdk-s3 

### ISSUE THREAD

**Issue by parth2094** [aws/aws-sdk-java#2233]
Hi,

We want our EMR cluster to assume role based on the S3 bucket that it is accessing. We are using an approach of writing a custom credential provider as stated in [this](https://aws.amazon.com/blogs/big-data/securely-analyze-data-from-another-aws-account-with-emrfs/) article. The credential provider returned by EMRFS to s3 client implements the class [AWSCredentialsProvider](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html?com/amazonaws/auth/AWSCredentialsProvider.html).
As can be seen from its javadoc, it must implement two methods getCredentials() and refresh().

EMRFS returns this provider to an s3 client which is used for further read/writes.

Since our scale is huge (700+ node cluster), we want to estimate the number of calls to STS in this case.
Wanted to understand the call patterns between the s3 client and the getCredentials() and refresh() method?
When does the client call getCredentials() and when does it call refresh()?
We have put a logic in our getCredentials() implementation to make a call to STS only if credential is null or about to expire, but doesn't the client have this logic to decide when to call getCredentials and when to call refresh() ?

**Comment by kmbotts** [comment]
It appears that each API call will attempt to invoke the AWSCredentialsProvider.getCredentials() method twice.
1) runBeforeRequestHandlers() - is intended to be used in conjunction with RequestHandler2 callbacks. the Credentials from this call are cached into the request handler context
```request.addHandlerContext(HandlerContextKey.AWS_CREDENTIALS, credentials);``` You could implement the beforeRequest method of the RequestHandler2 call back to retrieve your credentials from the context map and refresh them if necessary.

2) executeOneRequest() - This is called just before signing of the request. so what it gets is what it's going to use.

We had to do something similar for some refreshable credentials for programmatic cognito login sessions talking to various resources around the clock. Eventually the session token would expire and needed to be refreshed with new STS credentials prior to making a new call.

We implemented our refresh logic in the beforeRequest callback method mentioned above. But instead of putting the refresh logic in the getCredentials() method of the AWSCredentialsProvider, we stored all the refresh logic in an implementation of AWSRefreshableSessionCredentials (which extends AWSCredentials) itself. The reason for this, is the beforeRequest method doesn't have access to the provider, only the cached AWSCredentials supplied in the context prior to being called.

So from the beforeRequest method, we can call the refreshCredentials() method. The expiration date is a member variable of the AWSRefreshableSessionCredentials instance and refreshes itself if expired. One added wrinkle we added to the refresh logic is to put ReadWriteLock around the refresh and the reading of any member variables. so if the session is being updated, any reads will be blocked until the session was updated. read locks didn't block, but write locks blocked reads (and other writes). This is a must if you plan on sharing the credentials instance as a singleton where more than one client/thread could potentially update the credentials at the same time.

I would consider you change to a similar pattern. The AWSCredentialsProvider.getCredentials() method should return the AWSCredentials object you have. In my case the AWSRefreshableSessionCredentials which has a method to refreshCredentials().
The AWSCredentialsProvider.refresh() is to refresh the provider, not the creds, nor should getCredentials() be refreshing credentials. Not to say it doesn't work, but I prefer the separation of concerns and each interface controls its piece instead of coupling the logic into one area, i.e. getting the Credentials and refreshing them. 

As for the number of times these methods are called. I'm not seeing explicit calls to the refresh() method, looks like that is just how you implement the provider and call refresh based on some internal logic you have. The getCredentials() method is called at minimum twice per API call. however, since your logic has it baked in to only call STS if null or expired, many of those will be no-op calls and just return your AWSCredentials object as is.

**Comment by debora-ito** [comment]
Thank you for the detailed report @kmbotts.

@parth2094 your questions are very specific to EMR and its resource management, and I don't know enough about EMR to answer them. For service specific questions we recommend creating a thread in the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=52) where you can get support directly from the service team.

I'll go ahead and close this. Feel free to reach out if you have any further questions.
