### ISSUE TITLE
Missing links in aws-sdk-java/CONTRIBUTING.md

### ISSUE THREAD

**Issue by h-hub** [aws/aws-sdk-java#2259]
working-on-the-sdk link and git-rewriting-history link is missing from the file.

1. - working-on-the-sdk can be linkes to this link-> https://github.com/aws/aws-sdk-java-v2/blob/master/docs/GettingStarted.md
2. - git-rewriting-history can be linkes to this link->https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

As someone who is new to Open source, I'm hoping to submit pull requests to add these links. Correct if I have input incorrect information or if this issue is irrelevant.

Thanks.

**Comment by debora-ito** [comment]
Hi @h-hub thank you for reaching out, this is not irrelevant.

The second link is correct but the first one is not, it points to the SDK version 2.x Getting Started page.

I found other links that are not working in the CONTRIBUTING page. This will have to be fixed in our internal release though, but we hope you can contribute in another issue, look for the ones with a `help wanted` label.

**Comment by h-hub** [comment]
Happy to help @debora-ito.

I'll check those issues. Thanks.

**Comment by debora-ito** [comment]
The CONTRIBUTING page was updated in the latest release `1.11.767`. Thank you again.
