### ISSUE TITLE
Request to add support for STSAssumeRoleSessionCredentialsProvider.builder() in DefaultAWSCredentialsProviderChain.java

### ISSUE THREAD

**Issue by jalmeidaa** [aws/aws-sdk-java#2368]
I am working on apache beam pipeline to write to s3 using STSAssumeRoleSessionCredentialsProvider.builder() provider but it seems to be not support in DefaultAWSCredentialsProviderChain.java.

## Describe the Feature
Need to be able use credentials generated by STSAssumeRoleSessionCredentialsProvider.builder() by passing to DefaultAWSCredentialsProviderChain.java

## Is your Feature Request related to a problem?
Currently I cannot write to s3 using assume role. The feature helps to perform multiple account writes. See additional context

## Proposed Solution
Add STSAssumeRoleSessionCredentialsProvider.builder() provider to DefaultAWSCredentialsProviderChain.java

## Describe alternatives you've considered
N/A

## Additional Context
I am running my beam pipeline on Account A & want to write files to account B using assumeRole so multiple accounts can access files in account B. But when I assume role and pass this to pipeline, it fails to recognize.
Refer : [StackOverflow Question](https://stackoverflow.com/questions/62439623/i-am-trying-to-write-to-s3-using-assumerole-via-fileio-with-parquetio).
Also [feature request stackoverflow](https://stackoverflow.com/questions/62582139/request-to-add-support-for-stsassumerolesessioncredentialsprovider-builder-in)

## Your Environment

* AWS Java SDK version used: 1.11.718
* JDK version used: 1.8.0_211
* Apache Beam : 2.22.0
* Operating System and version:

**Comment by debora-ito** [comment]
@jalmeidaa I'm not fully clear on what you are requesting. If S3 is not recognizing an assumed role credential specified in a Beam pipeline, I don't see how adding STSAssumeRoleSessionCredentialsProvider to the default credential provider chain will help.

Also, I'm not familiar with Beam but since you're using a session credential you probably have to provide a BasicSessionCredentials (which has a session token) instead of BasicAWSCredentials for the request to be valid.
