### ISSUE TITLE
DynamoDbMapper modifies empty string ("") to null while empty string has been officially supported by DynamoDb

### ISSUE THREAD

**Issue by ocind** [aws/aws-sdk-java#2371]
## Describe the bug
As per this recent [news](https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-dynamodb-now-supports-empty-values-for-non-key-string-and-binary-attributes-in-dynamodb-tables/#:~:text=May%2018%2C%202020-,Amazon%20DynamoDB%20now%20supports%20empty%20values%20for%20non%2Dkey%20String,before%20sending%20them%20to%20DynamoDB.) DynamoDb now supports saving empty string in attribute values.

However, empty string is actually converted to NULL by DynamoDBMapper as can be seen [here](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/StandardModelFactories.java#L262)

## Expected Behavior
Passing empty string field in an entity to DynamoDbMapper.save method should correctly update the corresponding field to empty string

## Current Behavior
Passing empty string field to an entity to DynamoDbMapper.save method basically converts the field to null. Since we are using SaveBehavior.UPDATE_SKIP_NULL_ATTRIBUTES, this resulted in the field to be "ignored" instead of being set to ""

## Steps to Reproduce
```
  public static void main(String[] args) {
    DynamoDBMapper dynamoDBMapper = new DynamoDBMapper(); //init with SaveBehavior.UPDATE_SKIP_NULL_ATTRIBUTES
    Item item= Item.builder()
        .primaryKey("dc7de992-3286-465f-98df-70bc519fc90b")
        .description("").build();
    acCloudDynamoDBMapperClient.save(item);
  }
```
Description is not updated into ""

## Possible Solution
Remove the empty string check  [here](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/StandardModelFactories.java#L262)

## Context
We have a CRUD webapp and we wanted to be able to "remove" (setting it to empty string) a field while editing the item 

## Your Environment

* AWS Java SDK version used: 1.11.772
* JDK version used: 8.0.242-amzn
* Operating System and version: Ubuntu 20.04

**Comment by debora-ito** [comment]
Hi @ocind, thank you for reaching out. We haven't made this change in v1 because it's a breaking change, it would break customers who are relying on this behavior in their projects. To add support for empty strings, a separate field to DynamoDBMapper APIs would have to be added or make it a configurable feature, and it would be a change too big to be considered in v1 as the team efforts are focused in new features for Java SDK v2.

Empty strings are already supported in Java SDK v2 [DynamoDBEnhanced](https://aws.amazon.com/blogs/developer/introducing-enhanced-dynamodb-client-in-the-aws-sdk-for-java-v2/) Client, so I'd like to suggest you to give it a try and send us feedback.

**Comment by imjuoy** [comment]
Is this the only suggested solution?

**Comment by robin-xyzt-ai** [comment]
Bumped into the same problem. And since I didn't fancy switching to the Java SDK v2, I opted for a workaround: replace the current type convertor for one that replaces empty strings with a fixed value when storing items, and replaces that fixed value with the empty string again when deserializing:

```java
package ai.xyzt.spring.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverter;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverterFactory;

public class EmptyStringTypeConverterFactory extends DynamoDBTypeConverterFactory {

  private final DynamoDBTypeConverterFactory delegate = DynamoDBTypeConverterFactory.standard();

  @Override
  public <S, T> DynamoDBTypeConverter<S, T> getConverter(Class<S> sourceType, Class<T> targetType) {
    DynamoDBTypeConverter<S, T> delegateConverter = delegate.getConverter(sourceType, targetType);
    if (sourceType.equals(String.class)) {
      return (DynamoDBTypeConverter<S, T>) new EmptyStringDynamoDBTypeConverter<T>((DynamoDBTypeConverter<String,T>)delegateConverter);
    }
    return delegateConverter;
  }

  private static final class EmptyStringDynamoDBTypeConverter<T>
      implements DynamoDBTypeConverter<String, T> {

    private static final String DUMMY_VALUE_FOR_EMPTY_STRINGS =
        "completely_random_value_that_should_not_appear_in_the_application_to_represent_an_empty_string_in_the_db";

    private final DynamoDBTypeConverter<String, T> delegate;

    private EmptyStringDynamoDBTypeConverter(
        DynamoDBTypeConverter<String, T> delegate) {
      this.delegate = delegate;
    }

    @Override
    public String convert(T object) {
      String convert = delegate.convert(object);
      if (convert.equals("")) {
        return DUMMY_VALUE_FOR_EMPTY_STRINGS;
      }
      return convert;
    }

    @Override
    public T unconvert(String object) {
      if (object.equals(DUMMY_VALUE_FOR_EMPTY_STRINGS)) {
        return delegate.unconvert("");
      }
      return delegate.unconvert(object);
    }
  }
}
```
and then creating the `DynamoDBMapperConfig`:

```
 return DynamoDBMapperConfig.builder()
        .withTypeConverterFactory(new EmptyStringTypeConverterFactory())
        .build();
```

This was easy to achieve in my code base as I was already using a utility method to initialize the `DynamoDBMappConfig.builder()` with some default values.

The other alternative I could think of was annotating all my String attributes with a custom type convertor, but that sounded like an awful lot of work and easy to forget when adding new String attributes.
