### ISSUE TITLE
Download pgp Encrypted File to local folder from s3 bucket

### ISSUE THREAD

**Issue by upen4a3** [aws/aws-sdk-java#2387]
I am trying to download files from s3 bucket ,but getting
`
com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: ******), S3 Extended Request ID: -*****`

```
                              
                              final S3Object s3Object = s3Service.getObject("mybucketName", "mycncryptedFilePath");
                               String filePath="/Users/Desktop/s3"
				File localFile = new File("filePath");
				ObjectMetadata object = s3Client.getObjectUsingFile(mybucketName, mycncryptedFilePath, localFile);

```

The problem here is, I am getting the file using s3Object.getObject(),but the file I am downloading is encrypted using .pgp encryption technique.Is there a way we can download the encrypted file from s3 bucket without reading the content first.

**Comment by debora-ito** [comment]
@upendar4a3 It will depend on what scheme/library was used to encrypt it, by your description it's not exactly clear how the object was encrypted in the first place. If it was encrypted using the [AmazonS3EncryptionClient](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3EncryptionClientBuilder.html) for example, you can also use it to download and decrypt it. If it was encrypted using a third-party tool or library, it must be decrypted the same way it was encrypted.

On a side note, an AccessDenied error can be caused by a credential used in the s3 client not having access permission to the object.
