### ISSUE TITLE
How to copy S3 file/object across different AWS account?

### ISSUE THREAD

**Issue by harisingh-highq** [aws/aws-sdk-java#2431]
I found below method to copy file from 1 bucket to another bucket in S3 SDK java:-
`AmazonS3 cloudianClient = CloudianS3Helper.getCloudianClient(dbAccessKey, dbSecretKey, dbEndpoint); 
CopyObjectResult result = cloudianClient.copyObject(bucketName, sourcePath, bucketName, destinationPath);
`

I want to copy file/object from 1 bucket of an AWS account to other bucket of different AWS account (Copy files across AWS accounts), then which method is supported this? 

Can anyone help me into this?

**Comment by ganeshbhargav** [comment]
The base requirement of copying files is straight-forward:

- Create an event on the source S3 bucket that triggers a Lambda function
- The Lambda function copies the object to the other bucket

The complicating factor is the need for cross-account copying.

Two scenarios are possible:

Option 1 ("Pull"): Bucket in Account-A triggers Lambda in Account-B. This can be done with [Resource-Based Policies for AWS Lambda (Lambda Function Policies) - AWS Lambda](https://docs.aws.amazon.com/lambda/latest/dg/access-control-resource-based.html). You'll need to configure the trigger via the command-line, not the management console. Then, a Bucket policy on the bucket in Account-A needs to allow GetObject access by the IAM Role used by the Lambda function in Account-B.

Option 2 ("Push"): Bucket in Account-A triggers Lambda in Account-A (same account). The Bucket policy on the bucket in Account-B needs to allow PutObject access by the IAM Role used by the Lambda function in Account-A. Make sure it saves the object with an ACL of bucket-owner-full-control so that Account-B 'owns' the copied object.

**Comment by harisingh-highq** [comment]
@ganeshbhargav 
Thank you for your reply.

I would like to inform you that this solution is feasible from AWS interface only. 
It seems to be not feasible with aws-sdk-java library.

I need api/method implementation which supports this so I can use it in our java application.

**Comment by debora-ito** [comment]
@harisingh-highq see https://github.com/aws/aws-sdk-java/issues/1676 for an example showing how to do this.

More resources: 
- https://docs.aws.amazon.com/AmazonS3/latest/dev/example-walkthroughs-managing-access.html
- https://aws.amazon.com/premiumsupport/knowledge-center/copy-s3-objects-account/

The S3 Developer Guide is a good starting point for questions like this, it has a ton of examples and guides for common cases. Also search for previous similar issues here in the repository, one may show a solution for your question.

**Comment by harisingh-highq** [comment]
@debora-ito Thanks for your reply, appreciate your help.
