### ISSUE TITLE
AmazonEC2Exception 302 Authentication Required in AWS JAVA SDK Method.

### ISSUE THREAD

**Issue by isuchathuranga** [aws/aws-sdk-java#2432]
Hi,

I am getting following error when I am calling JAVA SDK method in some servers only. 

com.amazonaws.services.ec2.model.AmazonEC2Exception: null (Service: AmazonEC2; Status Code: 302; Error Code: 302 authenticationrequired; Request ID: null)
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1799)

This issue is only occurred in some servers.
Any idea on this ?

**Comment by ganeshbhargav** [comment]
A 302 Found message is an HTTP response status code indicating that the requested resource has been temporarily moved to a different URI.  302 Found code generally indicates an issue on the actual web server hosting your application.

The appearance of a 302 Found is usually not something that requires much user intervention. All modern browsers will automatically detect the 302 Found response code and process the temporarily redirection action automatically. The web server hosting the application will typically include a special Location header as part of the response it sends to the client. This Location header indicates the new URL where the requested resource can be found.

For example, if a request comes in to access the URL http://wordpress.com, but the web server is configured to force redirection to a secure version using https, the server response will include the Location: https://wordpress.com header. This tells the browser that it should redirect this single request to http://wordpress.com to the secured URL of https://wordpress.com. In most cases, the browser will automatically detect this 302 Found response code, read the new Location URL, and redirect the request to that new location.


Since the 302 Found indicates that something has gone wrong within the server of your application, we can largely disregard the client side of things. If you’re trying to diagnose an issue with your own application, you can immediately ignore most client-side code and components.

However, it’s entirely possible that the server is misconfigured, causing it to improperly respond with 302 Found codes, instead of the standard and expected 200 OK code of a normal, functional request. Thus, a large part of diagnosing the issue will be going through the process of double-checking what resources/URLs are generating 302 Found response codes and determining if these codes are appropriate or not.


We can solve the problem by troubleshooting on the server side.
Below  is the solution is your application is running on an Apache Server.
	1) Look for a .htaccess file within the root directory of your website file system.
	2) open .htaccess file in a text editor and look for lines that use RewriteXXX directives, which are part of the mod_rewrite module in Apache.
	3) For example, here is a simple RewriteCond and RewriteRule combination that matches all incoming requests to example.com and establishes a temporarily redirection to that same URI on the temporary-example.com domain instead:
		RewriteEngine on
		RewriteCond %{HTTP_HOST} ^example\.com$
		RewriteRule ^(.*)$ http://www.temporary-example.com/$1 [R=302]
	Notice the extra flag at the end of the RewriteRule, which explicitly states that the response code should be 302, indicating to user agents (browsers) that this is a temporary redirect. Thus, if you find any strange RewriteCond or RewriteRule directives in the .htaccess file that don’t seem to belong, try temporarily commenting them out (using the # character prefix) and restarting your web server to see if this resolves the issue.
Below  is the solution is your application is running on an nginx Server.
	1) Look for an .nginx.conf file within the root directory of your website file system.
	2) Once located, open nginx.conf in a text editor and look for rewrite directives that are using the redirect flag.
	3)  For example, here is a simple block directive (i.e. a named set of directives) that configures a virtual server by creating a temporary redirection from example.com to the temporary-example.com:

		server {
		    listen 80;
		    listen 443 ssl;
		    server_name www.example.com;
		    rewrite ^/$ http://www.temporary-example.com redirect;
		}
	4) Look through your nginx.conf file for any abnormal rewrite directives that include the redirect flag (the alternative permanent flag will issue 301 response codes instead). Comment out any abnormalities before restarting the server to see if the issue was resolved.

Hope this can resolve the issue.

**Comment by debora-ito** [comment]
@ganeshbhargav that's a great explanation on 302 error code. Unfortunately I don't think it helps much in @isuchathuranga case, the action items are mostly on the service side.

@isuchathuranga to be able to help you I will need more context about the error you're seeing. Can you provide a sample code I can use to reproduce and the full stacktrace with the error?
