### ISSUE TITLE
Does aws-java-sdk jars on maven central broken?

### ISSUE THREAD

**Issue by ozhelezniak-talend** [aws/aws-sdk-java#2443]
Hello!

I think something went wrong with uploading the dependencies on maven central.
The same version that we can download from your site (from here) is bigger than the one that is existed on maven central.

For example the release:
https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk/1.11.889
The jar doesn't contain classes. It's not declared with packaging "pom".

**Comment by debora-ito** [comment]
Hello @ozhelezniak-talend! I'm not sure what's the issue you're having but in here the GitHub project contains the java source files while the jars in maven central contain the `.class` files, they will not have the same size.

How are you consuming the SDK modules?

**Comment by ozhelezniak-talend** [comment]
Hello @debora-ito. Thank you for the feedback!
The problem is that jars on maven central don't contain any .class files.
https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk/1.11.889/aws-java-sdk-1.11.889.jar

**Comment by debora-ito** [comment]
That's expected, `aws-java-sdk-1.11.889.jar` is basically just a pom.xml with all the SDK modules as dependencies. Note that you usually don't need to download the jars from maven central, check the Getting Started docs for more details about the different ways to use the SDK: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-install.html

**Comment by rpatrick00** [comment]
@debora-ito I can understand the confusion.  The jar itself is completely useless (no classes or manifest Class-Path).  If you were to change the packaging type to POM (so that the jar isn't generated), that would be less confusing for developers familiar with Maven.  That way, developers can just do this:

```xml
<dependencies>
    <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-java-sdk</artifactId>
        <version>1.11.889</version>
        <type>pom</type>
    </dependency>
</dependencies>
```

The only purpose that the jar is currently serving is to eliminate the need to add the `<type>pom</type>` element of the dependency (since jar is the default packaging type).

@ozhelezniak-talend Personally, I would strongly recommend against creating a dependency on the entire AWS Java SDK.  What I recommend is that you import the aws-java-sdk-bom (to make sure that you get a consistent set of versions of the component jars) and then add dependencies on only the features you are using.  For example, in a project I am currently doing with S3, my pom.xml has snippets that look like this:

```xml
    <dependencyManagement>
        <dependencies>
            <!-- Have to use the older AWS SDK version because SnapLogic pulls it in and the versions
                 of netty appear to be incompatible. -->
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-bom</artifactId>
                <version>1.11.688</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-sts</artifactId>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-s3</artifactId>
        </dependency>
    </dependencies>
```

**Comment by ozhelezniak-talend** [comment]
@debora-ito and @rpatrick00 
Thank you for your answers!
Yes, @rpatrick00 you are right the situation that the "aws-java-sdk" is packed as "jar" is confusing.

**Comment by debora-ito** [comment]
@rpatrick00 thank you for clarifying the confusion and explaining in a better way than I did.

@ozhelezniak-talend let us know if you have any other question.

**Comment by ozhelezniak-talend** [comment]
@debora-ito 
Do you plan to change the packaging type from "jar" to "pom"?
It's the last question, thank you.

**Comment by debora-ito** [comment]
There's no plans to change that. Note that importing the aws-java-sdk-bom and adding only the SDK modules you're going to use like @rpatrick00 described is the recommended way to include the SDK in your project.
