### ISSUE TITLE
AmazonS3EncryptionClientV2 can not be subclassed

### ISSUE THREAD

**Issue by ionapatterson** [aws/aws-sdk-java#2494]
AmazonS3EncryptionClientV2 can not be subclassed despite lacking final keyword.

AmazonS3EncryptionClientV2 can not be subclassed as it's only constructor method is package-private. Additionally the argument for this constructor is AmazonS3EncryptionClientV2Params which is a package-private class whose only subclass is  AmazonS3EncryptionClientV2ParamsWrapper which is final public (preventing extension) and which also has only a package-private constructor.

**Comment by debora-ito** [comment]
@ionapatterson why do you need a subclass of AmazonS3EncryptionClientV2?

**Comment by ionapatterson** [comment]
@debora-ito We currently provide a subclass of [AmazonS3EncryptionClient](https://github.com/IonicDev/ionic-for-aws-java-sdk-s3/blob/master/src/main/java/com/ionic/cloudstorage/awss3/IonicS3EncryptionClient.java) that provides enhanced interactions with our Key Store and are looking to migrate to subclassing AmazonS3EncryptionClientV2.

**Comment by cenedhryn** [comment]
@ionapatterson To summarize what you described in the issue, AmazonS3EncryptionClientV2 was written with the intention that it not be subclassed. It's a pattern we're moving away from.
Can you change the structure of your client to use a wrapper pattern instead of subclassing? I'm sorry that this will increase the amount of refactoring needed. 

We have started work on the next generation client encryption, for AWS Java SDK v2 (https://github.com/aws/aws-sdk-java-v2/issues/34). It'd be great if you wanted to provide feedback on features you'd like to see supported, such as key management, materials description etc.
