### ISSUE TITLE
CVE-2020-28491

### ISSUE THREAD

**Issue by VinayakKorape** [aws/aws-sdk-java#2561]
In aws-java-sdk-core, package com.fasterxml.jackson.dataformat:jackson-dataformat-cbor from 0 and before 2.11.4, from 2.12.0-rc1 and before 2.12.1. Unchecked allocation of byte buffer can cause a java.lang.OutOfMemoryError exception.
Vendor Statement :
Vendor URL :
NVD URL : https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-28491
Fix Version : 2.11.4
Solution : Upgrade package jackson-dataformat-cbor to version 2.11.4 or above.

**Comment by debora-ito** [comment]
Hi @VinayakKorape thank you for reaching out. This is the same case of #2534, right now we cannot upgrade `jackson-dataformat-cbor` due to backward compatibility issues. 

We are working to upgrade the version of jackson libraries and bump up the SDK version to 1.12.x, #2096 is the tracking issue for this work. In the meantime you can upgrade `jackson-dataformat-cbor` version in your own project.
