### ISSUE TITLE
Does retry logic apply to "InternalError" error when using sendMessageBatchAsync 

### ISSUE THREAD

**Issue by supattra-t** [aws/aws-sdk-java#2562]
I use sendMessageBatchAsync to publish messages to user SQS and I got the error "InternalError" from sendMessageBatchResult.getFailed(). I wonder why it didn't retry the request even though I have set the clientConfiguration.   

## Describe the issue
The clientConfiguration is created by the code below.
`final RetryPolicy.BackoffStrategy bs = new PredefinedBackoffStrategies.ExponentialBackoffStrategy(1800, 15000);`
 
`final ClientConfiguration cf = new ClientConfiguration()
    				.withRetryPolicy(new RetryPolicy(null, bs, 3, false)
				.withRequestTimeout(5000)
		               .withSocketTimeout(4000);`
I got the error at 2021-05-04T11:09:14.418Z while the time that I send the message was 2021-05-04T11:09:14.403Z. It seems the retry logic didn't apply to this.
 
I have raised this issue to AWS support and AWS support think it is about the SDK issue (https://console.aws.amazon.com/support/home?#/case/?displayId=8272910121&language=en).

## Steps to Reproduce
Sending messages to many SQS at the same time. Anyway, this error occurred around 1 out of 16000 message sending.

## Current Behavior
Got the "InternalError" without retrying.

## Your Environment
* AWS Java SDK version used: 'aws-java-sdk-sqs', version: '1.11.934'
* JDK version used: Java 1.8
* Operating System and version: Linux

**Comment by debora-ito** [comment]
The retry logic will not apply to an individual item of sendMessageBatchResult because the `sendMessageBatch` call itself will return a successful status code 200 even if some of the messages have failed, according to the [API docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessageBatch.html). 

The recommendation is to always check `sendMessageBatchResult.getFailed()` and manually retry each failed entry. The SQS Developer Guide has a section about batch operations with Java SDK examples: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-throughput-horizontal-scaling-and-batching.html

**Comment by supattra-t** [comment]
Thank you for clarification.
