### ISSUE TITLE
The ClientConfiguration get proxy setting with protocol type other than proxy protocol type

### ISSUE THREAD

**Issue by HelloHorizon** [aws/aws-sdk-java#2567]
## Describe the bug
The `ClientConfiguration` gets the client configuration from the system based on the protocol type other than proxy protocol type. If the user sets the protocol with HTTPS and proxy protocol with HTTP, the client will set the proxy with system property `https.proxyHost`.

## Expected Behavior
ClientConfiguration sets the client configuration from the system based on the protocol type as:
[protocol check](https://github.com/aws/aws-sdk-java/blob/1c94d1504753629995764231a311f787d42a9c8c/aws-java-sdk-core/src/main/java/com/amazonaws/ClientConfiguration.java#L690)

## Current Behavior
ClientConfiguration sets the client configuration from the system based on the proxy type.

## Possible Solution
Change the check logic as follows:
```
   private String getProxyHostProperty() {
        return getProxyProtocol() == Protocol.HTTPS
                ? getSystemProperty("https.proxyHost")
                : getSystemProperty("http.proxyHost");
    }
```
## Your Environment
* AWS Java SDK version used: 1.11.815
* JDK version used: 1.8
* Operating System and version: mac

**Comment by debora-ito** [comment]
@HelloHorizon unfortunately this won't get fixed in v1 before going into Maintenance Mode. 


Java SDK v2 proxy configuration is done in the individual HTTP clients, you can read more info about them in the [HTTP Client](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/http-configuration.html) section of the Dev Guide. If this issue still persists in v2, please open a [new issue](https://github.com/aws/aws-sdk-java-v2/issues/new/choose) in the v2 repo.


#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)
