### ISSUE TITLE
Feature parity between V1 and V2 SDKs

### ISSUE THREAD

**Issue by jonatan-ivanov** [aws/aws-sdk-java#2608]
Based on the [Developer Guide](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/home.html#features-notyet), there are features in the V1 SDK that are not yet in the version 2 of the SDK and based on the [1.11.x Parity](https://github.com/aws/aws-sdk-java-v2/labels/1.11.x%20Parity) label, there are quite a few issues open.

This can block users to completely move to the V2 SDK also open source libraries to fully support V2.
Are you planning to bring the the Java V2 SDK up to feature parity with V1? If so, do you have any timeline?

See:
- Micrometer: https://github.com/micrometer-metrics/micrometer/issues/1473
- Spring Cloud AWS: https://github.com/awspring/spring-cloud-aws/issues/116

**Comment by mp911de** [comment]
* Spring Vault: https://github.com/spring-projects/spring-vault/issues/253

**Comment by debora-ito** [comment]
Hi @jonatan-ivanov @mp911de 

Yes, we're aware of the feature parity gap and planning to close it, but can't give any timelines unfortunately.

We have created a Project board of Public Feature Requests in here: https://github.com/aws/aws-sdk-java-v2/projects/1
and we try to keep it prioritized, but acknowledge that 1) is not very up-to-date; and 2) the velocity of the release of new feature requests is not as fast as we would like it to be. For example, the comments on the micrometer repo about concerns of the Java SDK feature parity gap were made in May 2020, and since then we have released only a few `1.11.x Parity` features (like Waiters and Client-Side metrics).

I know that reading "can't give a timeline" does not help much, I'm sorry. Right now we are actively working on the V2 versions of TransferManager and the SQS Buffered Client, you can check the progress in the v2 [PRs](https://github.com/aws/aws-sdk-java-v2/pulls). In the meantime, please show your interest in feature requests by adding a 👍  to the original issue, it help us prioritize them.

**Comment by jonatan-ivanov** [comment]
@debora-ito Thanks for your answer, this is actually helpful, thank you. Based on the [1.11.x Parity label](https://github.com/aws/aws-sdk-java-v2/labels/1.11.x%20Parity) (issues from 2017), I was not sure if closing the gap is a goal. Thanks for the clarification.

**Comment by debora-ito** [comment]
I'll go ahead and close this. Feel free to reach out if you have more questions.

**Comment by jonatan-ivanov** [comment]
@debora-ito I think having an "epic" issue that lists the things need to be done for feature parity and that people can refer to would be great so that we can track the progress and clearly see what is done and what is left.

**Comment by debora-ito** [comment]
The [Project Board](https://github.com/aws/aws-sdk-java-v2/projects/1) was created for that purpose, to track the progress of all feature requests using the backlog columns and the "In progress" column. I'll talk to the team and come up with a plan to make it up-to-date again and keep it updated as the time goes by. Do you think that would be sufficient to have a glimpse of the status of features?
