### ISSUE TITLE
DynamoDBMapper Not Detecting Annotations on inherited properties

### ISSUE THREAD

**Issue by jeff-miller-cfa** [aws/aws-sdk-java#2665]
### Describe the bug

If you have a base class:

```
@Data
class Animal{

    @DynamoDBVersionAttribute
    private int version;

}
```

and a child class:

```
@DynamoDBTable(tableName="cats")
class Cat extends Animal{

}
```

The `DynamoDBAutoGenerated` annotation `DynamoDBVersionAttribute` will not be managed because it is an inherited field.

### Expected behavior

The version field should be maintained. The same thing applies to any other annotation using `DynamoDBAutoGenerated` like `DynamoDBAutoGeneratedTimestamp`.

### Current behavior

The field is saved to dynamo if provided but it does not get autogenerated.

### Steps to Reproduce

See the example above.

### Possible Solution

Change the `inherited` parameter on https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/StandardBeanProperties.java#L55 to be true.

### AWS Java SDK version used

1.11.920

### JDK version used

openjdk 11.0.8 2020-07-14

### Operating System and version

MacOS

**Comment by kindagonzo** [comment]
+1 please

**Comment by debora-ito** [comment]
@jeff-miller-cfa apologies for taking so long to respond.

I cannot reproduce the issue, `@DynamoDBVersionAttribute` is enforced as expected in my local tests. I'm not using Lombok though, I'm declaring all the class attributes:

```java
    @DynamoDBTable(tableName="Animal")
    public class Animal {
        private String id;
        private String name;
        private Long version;

        @DynamoDBHashKey
        public String getId() { return id; }
        public void setId(String id) { this.id = id; }

        public String getName() { return name; }
        public void setName(String name) { this.name = name; }

        @DynamoDBVersionAttribute
        public Long getVersion() { return version; }
        public void setVersion(Long version) { this.version = version; }

    }

    @DynamoDBTable(tableName="Cat")
    public class Cat extends Animal{

    }
```

```java
    Cat cat = ddbMapper.load(Cat.class, "99");
    Long currentVersion = cat.getVersion();

    cat.setName("Garfield");
    cat.setVersion(currentVersion+10L); //forcing an exception
    mapper.save(cat);
```

Throws an error as expected:
`2022-03-25 19:22:55,217 [main] DEBUG com.amazonaws.request -  Received error response: com.amazonaws.services.dynamodbv2.model.ConditionalCheckFailedException: The conditional request failed (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ConditionalCheckFailedException; Request ID: xxx; Proxy: null)
`

There's some incompatibility with Lombok probably due to the use of reflection in the DynamoDB Mapper.

Let us know if you have further questions.
