### ISSUE TITLE
package javax.xml.bind does not exist

### ISSUE THREAD

**Issue by ramakris** [aws/aws-sdk-java#2721]
### Describe the bug

I cloned the project and attempted     "mvn clean install -Dgpg.skip=true". and this is what I get. What am I missing? I would expect all the dependencies to be in the pm.xml.

/Users/ramak/aws-sdk-java/aws-java-sdk-core/src/main/java/com/amazonaws/util/Base64.java:[17,21] error: package javax.xml.bind does not exist
[ERROR] /Users/ramak/aws-sdk-java/aws-java-sdk-core/src/main/java/com/amazonaws/util/Base64.java:[18,21] error: package javax.xml.bind does not exist
[ERROR] /Users/ramak/aws-sdk-java/aws-java-sdk-core/src/main/java/com/amazonaws/util/Base64.java:[52,35] error: cannot find symbol
  symbol:   variable JAXBContext
  location: class Base64
[ERROR] /Users/ramak/aws-sdk-java/aws-java-sdk-core/src/main/java/com/amazonaws/util/Base64.java:[83,23] error: cannot find symbol
  symbol:   variable DatatypeConverter
  location: class Base64
[INFO] 4 errors 
[INFO] -------------------

### Expected behavior

The build process should complete without errors

### Current behavior

Throws an error
/Users/ramak/aws-sdk-java/aws-java-sdk-core/src/main/java/com/amazonaws/util/Base64.java:[17,21] error: package javax.xml.bind does not exist
[ERROR] /Users/ramak/aws-sdk-java/aws-java-sdk-core/src/main/java/com/amazonaws/util/Base64.java:[18,21] error: package javax.xml.bind does not exist
[ERROR] /Users/ramak/aws-sdk-java/aws-java-sdk-core/src/main/java/com/amazonaws/util/Base64.java:[52,35] error: cannot find symbol
  symbol:   variable JAXBContext
  location: class Base64
[ERROR] /Users/ramak/aws-sdk-java/aws-java-sdk-core/src/main/java/com/amazonaws/util/Base64.java:[83,23] error: cannot find symbol
  symbol:   variable DatatypeConverter
  location: class Base64
[INFO] 4 errors 
[INFO] -------------------

### Steps to Reproduce

build the binaries.

### AWS Java SDK version used

17

### JDK version used

openjdk 17.0.2 2022-01-18 OpenJDK Runtime Environment (build 17.0.2+8-86) OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

### Operating System and version

mac

**Comment by debora-ito** [comment]
HI @ramakris thank you for reaching out.

The `java.xml.bind` module was part of the [JDK](https://docs.oracle.com/javase/9/docs/api/java.xml.bind-summary.html) but was removed in JDK 11. I see you are using JDK 17 so in order to build the SDK you need to add it as a dependency. The Java SDK v1 was implemented on Java 6.

Note that to use the SDK you don't need to build the project from scratch, you can simply add the service modules you want to use as a dependency in your project. For example, this adds the S3 module as a dependency to the pom.xml:

```
<dependencies>
  <dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-s3</artifactId>
  </dependency>
</dependencies>
```

for more info: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-project-maven.html#configuring-maven.

Also, if you are creating a new project using the Java SDK please consider using the Java SDK 2.x: https://github.com/aws/aws-sdk-java-v2. It's a rewrite of the SDK 1.x, and it's where most new features are being released.

**Comment by khwbilal** [comment]
i am facing the same issue even added the above dependency still its not working
