### ISSUE TITLE
Resuming download with TransferManager not working after JVM restart (AWS SDK 1.12.180)

### ISSUE THREAD

**Issue by rmleme** [aws/aws-sdk-java#2727]
### Describe the bug

Reopening [issue 1351](https://github.com/aws/aws-sdk-java/issues/1351): "_Resuming download with TransferManager not working after JVM restart_".

Issue 1351 was noticed at version 1.11.118 of AWS SDK.

According to @debora-ito [comment](https://github.com/aws/aws-sdk-java/issues/1351#issuecomment-591043385): "_Try the newer versions of the SDK and please reopen if you are still seeing this._"

I retested with version 1.12.180 but the issue still remains. As I'm unable to reopen the original issue, I'm opening a new one.

### Expected behavior

Even after a JVM crash, a given download should resume from the latest snapshot.

### Current behavior

The download is always restarting from the beginning.

### Steps to Reproduce

https://github.com/aws/aws-sdk-java/issues/1351#issuecomment-341036256

### Context

I'm trying to create a reliable Kotlin S3 client, capable of resuming a download from the latest snapshot after a JVM crash, instead of restarting the download from the beginning.

### AWS Java SDK version used

1.12.180

### JDK version used

OpenJDK 64-Bit Server VM (build 17.0.2+8-Ubuntu-120.04, mixed mode, sharing)

### Operating System and version

Ubuntu 20.04.4 LTS

**Comment by debora-ito** [comment]
HI @rmleme 

We apologize but this won't get fixed in v1.  If this is still an issue on [TransferManager v2](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/transfer/s3/S3TransferManager.html), please let us know and put the repro case details in a new [aws/aws-sdk-java-v2 issue](https://github.com/aws/aws-sdk-java-v2/issues/new/choose).

#### Reference:
- [Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)
