### ISSUE TITLE
AbstractProfilesConfigFileScanner does not support comments starting with ";"

### ISSUE THREAD

**Issue by jaeggir** [aws/aws-sdk-java#2746]
### Describe the bug

The config and credential files in `~.aws`are according to https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html INI files. Comment lines in INI files do either start with `;` or `#`.  `AbstractProfilesConfigFileScanner` does only treat empty lines or lines starting with `#` as comment lines: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/profile/internal/AbstractProfilesConfigFileScanner.java#L99

### Expected Behavior

Lines starting with `;` should also be parsed as comments.

### Current Behavior

The parser fails for such files as the line is treated as a key/value pair. See here: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/profile/internal/AbstractProfilesConfigFileScanner.java#L161

### Reproduction Steps

* add "; sample comment" to `~.aws/config`
* use STSAssumeRoleSessionCredentialsProvider to get an AWSCredentialsProvider.

### Possible Solution

AbstractProfilesConfigFileScanner.java#L99
```
 if (line.isEmpty() || line.startsWith("#") || line.startsWith(";")) {
```
=> I can open a PR if this helps.

### AWS Java SDK version used

1.12.195

### JDK version used

11.0.12

### Operating System and version

OSX 12.3.1

**Comment by debora-ito** [comment]
Hi @jaeggir thank you for reaching out, it's a reasonable request.

After a quick test I see Java SDK v2 does consider `;` as a comment character. The team is focused in Java SDK v2 feature work, so this probably won't be fixed in v1.

**Comment by debora-ito** [comment]
@jaeggir this won't get fixed in v1 before going into Maintenance Mode, so I'm closing this issue.

This is fixed in v2, but if you see any other problem related to this please open a [new issue](https://github.com/aws/aws-sdk-java-v2/issues/new/choose) in the v2 repo.

#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)
