### ISSUE TITLE
TransferManager does not honor Request Level Credentials if set

### ISSUE THREAD

**Issue by mgodwan** [aws/aws-sdk-java#2801]
### Describe the bug

TransferManager is internally creating multi-part upload requests.
While creating a multi part upload request, it uses the credentials provider associated with the client.

In case a client provides credentials with a PutObjectRequest, the credentials are not used in the UploadPartRequest created within the TransferManager.

References:

1. Sample request which does not use the creds provider from origReq: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/UploadPartRequestFactory.java#L61

2.  https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/AmazonWebServiceRequest.java#L147

### Expected Behavior

TransferManager should use the credentials provider set on client's request.

### Current Behavior

TransferManager always uses S3 Client credentials.

### Reproduction Steps

Can be reproduced by setting the credentials on PutObjectRequest and setting dummy credentials on S3 Client.
* A request which uploads in a single chunk goes through.
* A request using multi part upload fails.

### AWS Java SDK version used

[1.11.700]

### JDK version used

11

### Operating System and version

OSX

**Comment by yasminetalby** [comment]
Hello @mgodwan,

Thank you very much for your submission.

I haven't been successful reproducing this issue:
When setting different credentials on both the client and putObjectRequest, the TransferManager uses the credential set on the putObjectRequest following the expected behavior:
_Sets the optional credentials provider to use for this request, overriding the default credentials provider at the client level._

Could you please provide the sample code associated with the behavior you encountered?

Best,

Yasmine

**Comment by mgodwan** [comment]
The issue happens when the put object results in a multi part upload with [1.11.700]
Looks like this was fixed in the later versions.

I was able to fix this by updating the dependency version.

CP for the fix: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/UploadPartRequestFactory.java#L136

CP without the fix: https://github.com/aws/aws-sdk-java/blob/59759680facd95c304ff5ce970fd62cb9eae87c2/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/UploadPartRequestFactory.java

Closing this.
