### ISSUE TITLE
The security token included in the request is expired

### ISSUE THREAD

**Issue by arun-rai** [aws/aws-sdk-java#2802]
### Describe the bug

Observing one of our container fail to fetch Message from SQS with error 'The security token included in the request is expired'. This had happened with multiple times for brief period with multiple services (SQS+ Dynamo DB).
Issue got resolved exactly after 15 minutes, without intervening anything.

AWS java SDK - aws-java-sdk-core-1.12.201
Using InstanceProfileCredentialsProvider = new InstanceProfileCredentialsProvider(true));
Cluster: Kubernetes v1.21.11
IAM component: kube2iam (https://github.com/jtblin/kube2iam)

ERROR log: 
com.amazonaws.services.sqs.model.AmazonSQSException: The security token included in the request is expired (Service: AmazonSQS; Status Code: 403; Error Code: ExpiredToken; Request ID: 25b9b369-9954-5d2c-8c21-e84006d4ec55; Proxy: null). 

### Expected Behavior

Issue should not be occurring intermittently. SDK should always be able to fetch token before it get expired.

### Current Behavior

On of container fail to fetch Message from SQS with error 'The security token included in the request is expired'. This had happened with multiple times for brief period with multiple se

### Reproduction Steps

Intermittently. Not always producible. 

### Possible Solution

NA

### Additional Information/Context

NA

### AWS Java SDK version used

aws-java-sdk-core-1.12.201

### JDK version used

java version "11.0.7" 2020-04-14

### Operating System and version

Kubernetes v1.21.11

**Comment by arunhegde** [comment]
@arun-rai did you guys find a solution to this issue? We are also facing exactly same issue on our k8s cluster from few days while using dymanodb.

**Comment by FerasMaali** [comment]
Any updates here? It's also causing us issues while working with SQS & SES

**Comment by arunhegde** [comment]
We have opened a AWS support ticket on the same as we are repeatedly seeing the issues on DynamoDB, Kinesis and Cloudwatch. Our case ID is 10196898021. Please let us know if you guys find out any solutions/work arounds to fix

**Comment by arunhegde** [comment]
@arun-rai -  I think we got some clue. We are still testing it. At the moment it appears to be application issue (the code that is running in the pods). 

In our case we had multiple AWS credentials providers other than the default credentials provider. We cleaned them up, made sure we always have a single credentials provider and that ithe is default credentials provider. Also made sure that all our AWS service calls (dynamodb, cloudwatch, kinesis, x-ray) use the same. 

Also after some investigation on AWS Spring Cloud library we have explicitly set the following property in the properties file
`cloud.aws.credentials.instance-profile=true`

You can set log level on AWSCredentialsProviderChain to debug so you know when it's getting credentials, and from where. 

With above two change we have been constantly monitoring our services and we have not seen the token expiry errors in last 4 days or so which used to happen almost every day before. Still we can't confidently say that the issue is fixed but so far its looking positive.

**Comment by debora-ito** [comment]
Hey everyone, apologies for the long silence in here.
Taking a look at this and at the state of the support cases, will provide an update shortly.

**Comment by debora-ito** [comment]
@arun-rai I don't really have suggestions to add to @arunhegde comment.

In a traditional use of InstanceProfileCredentialsProvider, the SDK would automatically refresh the credentials since "eagerlyRefreshCredentialsAsync" is set to true. Using the `kube2iam` seems to add a complexity to the credential fetching but I'm not familiar with the lib. 

You should identify which process is getting the credentials, when and why it's using expired credentials when it shouldn't, with additional logs if needed.

**Comment by arunhegde** [comment]
Forgot to update. We made one more change probably that’s also the reason
to fix it. We upgraded kube2iam library.

**Comment by vickeyrihal1** [comment]
@arunhegde - If I understood correctly, you didn't upgrade the kube2iam image. It's just the aws cli or some other aws sdk that you run on the nodes has been upgraded? 

Could you share the upgrade steps?
And share the previous and current versions?

**Comment by arunhegde** [comment]
- Updated aws-sdk-go to v1.44.42 from v1.8.7 (kube2iam/go.mod)
- Updated to go 1.17 from go 1.16 (in kube2iam/go.mod)
- Update go-iptables to v0.6.0 from v0.1.0 (in kube2iam/go.mod)
- In kube2iam Dockerfile changed `FROM alpine:3.15.5` to `FROM scratch`
-  Set AWS_METADATA_SERVICE_TIMEOUT: to '3'

These are the main changes i could see... there were many indirect dependency updates with this..

**Comment by slimm609** [comment]
We did very similar actions to the above from @arunhegde and have also seen a resolution to this issue.

**Comment by arunhegde** [comment]
Good to know @slimm609 !

**Comment by debora-ito** [comment]
Looks like this was resolved, closing.

**Comment by abhisheknsit** [comment]
@arunhegde Are you using java sdk version > 1.12.188?
This seems to be coming from these lines of code: https://github.com/aws/aws-sdk-java/blame/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/BaseCredentialsFetcher.java#L162-L179

The sdk is extending the age of credentials by 15 minutes incase it was not able get success from IMDS endpoint.
