### ISSUE TITLE
Provide a priority parameter for TransferManager batched uploads.

### ISSUE THREAD

**Issue by bedge** [aws/aws-sdk-java#284]
We've had great success migrating many upload services to a single instance of the TransferManager.
The one thing that we feel is missing is the ability to prioritize uploads.

**Comment by debora-ito** [comment]
Hi @bedge, the SDK team has reviewed the feature request list for V1, and since they're concentrating efforts on V2 new features they decided to not implement this one in V1. It still being considered for the TransferManager refactor in V2, see the referenced issue above. I'll go ahead and close this one.

Please feel free to comment on the V2 issue with your use case, and reach out if you have further questions.
