### ISSUE TITLE
Shaded sdk bundle doesn't shade mozilla/public-suffix-list.txt

### ISSUE THREAD

**Issue by steveloughran** [aws/aws-sdk-java#2860]
### Describe the bug

the aws-sdk-bundle doesn't shade mozilla/public-suffix-list.txt, which is used by httpclient to determine how it handles https certificates

as a result, if a different library has an out of date list, applications may not be able to connect to more recent s3 regions

This surfaced in [HADOOP-18159](https://issues.apache.org/jira/browse/HADOOP-18159)

### Expected Behavior

aws httpclients get the up to date public suffix list and so connect to all s3 regions

### Current Behavior

If an out of date resource comes from a different library on the classpath, the caller sees the error message "Certificate doesn't match any of the subject alternative names: [*.s3.amazonaws.com, s3.amazonaws.com]"

### Reproduction Steps

1. add a JAR with an outdated copy of the same resource, eg. cos_api-bundle-5.6.19.jar to the classpath
2. attempt to talk to s3 regions

### Possible Solution

when shading resources, move this one.

aws sdk is not unique in not shading this (hadoop doesn't do it properly either)

### Additional Information/Context

reported against v2 SDK as well https://github.com/aws/aws-sdk-java-v2/issues/1786

### AWS Java SDK version used

1.12.262

### JDK version used

not known

### Operating System and version

not known

**Comment by garretwilson** [comment]
I appreciate the issue, but it's not clear what the appropriate approach to shading would be. See my Stack Overflow question, [Maven Shade Plugin transformer to merge text files, discarding duplicate lines](https://stackoverflow.com/questions/76551466/maven-shade-plugin-transformer-to-merge-text-files-discarding-duplicate-lines). Or would it be OK to use the existing [AppendingTransformer](https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#AppendingTransformer) and merge the files, duplicating virtually all of the lines? Will Apache HttpClient merely discard duplicates it finds?

**Comment by steveloughran** [comment]
I don't know what to do here. could the file be renamed and the shaded client set to pick it up? that way you can ship something which knows of all your regions

**Comment by garretwilson** [comment]
> that way you can ship something which knows of all your regions

Regions? This is not a per-region file, is it? It's just that one source happened to be out of date, isn't it?

Honestly I am not familiar with how the original ticket came about, but in my case there were simply different versions of Apache HttpClient being used by transient dependencies, and they had slightly different content because it looks like they were generated at different times with slightly different changelogs—not because they cover different regions. I understood in the case of this ticket that one was simply out of date and was overwriting the newer one via shading.

**Comment by steveloughran** [comment]
the original issue is: [HADOOP-18159](https://issues.apache.org/jira/browse/HADOOP-18159)
Certificate doesn't match any of the subject alternative names: [*.s3.amazonaws.com, s3.amazonaws.com].

the shaded https client couldn't talk to newer s3 regions because of certificate issue

**Comment by steveloughran** [comment]
there was another jar on the classpath with the older list. because both jars had the same path to the list, it was up to the jvm to pick a version, and it chose the one without the newer regions listed as TLDs, hence, s3a stopped talking to those regions.

**Comment by debora-ito** [comment]
@steveloughran  

We apologize but this won't get fixed in v1. If this is still an issue with the Java SDK v2, please let us know and open a [new issue](https://github.com/aws/aws-sdk-java-v2/issues/new/choose) in the v2 repo.

#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)

**Comment by steveloughran** [comment]
@debora-ito someone else hit it in https://github.com/aws/aws-sdk-java-v2/issues/1786

please can someone have a look at this. thanks
