### ISSUE TITLE
`getErrorCode()` returns different value than how is written in the aws documentation

### ISSUE THREAD

**Issue by NellyVladova** [aws/aws-sdk-java#3020]
### Describe the bug

I found that `getErrorCode()` method which is part of `AmazonServiceException` returns different value than how is written in the aws documentation. In the official documentation is written that it should return the AWS error code represented by this exception but this method returns http status code instead of error code. Is this the expected behaviour or the description of this method is wrongly written?

### Expected Behavior

Expected behaviour is to return the AWS error code represented by this exception(e.g. `NoSuchBucket`, `NoSuchKey`, etc.)

### Current Behavior

The current behaviour is that the method returns the http status code instead of the error code

### Reproduction Steps

```
try {
      ObjectMetadata s3ObjectMetadata = s3.getObjectMetadata(bucket, key);
} catch (AmazonS3Exception amazonS3Exception) {
      log.warn("Couldn't process {}, due to: {}", key, amazonS3Exception.getErrorCode());
}
``` 

### AWS Java SDK version used

1.12.520

### JDK version used

17.0.5

### Operating System and version

macOS Ventura 13.5

**Comment by debora-ito** [comment]
That will depend on the operation and on how the service is sending the error in the response.

For example, here's the [wirelogs](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html) of the S3 GetObject response when the bucket does not exist:
```
<< "HTTP/1.1 404 Not Found[\r][\n]"
<< "x-amz-request-id: KCCJA3F7DEVMXF5D[\r][\n]"
<< "<?xml version="1.0" encoding="UTF-8"?>[\n]"
<< "<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>xxx</BucketName><RequestId>xxx</RequestId><HostId>xxx</HostId></Error>
```

`getErrorCode()` in this case will return NoSuchBucket.

But GetObjectMetadata performs a HEAD request under the hood, and HEAD responses don't have a body, so the service can't send additional information like error codes. That's why `getErrorCode()` in this case will return `404 Not Found`.
