### ISSUE TITLE
OOM should not be wrapped

### ISSUE THREAD

**Issue by BusyByte** [aws/aws-sdk-java#3024]
### Describe the bug

See https://github.com/aws/aws-sdk-java-v2/issues/3381#issuecomment-1695937788

### Expected Behavior

Same as https://github.com/aws/aws-sdk-java-v2/issues/3381 only for only for aws-sdk-java

### Current Behavior

SdkClientException is wrapping OutOfMemoryError

### Reproduction Steps

See stack trace on https://github.com/aws/aws-sdk-java-v2/issues/3381#issuecomment-1695937788.

### AWS Java SDK version used

1.12.528

### JDK version used

docker: amazoncorretto:17

### Operating System and version

docker: amazoncorretto:17

**Comment by bjhartin** [comment]
👍

**Comment by debora-ito** [comment]
Acknowledged.

Note that the team is really focusing efforts in Java SDK v2 features, so this will have low priority.

**Comment by debora-ito** [comment]
@BusyByte @bjhartin @fatpitch 

We don't have plans to fix before going into Maintenance Mode, so I'll go ahead and close this.
This is fixed in v2, but if you see any related problem please open a [new issue](https://github.com/aws/aws-sdk-java-v2/issues/new/choose) in the v2 repo.

#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)
