### ISSUE TITLE
Unable to programatically create an SQS queue

### ISSUE THREAD

**Issue by vivekkothari** [aws/aws-sdk-java#3055]
### Describe the bug

When trying to create a SQS queue using,
```
aws.sqs()
            .createQueue(new CreateQueueRequest(name).addAttributesEntry("VisibilityTimeout", "2"));
```
Here `aws.sqs()` returns a `AmazonSQSAsync` object.
I am getting 
```
com.amazonaws.SdkClientException: Unable to execute HTTP request: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (com.amazonaws.event.ResponseProgressInputStream); line: 1, column: 2]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1219)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1165)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:3331)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:3297)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:3286)
	at com.amazonaws.services.sqs.AmazonSQSClient.executeCreateQueue(AmazonSQSClient.java:1116)
	at com.amazonaws.services.sqs.AmazonSQSClient.createQueue(AmazonSQSClient.java:1085)
```

### Expected Behavior

It should successfully create the queue.

### Current Behavior

I am getting the exception mentioned above.

### Reproduction Steps

Use the SDK version `com.amazonaws-aws-java-sdk-bom-1.12.588` and try to create any queue, it fails consistently.
Note that I am using localstack for testing.

### Possible Solution

n/a

### Additional Information/Context

n/a

### AWS Java SDK version used

com.amazonaws-aws-java-sdk-bom-1.12.588

### JDK version used

20.0.2

### Operating System and version

macOS Sonoma

**Comment by debora-ito** [comment]
Hi @vivekkothari 

The SQS service model changed its protocol to AWS JSON-1.0 in version [1.12.585](https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#112585-2023-11-08). Localstack needs to accommodate this change on their side - they are aware of the issue and they have tracking Github issue - https://github.com/localstack/localstack/issues/8267#issuecomment-1806421471

While Localstack doesn't release a new SQS version, you need to use Java SDK version <= 1.12.583 (don't use 1.12.584, it has a bug related to the SQS protocol change that was fixed in 1.12.585).

**Comment by flozano** [comment]
I wonder if a patch release is really expected to contain things such as a protocol change in one of the most common AWS services...

**Comment by debora-ito** [comment]
We understand it was a big change in the SQS model, but it was still a service model change. We reserve minor version upgrades to indicate changes in the SDK.

**Comment by flozano** [comment]
I understand. The problem is the cognitive effort and burden you are putting onto users (AWS customers). You have released almost 600 patch versions with lengthy diffs.

The common wisdom about this kind of patch version is that it's safe to blindly update as they should be mostly bugfixes, additions and non-breaking changes. Clearly this is not the case with AWS SDK and makes me wonder if I have to read each and every patch version changelog, when I just want security fixes and bugfixes. Is there any document explaining what we users can expect from versioning of this library?

**Comment by debora-ito** [comment]
Yes, we do! Check the [VERSIONING.md](https://github.com/aws/aws-sdk-java-v2/blob/master/VERSIONING.md) - I noticed it's not referenced in the main README though, I'll add to it.

Just to clarify one point: the SQS model change did not cause any breaking changes when the SQS endpoint is used directly, it was Localstack that broke, which is a third-party solution. The SDK can't guarantee it will work seamlessly with third-party libraries.

**Comment by flozano** [comment]
> Yes, we do! Check the [VERSIONING.md](https://github.com/aws/aws-sdk-java-v2/blob/master/VERSIONING.md) -

> PATCH - Zero to low risk changes. New features and bug fixes that should be safe to consume without much worry.

> The AWS SDK for Java v2 does NOT follow strict [semantic versioning](https://semver.org/). Patch releases may contain new features in addition to bug fixes. See the FAQ for rationale.

so it's implied that only new features and bugfixes come, not changes in the wire protocol that services use. From AWS docs, it seems the new protocol reduces latency, CPU and memory. Those changes are welcome for sure, but it's not a trivial change.

> the SQS model change did not cause any breaking changes when the SQS endpoint is used directly

it's a big change however, as it changes the protocol of a queue system (!!!) in a patch release (!!!). It can have colateral effects.
