### ISSUE TITLE
AWS SDK Metrics not reporting HttpClientPoolAvailableCount or HttpClientPoolPendingCount

### ISSUE THREAD

**Issue by AndrewMacKenzieFD** [aws/aws-sdk-java#3099]
### Upcoming End-of-Support

- [X] I acknowledge the upcoming end-of-support for AWS SDK for Java v1 was [announced](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/), and migration to AWS SDK for Java v2 is recommended.

### Describe the bug

version 1.11.804

aws-sdk-core - AwsSdkMetrics

We are attempting to use this package in order to monitor our SNS connection pools, during testing we have observed that both HttpClientPoolAvailableCount & HttpClientPoolPendingCount are not being reported when making requests, but HttpClientPoolLeasedCount is.

We have implemented our own RequestMetricCollector with additional logging and can confirm that there are no instances of the aforementioned metrics as part of the AWSRequestMetrics object on the requests in question from both SNS and SQS.

### Expected Behavior

We would expect these metrics to be produced.

### Current Behavior

The metrics HttpClientPoolAvailableCount & HttpClientPoolPendingCount are not being reported as part of the Request inside the AWSRequestMetrics object during any SNS or SQS operation.

### Reproduction Steps

1. AwsSdkMetrics enabled for application
2. SNS sync client created, using NotificationMessagingTemplate to publish messages

### AWS Java SDK version used

1.11.804

### JDK version used

17

### Operating System and version

docker - eclipse-temurin:17-alpine

**Comment by debora-ito** [comment]
@AndrewMacKenzieFD there's no obvious reasons why the SDK would not obtain HttpClientPoolAvailableCount 
 or HttpClientPoolPendingCount, specially because the three metrics are captured at the same time:

https://github.com/aws/aws-sdk-java/blob/53c5f6bc86ebd255839eda363e95f13480b29361/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L1546-L1549

Is this something reproducible? 
Is it intermittent or it happens every time?

JDK 17 is not supported in the Java SDK v1, this could be related but I'm not sure. Could you test with JDK <= 16?
