### ISSUE TITLE
Clarify supported java versions

### ISSUE THREAD

**Issue by pulkitnt** [aws/aws-sdk-java#3131]
### Upcoming End-of-Support

- [X] I acknowledge the upcoming end-of-support for AWS SDK for Java v1 was [announced](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/), and migration to AWS SDK for Java v2 is recommended.

### Describe the issue

From https://github.com/aws/aws-sdk-java/issues/2795#issuecomment-1226590872 we read:

> Essentially, the Java SDK v1 will support Java versions from 7 to 16.

But the same comment point to: https://github.com/aws/aws-sdk-java#maintenance-and-support-for-java-versions and that reads:

> The AWS Java SDK version 1 (v1) supports Java versions from 7 to 17

So I think https://github.com/aws/aws-sdk-java#maintenance-and-support-for-java-versions needs to be updated to:

> The AWS Java SDK version 1 (v1) supports Java versions from 7 to 16

### Links

https://github.com/aws/aws-sdk-java#maintenance-and-support-for-java-versions

**Comment by debora-ito** [comment]
@pulkitnt

That comment was made in 2022. Since then, we fixed all known compatibility issues on the SDK side, and SDK version >= 1.12.715 supports Java 17 - see the [1.12.715 changelog](https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#112715-2024-05-03) entry.

The README is up-to-date. If you experience any issue with Java 17, let us know.
