### ISSUE TITLE
Unable to build one all encompassing jar file from source

### ISSUE THREAD

**Issue by Don10** [aws/aws-sdk-java#342]
I have read #313 and #314 but that does not seem to answer my question.

I use to be able to use the maven command as shown on the github page to build the AWS source code which resulted in one jar file that I could then have my project use to reference all the AWS APIs. 

So for example when building the 1.8.9 code base using “mvn clean install -Dgpg.skip=true” as instructed on the github page it would result in one jar file called “aws-java-sdk-1.8.9.1.jar”  which I could then use to reference all the AWS code. However this is not the case anymore when building the 1.9.14 code base. 

Is this by design and if so why? 
Is there a way to build the one all encompassing jar anymore? If so how?

Thanks

**Comment by david-at-aws** [comment]
Yes, this is by design. Many users of the SDK only talk to a couple AWS services, and don't want to have to pull in the whole rest of the SDK (which now supports somewhere in the range of 40 services with no signs of leveling off). With 1.9+ we've moved the client for each service into a different submodule, allowing customers in this position to pick up only the submodules they actually need.

The aws-java-sdk-osgi module now builds the old consolidated jar containing everything, if you prefer picking up the whole SDK in one shot.

```sh
mvn clean install
jar -tf aws-java-sdk-osgi/target/aws-java-sdk-osgi-{version}.jar
```
