### ISSUE TITLE
SimpleWorkflow getList of things returns null vs empty list

### ISSUE THREAD

**Issue by soldiermoth** [aws/aws-sdk-java#345]
I was wondering why the convention was changed from
```java
public java.util.List<HistoryEvent> getEvents() {
    if (events == null) {
         events = new com.amazonaws.internal.ListWithAutoConstructFlag<HistoryEvent>();
          events.setAutoConstruct(true);
    }
    return events;
}
```
to
```java
public java.util.List<HistoryEvent> getEvents() {
   return events;
}
```

in 1.8.x to 1.9.x
samples taken from
https://github.com/aws/aws-sdk-java/blob/1.8.11/aws-java-sdk/src/main/java/com/amazonaws/services/simpleworkflow/model/DecisionTask.java#L243-L256
and 
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-simpleworkflow/src/main/java/com/amazonaws/services/simpleworkflow/model/DecisionTask.java#L246-L255

I noticed this convention changed a number of places so I'm assuming it's an across the board thing.

**Comment by hanshuo-aws** [comment]
Yes, this is a breaking change we introduced in 1.9.x sdk version.

As you have found out, before the change, list-attribute getter returns an empty list by default. We find this behavior very confusing in either case when the data model is used as a request parameter or comes from a service response.

From the service perceptive, null vs empty list can mean completely different things - for an Update*** API request, a null list (i.e. the list attribute is not included in the request JSON body) typically means to keep the existing list value unchanged, whereas an empty list means to change it to empty. Similarly, in the service response, a null list value usually means that the data for such parameter is unknown or unspecified, whereas `"events" : []` means the data is explicitly an empty list.

Because of how the model class used to auto-construct list value by default, we had to rely on the ListWithAutoConstructFlag(true) wrapper to distinguish such auto-construct lists, so that `"events" : []` does not appear in the marshalled request if the `events` parameter was never touched by the caller (as opposed to explicitly providing an empty list value via the setter). And when `DecisionTask` is unmarshalled from the service response, `getEvents()` returns you an empty list even when the `"events"` attribute doesn't appear in the response content at all.

As you probably would agree, we find this behavior very confusing and hard to reason about, since what you get from the parameter getter is not necessarily the same as what will be sent in the request or what you actually received from the service. This problem becomes even messier when we evaluate how we would support map-type attributes in the swf API (we apparently are not excited about having to create another MapWithAutoConstructFlag wrapper...), and we feel that it's the right time to completely get rid of the auto-construct behavior in the swf API.

What we did is we flipped a code-gen configuration in our internal system which effectively changes all the list-type parameter getters in the swf sdk module to simply return null as the default. The request marshaller implementation can then directly pass whatever value it gets from the request model class, and sends it over to the wire. For responses, you will now get a null list if such attribute was not mentioned in the service response body at all.
