### ISSUE TITLE
SQS client allows empty MessageAttribute DataTypes

### ISSUE THREAD

**Issue by leelynne** [aws/aws-sdk-java#352]
Client version: 1.9.17

When Sending a SQS message with MessageAttributes and not specifying the DataType the client still sends the invalid request.

I am calling the reqeust invalid after reading this from the docs: "Name, type, and value must not be empty or null" - http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/SQSMessageAttributes.html#SQSMessageAttributes.DataTypes

Example java code:
SendMessageRequest sqsReq = new SendMessageRequest(queueUrl, body);
MessageAttributeValue pathVal = new MessageAttributeValue();
pathVal.setStringValue(req.path);
sqsReq.addMessageAttributesEntry("path",pathVal);

Results in a sqs message (note the missing MessageAttribute.1.Value.DataType key/value):
"Action=SendMessage&Version=2012-11-05&MessageBody=body&MessageAttribute.1.Name=path&MessageAttribute.1.Value.StringValue=pathVal"

The client should ideally set the DataType with the setTYPEValue() method - e.g. setStringValue() will set the dataType to String if it isn't already set.

**Comment by hanshuo-aws** [comment]
@leelynne 
In general, the SDK does not perform client-side validation or provide any default parameter input. The reason that we don't do it is (mostly) because we want to make sure the SDK is forward-compatible if the service ever changes their input validation logic. For example, imagine someday the SQS service does allow the DataType to be unspecified but all the existing SDK versions are stuck with this default behavior, then we would have to force customers to upgrade to the latest SDK in order to disable this client-side behavior which was once deemed "helpful". We try to prevent such problem by making the SDK a thin layer above the service's HTTP interface, and let the service side to deal with the input validation.
