### ISSUE TITLE
S3 Multipart upload Infinite loop

### ISSUE THREAD

**Issue by bornmw** [aws/aws-sdk-java#359]
Using the latest AWS SDK (1.9.17) my multipart upload results in an infinite loop inside `com.amazonaws.services.s3.internal.InputSubstream:70` loop. It might be because of ByteArrayInputStream, but it is a legitimate InputStream. Tried JDK 1.8 and 1.6 on Linux.

This is the straightforward test program based on [multipart upload example](http://docs.aws.amazon.com/AmazonS3/latest/dev/llJavaUploadFile.html) that goes into infinite loop at `i=5`:

```java
package test;

import com.amazonaws.services.s3.AmazonS3Client;
import com.amazonaws.services.s3.model.*;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by omikheev on 2/10/15.
 */
public class Main {

    public static void main(String[] args) throws Exception {
        AmazonS3Client s3Client = new AmazonS3Client();
        String bucketName = "webdav-test-oleg";
        String filePath = "testFile";
        byte[] data = new byte[122880000];
        InputStream inputStream = new ByteArrayInputStream(data);
        long partSize = 10 * 1024 * 1024;

        List<PartETag> partETags = new ArrayList<PartETag>();

        // Step 1: Initialize.
        InitiateMultipartUploadRequest initRequest = new InitiateMultipartUploadRequest(bucketName, filePath);

        InitiateMultipartUploadResult initResponse =
                s3Client.initiateMultipartUpload(initRequest);


        try {
            // Step 2: Upload parts.
            long filePosition = 0;
            for (int i = 1; filePosition < data.length; i++) {
                // Last part can be less than partSize. Adjust part size.
                partSize = Math.min(partSize, (data.length - filePosition));

                // Create request to upload a part.
                UploadPartRequest uploadRequest = new UploadPartRequest()
                        .withBucketName(bucketName).withKey(filePath)
                        .withUploadId(initResponse.getUploadId()).withPartNumber(i)
                        .withFileOffset(filePosition)
                        .withInputStream(inputStream)
                        .withPartSize(partSize);

                // Upload part and add response to our list.
                partETags.add(s3Client.uploadPart(uploadRequest).getPartETag());
                System.out.println("Uploaded part " + i);
                filePosition += partSize;
            }

            // Step 3: Complete.
            CompleteMultipartUploadRequest compRequest = new
                    CompleteMultipartUploadRequest(bucketName,
                    filePath,
                    initResponse.getUploadId(),
                    partETags);

            s3Client.completeMultipartUpload(compRequest);
        } catch (Exception e) {
            s3Client.abortMultipartUpload(new AbortMultipartUploadRequest(bucketName, filePath, initResponse.getUploadId()));
            throw e;
        }
        System.out.println("Written " + data.length);
    }

}
```

This is the last line before it goes into infinite loop and never returns:
![selection_082](https://cloud.githubusercontent.com/assets/214126/6125593/9684de84-b0cc-11e4-9153-a8bb4f83c11e.png)

In `com.amazonaws.services.s3.internal.InputSubstream` `super.skip` always returns 0 so `while` can never finish:

![selection_081](https://cloud.githubusercontent.com/assets/214126/6125246/fa603344-b0c8-11e4-93a6-1461f5bf70f0.png)

**Comment by bornmw** [comment]
Ok sorry, removing .withFileOffset(filePosition) solved it

**Comment by bornmw** [comment]
Thinking again - should `withFileOffset` interfere with the Stream at all?

**Comment by hansonchar** [comment]
Hi @bornmw,

The fileOffset is typically used when a file is specified, not when an input stream is specified.  If you specified a file offset when an input stream is in use, the current implementation would use that offset as an offset from the current position of the given input stream, and skip that many bytes before reading the data (from the input stream).  

I think what happened is that, as an inadvertent side effect, most of the bytes from the input stream were thus skipped until no more data was available.  Meanwhile, since the content length was specified during a mutipart upload by the sending client in this case, the server side would just wait indefinitely on the connection for more data and hence have the appearance of an "infinite loop".

**Comment by bornmw** [comment]
Thanks for extensive explanation.
It's still worries me that a library can be forced into an infinite loop by giving it certain input. I don't think libraries should ever go into infinite loops, but that's just me.

**Comment by hansonchar** [comment]
Hi @bornmw, 

Fair comment.  In this case I can see two ways to improve the library.
1. Fail fast upon setting the file offset of the part upload request when no file has been specified;
2. Wrap the input sub stream with a [LengthCheckInputStream] (https://github.com/aws/aws-sdk-java/blob/1dfaca1d27f736df52488446dfafb1008e41d326/aws-java-sdk-core/src/main/java/com/amazonaws/util/LengthCheckInputStream.java) so that should the data read for each part turns out to be less than the expected part size, the upload would fail fast instead of waiting for more bytes to upload indefinitely.

What do you think?

**Comment by bornmw** [comment]
Hi @hansonchar 

I think that:
Streams have their own methods to skip that end users should use if they want to skip to some position.
Files don't have that, so that's why UploadPartRequest has file offset.
And that's why file offset should not try to skip bytes in streams, because it's just not supposed to do that.
So it would be logical not to apply file offset to streams.
And you won't even have to change withFileOffset() javadoc, because it says "Sets the optional offset in the specified *file*"
It seems that file offset being applied to streams is not what current javadoc says, and it's a bug.

Thanks

**Comment by hansonchar** [comment]
Hi @bornmw 

Good point on backward compatibility.  So it seems the safest improvement would be (2) ie uses a LengthCheckInputSteam to fail fast in face of an unexpected data length being read.  In other words, instead of blocking indefinitely when the data read is less than the part size, it would fail fast instead.

**Comment by bornmw** [comment]
Yes, I guess my long passage translates into (2)

**Comment by hansonchar** [comment]
Turns out there is indeed an infinite loop in the InputSubstream at line 71 in this case, when it tries to skip over the initial offset to the desired position.  Since the number of bytes skipped is zero, the while loop becomes infinite.

**Comment by hansonchar** [comment]
Will have this fixed in the next release.  Thanks, @bornmw !
