### ISSUE TITLE
Unable to create an EBs environment

### ISSUE THREAD

**Issue by anunesse** [aws/aws-sdk-java#365]
Hi,

I am using sdk 1.9.22 to deploy applications with the AWSElasticBeanstalkClient, I would like to manage a pool of EBs dockerized applications.

I am experiencing some difficulties to create a working environment with the CreateEnvironmentRequest, I would like to launch applications with the default Amazon linux running Docker image:

```java
//CREATE ENVIRONMENT
CreateEnvironmentRequest createEnvironmentRequest = new CreateEnvironmentRequest()
.withEnvironmentName(instance.getName())
.withApplicationName(instance.getName())
.withSolutionStackName("64bit Amazon Linux 2014.09 v1.2.0 running Docker 1.3.3");
CreateEnvironmentResult environmentResult = elasticBeanstalkClient.createEnvironment(createEnvironmentRequest);
```

Is there a way to create a working environment this way? Is it possible to launch a custom docker environment using a Dockerfile, a Dockerrun.aws.json or a full project from this Java client and if so how?

Thank you in advance.

**Comment by fulghum** [comment]
Hey @anunesse , you should be able to use the AWS Elastic Beanstalk API through the AWS SDK for Java to launch any environment you want to.  I'd reach out to the Elastic Beanstalk engineers through the AWS Elastic Beanstalk forum:
https://forums.aws.amazon.com/forum.jspa?forumID=86

They'll be able to give you the exact details of how you'd need to interact with the AWS Elastic Beanstalk API in order to launch whatever type of environment you need to set up.  

Hope that helps!
