### ISSUE TITLE
Allow AmazonWebServiceClient instances to share HttpClient instances

### ISSUE THREAD

**Issue by christophercurrie** [aws/aws-sdk-java#400]
Per the [HttpClient performance guide](http://hc.apache.org/httpclient-3.x/performance.html) it is recommended to share `HttpClient` instances per communication component or application. It would be a nice feature if there were an option for external control over the creation and configuration of HttpClient instances, which could then be passed to the SDK Clients.

**Comment by hanshuo-aws** [comment]
@christophercurrie 
The benefit of reusing HttpClient instance mostly comes from the HTTP connection pooling. But when multiple service clients share the same httpclient, such benefit is non-existent since service clients don't share the same endpoints and hence no connection can be actually reused across them.
Another reason why we don't allow supplying your own HttpClient instance is that we want to avoid making our public API tightly coupled with the Apache HttpClient library. An interesting idea we have been talking about is to come up with a generic HttpClient SPI (together with a default adapter for the Apache's implementation) as the first step to make our http layer an entirely pluggable component. I believe one of the outcomes of this bigger change would be the feature you requested here.
I will close this issue for now, but feel free to let us know if you have any additional question. (Or give us a +1 if you like the HttpClient SPI idea -- our work is always prioritized based on feedback from users like you).

**Comment by christophercurrie** [comment]
Definitely :+1: on a pluggable implementation, especially if such an implementation facilitated asynchronous usage.

**Comment by afranken** [comment]
also a :+1:  for the HttpClient SPI

**Comment by jglazner** [comment]
That would be freakn' awesome. :+1:  please add this!

**Comment by jgangemi** [comment]
:+1:

**Comment by shorea** [comment]
We just launched a Developer Preview of AWS SDK for Java 2.0 that adds support for this feature request. Try it out and let us know what you think!

https://github.com/aws/aws-sdk-java-v2
http://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/welcome.html
https://aws.amazon.com/blogs/developer/aws-sdk-for-java-2-0-developer-preview/
