### ISSUE TITLE
DynamoDB's AttributeValue.java getN() returns String instead of a number.

### ISSUE THREAD

**Issue by rlopezxl** [aws/aws-sdk-java#418]
From the code:
```
/**
* A Number data type.
*/
private String n;
```
This should return a number data type not a String.

**Comment by hansonchar** [comment]
The reason why the internal of N is represented as a String has to do with the low level wire protocol, where the Amazon DynamoDB service API actually has it defined as a string.  [AttributeValue.java](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/model/AttributeValue.java), in turn, is a model class auto-generated from the underlying service model definition.

I would recommend, however, not to deal with the low level constructs directly, but instead make use of a higher level API, such as [Item.java](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/document/Item.java) of the DynamoDB Document API, where 

```java
Item#getNumber("myNumberAttr")
```

, for example, would return a ```BigDecimal```.  The Amazon DynamoDB Document API provides a super set of all the functionalities of the low-level client, but with an API that makes use of the Java type system instead of the low-level artifacts such as ```AttributeValue```.  For more information:
 
  [Introducing DynamoDB Document API (Part-1)](http://java.awsblog.com/post/Tx1DDAWQGXWITSG/Introducing-DynamoDB-Document-API-Part-1)
 [Introducing DynamoDB Document API (Part-2)](http://java.awsblog.com/post/Tx3C0ANZBMQY1RL/Introducing-DynamoDB-Document-API-Part-2)
