### ISSUE TITLE
APIs to recompute signature for a request in S3 server?

### ISSUE THREAD

**Issue by akiradeveloper** [aws/aws-sdk-java#481]
I am looking for some APIs to recompute signature in S3 server for authentication but haven't found one yet.

Is this project only for clients? The signature computation scheme in both client/server side is the same in theory so I guess it's easy to factor out such module so server implementations can reuse. But it seems not.

Does this project actually have one? or does some third party library exist for this purpose?

**Comment by zhangzhx** [comment]
I don't know what the underlying reason is that you want the APIs to recompute signature. As what you said, the signature computation scheme in both client/server side is the same. Why can't you just use the method in the client side to compute the signature?

The following is the signature version 4 signer which is adopted by most of the AWS services.

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/AWS4Signer.java#L173

**Comment by shorea** [comment]
Closing issue as there hasn't been a response.
