### ISSUE TITLE
Dry run requests have wrong results when AWS returns AuthFailure/401

### ISSUE THREAD

**Issue by glb** [aws/aws-sdk-java#494]
Attempting a dry run of a request gets an "Unrecognized service response" error when AWS responds with an AuthFailure / 401.

**Comment by hanshuo-aws** [comment]
This looks like more of a service-side issue. In the [official EC2 documentation](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/CommonParameters.html), it clearly states that unauthorized dry-run request is expected to return <code>UnauthorizedOperation</code>, not <code>AuthFailure</code>.

Can you give us more information on how to reproduce this? From which EC2 API did you see the AuthFailure/401 response?

I will pass the information to the service team to investigate. If it's indeed the expected behavior, we will merge your fix and also update the API documentation so that other EC2 SDKs and tools can be informed about this problem.

**Comment by glb** [comment]
Thank you!

I get `AuthFailure` when the access key ID is not a valid AWS access key ID (eg. "1234" instead of a 20-character string). I'm seeing this from the `Describe*` API calls, e.g.:
```
AWSCredentials basicCredentials = new BasicAWSCredentials("1234", "5678");
AmazonEC2Client ec2 = new AmazonEC2Client(basicCredentials);

ec2.dryRun(new DescribeInstancesRequest());
```
gets me:
```
Aug 26, 2015 4:27:20 PM com.amazonaws.http.AmazonHttpClient logHeaderRequestId
INFO: x-amzn-RequestId: not available
Exception in thread "main" com.amazonaws.AmazonClientException: Unrecognized service response for the dry-run request.
	at com.amazonaws.services.ec2.AmazonEC2Client.dryRun(AmazonEC2Client.java:10859)
	at TestClient.main(TestClient.java:25)
Caused by: com.amazonaws.AmazonServiceException: AWS was not able to validate the provided access credentials (Service: AmazonEC2; Status Code: 401; Error Code: AuthFailure; Request ID: bdaec8c2-6363-4d18-8a34-7377d2a308c0)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1127)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:462)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:297)
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:10903)
	at com.amazonaws.services.ec2.AmazonEC2Client.dryRun(AmazonEC2Client.java:10851)
	... 1 more
```

**Comment by hanshuo-aws** [comment]
Aha, that makes sense now.

The dry-run parameter is used for checking whether the caller is authorized to make the API call, and the authorization check happens ***after*** it passes the authentication. Under this context, an authorization(AuthZ) error and an authentication(AuthN) error could mean very different thing to the user:
* AuthZ error means you are not allowed to make this specific API call, but you might be if you call something else. This error is the only signal that the dryRun method should rely on when returning false to the caller. 
* On the other hand, AuthN error means you basically can't do anything with EC2 since none of the API supports unauthenticated call. It's most likely an indication of a programming error (e.g. passing bad credentials), and therefore in this case I think it makes more sense to throw an exception.

With all that said, I don't think the SDK should wrap the <code>AuthFailure</code> error in an <code>AmazonClientException</code> before throwing it, and I suspect it might be the source of confusion here. I would vote keeping the error-code check as is, but changing the method to throw the original service error if it's not the expected <code>UnauthorizedOperation</code>. What do you think?

**Comment by david-at-aws** [comment]
:+1:

**Comment by glb** [comment]
Hmm... as a consumer of `dryRun`, I expected that I would get a `DryRunResult` indicating that the request would be unsuccessful and with the details of the problem available (which is what the pull request implements). The failure may not be a _programmatic_ error -- for example in my case I write a program that takes credentials as user input -- and so forcing the programmer to handle the two cases (invalid permissions and invalid credentials) using a different control structure (check the `DryRunResult` and handle the exception) seems more complicated than necessary.

From the javadocs for `dryRun`:
> Checks whether you have the required permissions for the provided AmazonEC2 operation, without actually running it. The returned DryRunResult object contains the information of whether the dry-run was successful. This method will throw exception when the service response does not clearly indicate whether you have the permission.

Does this make sense?

**Comment by hanshuo-aws** [comment]
Authenticating the request with invalid keys is only one of the possible reasons for an <code>AuthFailure</code> error. There are many other cases where the authentication could fail due to client or system misconfiguration (e.g. using a wrong region name for request signing, or system clock is skewed), while the account being used does have full access to the service.

In summary, <code>AuthFailure</code> is not a sufficient indicator of whether the user has permission to invoke the API or not, and throwing an exception in this case does match the behavior as described in the documentation.

**Comment by glb** [comment]
OK, fair points, but also not programmatic errors. I will offer one last reason to consider the original content of the pull request, and that goes back to the "dry run". As a consumer of the `dryRun` API, I expected to get an indicator via the `DryRunResult` of likely success or failure if I execute the request normally. I think that the documented semantics of the `dryRun` API could safely be expanded to include this particular scenario without affecting existing users -- the unsuccessful result would still be an indication to the coder that the request would not be successful if run normally, and they could inspect the details to determine further whether the cause was an authentication or an authorization problem, both of which are likely to be _configuration_ rather than _coding_ issues.

If that's not a convincing reason, then I'll re-work to throw the original service exception as you suggested earlier.

**Comment by glb** [comment]
@hanshuo-aws I've updated the pull request per your comments.

**Comment by hanshuo-aws** [comment]
Hey @glb, I have merged the pull request. Thanks for the contribution.

**Comment by glb** [comment]
Thanks!
