### ISSUE TITLE
S3 waitForCompletion Swallows Error

### ISSUE THREAD

**Issue by mrawdon** [aws/aws-sdk-java#498]
An OOM Error occurred in my application(not the fault of the AWS SDK), but the Error is swallowed by the waitForCompletion call.  This prevents the rest of my application from properly handling the Error.
I believe the culprit is in [AbstractTransfer Line 277] (https://github.com/aws/aws-sdk-java/blob/8397ef2731c9ea57de1a529a2e3991eebb96b257/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/AbstractTransfer.java#L277)
I think it should only capture an Exception there, but continue throwing any Error
```
com.amazonaws.AmazonClientException: Unable to complete transfer: Java heap space
        at com.amazonaws.services.s3.transfer.internal.AbstractTransfer.unwrapExecutionException(AbstractTransfer.java:277) ~[aws-java-sdk-1.9.31.jar:na]
        at com.amazonaws.services.s3.transfer.internal.AbstractTransfer.rethrowExecutionException(AbstractTransfer.java:261) ~[aws-java-sdk-1.9.31.jar:na]
        at com.amazonaws.services.s3.transfer.internal.AbstractTransfer.waitForCompletion(AbstractTransfer.java:103) ~[aws-java-sdk-1.9.31.jar:na]
        at com.mitrend.util.s3.S3Helper.saveFile(S3Helper.java:207) ~[S3Helper.class:na]
```

**Comment by shorea** [comment]
Hey @mrawdon. Thanks for reporting this. I agree this is surprising and unintuitive behavior. We unfortunately cannot make this change without a major version bump as it is semantically a breaking change for other customers relying on the current behavior. We have placed this on the list of changes we want to make for the next major version release. In the short term I suggest creating a small wrapper around TransferManager to catch the AmazonClientException, unwrap it, throw if Error otherwise throw the original AmazonClientException (or the unwrapped exception if you think that's more appropriate). Kind of hacky but you'll be able to remove it 1.11 whenever we get enough motivation to make the jump.

**Comment by mrawdon** [comment]
Thanks for the response that should work for now.

**Comment by shorea** [comment]
We are looking to address this soon in our next major version. Closing issue.
