### ISSUE TITLE
Elastic Transcoder rejects empty array of Artwork

### ISSUE THREAD

**Issue by rankinc** [aws/aws-sdk-java#506]
Hi,
The files I pass to Elastic Transcoder may or may not contain cover artwork, and I would like Elastic Transcoder to preserve any that exists. And so I added the following to my `CreateJobOutput` object:

```
JobAlbumArt albumArt = new JobAlbumArt()
   .withMergePolicy("Fallback")
   .withArtwork();
```
This is consistent with the documentation. However, AWS rejects this because "The required value 'Output:AlbumArt:Artwork' was not found.". And yet an empty _list_ of `Artwork` (rather than an array) _is_ accepted! Is this a bug in the Elastic Transcoder Java SDK 1.10.16?

I've examined the source code for `JobAlbumArt.withArtwork(Artwork... artwork)`, and I am suspecting that this line isn't doing what it intends:

```
if (getArtwork() == null) setArtwork(new java.util.ArrayList<Artwork>(artwork.length));
```

for the simple reason that `getArtwork()` can _never_ return null.

Cheers,
Chris

**Comment by hanshuo-aws** [comment]
Hi @rankinc, I will try to explain and see if it helps.

Under the hood, the SDK serializes your request parameters into a JSON document and then sends it to the service over the wire. In particular, a JSON array value in the wire protocol is modeled as a Java List in the SDK API.

The javadoc is indeed confusing here since it mentions **use an empty Artwork** ***array***.  This is because our javadoc is data-driven from the service documentation for the wire protocol, and an empty JSON array on the wire actually means an empty List in the Java API. We will see how we can improve our javadoc to make this more clear.

As to why `withArtwork()` doesn't work, there isn't much compelling reason why it's done this way, but when there is no input parameter, this method behaves the same as if the method is not called at all. This means after you call `withArtwork()`, the Artwork parameter is still unspecified and the SDK will NOT include this parameter in the JSON content. In comparison, when you call `withArtwork(Collections.emptyList())`, you are explicitly specifying an empty List, and the SDK will serialize it to `{"Artwork" : []}`, which matches the service documentation ***use an empty Artwork array***.

Because of backwards-compatibility, we can't modify the SDK's existing behavior as described above. But we will definitely look at improving our documentation to avoid confusion.

**Comment by rankinc** [comment]
Yes, it is unclear; I would have expected `withArtwork(Artwork...)` and `withArtwork(List<Artwork>)` to have identical semantics since (on the face of it) they appear just to be different forms of the exact same function. _Particularly_ since the array variant contains these lines:

```
if (getArtwork() == null) setArtwork(new java.util.ArrayList<Artwork>(artwork.length));
```

which *strongly* suggest that the function's original author intended to implement the following really:

- If there is no artwork yet then create an empty list,
- Add all of the caller's artwork to the list.

> there isn't much compelling reason why it's done this way

Heh, that just sounds like a euphemism for "it's a bug"... ;-). I'm sorry that backwards-compatibility prevents you from fixing it, but I would at least recommend deleting the above line because `getArtwork()` simply _cannot_ return null.

**Comment by hanshuo-aws** [comment]
To be clear, the semantics of `withArtwork(Artwork...)` and `withArtwork(List<Artwork>)` are quite different, and the difference is [explicitly called out in the javadoc] (https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-elastictranscoder/src/main/java/com/amazonaws/services/elastictranscoder/model/JobAlbumArt.java#L194-L198). You may or may not agree, but I think how the SDK currently behaves when `withArtwork()` is called  (i.e. treat it as a no-op) does match up with the documentation.

At any rate, I do agree we should make it more clear in the javadoc to explain the expected behavior when no argument is passed to the vararg method.

**Comment by rankinc** [comment]
It doesn't really matter since you've already stated that backwards-compatibility prevents you from fixing this, but [the original version of that function looks like this](https://github.com/aws/aws-sdk-java/blob/b12c539a663e025ed15da50bf56a25a237c25104/aws-java-sdk-elastictranscoder/src/main/java/com/amazonaws/services/elastictranscoder/model/JobAlbumArt.java):

```
    /**
     * The file to be used as album art. There can be multiple artworks
     * associated with an audio file, to a maximum of 20. Valid formats are
     * <code>.jpg</code> and <code>.png</code>
     * <p>
     * Returns a reference to this object so that method calls can be chained together.
     *
     * @param artwork The file to be used as album art. There can be multiple artworks
     *         associated with an audio file, to a maximum of 20. Valid formats are
     *         <code>.jpg</code> and <code>.png</code>
     *
     * @return A reference to this updated object so that method calls can be chained
     *         together.
     */
    public JobAlbumArt withArtwork(Artwork... artwork) {
        if (getArtwork() == null) setArtwork(new java.util.ArrayList<Artwork>(artwork.length));
        for (Artwork value : artwork) {
            getArtwork().add(value);
        }
        return this;
    }
```

You will observe that the function's implementation is the same as it is today, but that the Javadoc is different. Curiously, both `withArtwork()` variants actually have the _exact same_ Javadoc at this time... According to the Git history, the array variant's Javadoc seems to have been tweaked slightly 6 months later, with the release of SDK 1.9.30. My guess is that someone had decided at that point to try to document what the function _really_ does, as opposed to what it was originally _supposed_ to do.

I'm curious: What do you believe the line
```
if (getArtwork() == null) setArtwork(new java.util.ArrayList<Artwork>(artwork.length));
```
is actually _for_?! I _defy_ you to achieve 100% code-branch coverage here in unit testing ;-).

**Comment by hanshuo-aws** [comment]
> My guess is that someone had decided at that point to try to document what the function really does, as opposed to what it was originally supposed to do.

Yea, kind of, and I am that "someone" :-) (See https://github.com/aws/aws-sdk-java/issues/341)

On that particular line of code, yes, you are correct, it's not necessary. The reason why it exists is because It's auto-generated by our internal code-gen system, and the code template for this "with-er" method is supposed to be able to handle both cases, no matter the attribute getter method returns auto-constructed empty list or not (in ETS client it does, whereas in some newer service clients it doesn't). Theoretically yes, we can remove this line in clients where list auto-construction is enabled, but I don't really see much value in doing so.

Our team is actively working on open-sourcing our internal code-gen system. I hope by doing so we can give our users more visibility into how the SDK is developed, and perhaps make it easier for us to incorporate feedback from the community.

Before that happens, do you think it would help if we document the expected behavior when zero item is passed to the vararg method? Thoughts?

**Comment by rankinc** [comment]
I would _strongly_ recommend that you document this difference in behaviour because it is both non-obvious and counter-intuitive. Consider that _any_ `java.util.List` can be converted to an array and back to a list again like this:

```
List<Object> list = ...
Object[] array = list.toArray(new Object[list.size()]);

List<Object> copy = java.util.Arrays.asList(array);
```

Since Java itself considers arrays and Lists to be interchangeable to this degree, my expectation of `withArtwork(Artwork...)` is therefore that it behaves as if implemented by

```
public JobAlbumArt withArtwork(Artwork... artwork) {
    return withArtwork(java.util.Arrays.asList(artwork));
}
```

And similarly for _any_ two methods whose signatures only differ on whether a given input is either a List or an array, of course.
