### ISSUE TITLE
DynamoDBMapper "load" and "batchLoad" methods should support ProjectionExpressions

### ISSUE THREAD

**Issue by mkobit** [aws/aws-sdk-java#527]
Both the overloaded `query` and `scan` methods have support for this in their respective `DynamoDBQueryExpression` and `DynamoDBScanExpression`. Since both APIs support this, the mapper should have support to use projections with both of them.

**Comment by debora-ito** [comment]
Hi @mkobit, the SDK team has reviewed the feature request list for V1, and since they're concentrating efforts on V2 new features they decided to not implement this one in V1. It's still being considered for the DynamoDB Mapper refactor in V2, see the referenced issue above. I'll go ahead and close this one.

Please feel free to comment on the V2 issue with your use case, and reach out if you have further questions.
