### ISSUE TITLE
Excess byte[] copy in JSONWriter

### ISSUE THREAD

**Issue by ogmios-voice** [aws/aws-sdk-java#536]
While DynamoDB supports both `byte[]` and `ByteBuffer` values, actually it will wrap every `byte[]` object into a `(Heap)ByteBuffer`, just to convert it back to an array in `JSONWriter.value(ByteBuffer b)`, but not without duplicating it:

``` java
    public JSONWriter value(ByteBuffer b) throws JSONException {
        b.mark();
        byte[] bytes = new byte[b.remaining()];
        b.get(bytes, 0, bytes.length);
        b.reset();
        return this.value(BinaryUtils.toBase64(bytes));
    }
```

As a quick fix it should use `ByteBuffer.hasArray()` and `array()`, but a final solution would work directly with the arrays without wrapping things back and forth. (Based on `Item` _"The internal representation of binary should always be byte[]"_, so why is it converted then to `ByteBuffer`?)

Unfortunately I don't think this would be the only place in the code where excess array copy is done: just check call hierarchy for `BinaryUtils.copyBytesFrom()` and `copyAllBytesFrom()`.

**Comment by spfink** [comment]
While Item does allow both byte[] and ByteBuffer as input, it immediately converts a byte[] input into a ByteBuffer because the AttributeValue class only works with ByteBuffers. The AttributeValue class is managed by the DynamoDB team. We will further discuss with them why they wrap byte[] immediately in a ByteBuffer but that is unlikely to change as it would be backwards incompatible. 

As far as the unnecessary copying, the reason that this being done currently is that array() on ByteBuffer does not respect the current position within the ByteBuffer. The code block that you posted is no longer being used in the latest version of the SDK. We now do a safe copy within BinaryUtils: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/BinaryUtils.java#L143

This copy is necessary so that it respects the current position of the buffer. In the case of DynamoDB, this may be unnecessary as the whole object should be needed. Will look into doing additional testing here to see if we can simply use array() when working with DynamoDB objects.

**Comment by debora-ito** [comment]
Hi @ogmios-voice,

the SDK team has reviewed the feature request list for V1 and decided not tackle this one, since they're concentrating efforts on V2 new features. I'll go ahead and close this.

Please feel free to reach out if you have further questions or comments.
