### ISSUE TITLE
DynamoDBMarshalling: add support for storing objects as binary data

### ISSUE THREAD

**Issue by lesliel** [aws/aws-sdk-java#537]
Right now custom data types must be transformed to `String` using an implementation of `DynamoDBMarshaller` in order to store them in DynamoDB. (see: [Mapping Arbitrary Data](http://docs.amazonaws.cn/en_us/amazondynamodb/latest/developerguide/JavaArbitraryDataMappingHLAPI.html))
However a similar marshaller interface should be provided for storing these data types as **binary** data. This interface should use `byte[]` ~~not `ByteBuffer`~~; e.g.:
```java
public interface DynamoDBBinaryMarshaller<T extends Object> {
    byte[] marshall(T getterReturnResult);
    T unmarshall(Class<T> clazz, byte[] obj);
}
```

**Comment by breedloj** [comment]
Can you give some examples of how you'd like to use this?  Also why you would want to marshall to  byte[] vs. a ByteBuffer.  Another workaround could be to Base64 encode the bytes to a String to use the current marshaller interface.

**Comment by lesliel** [comment]
What kind of examples are you asking for? I have stated my reasons why would I like to have it: _store custom data types as **binary** data_ instead of String.

I prefer `byte[]` over `ByteBuffer` as based on `Item` _"The internal representation of binary should always be byte[]"_ (but you should know this better as an Amazon employee), and I prefer performance over excess wrapping and conversion of the different datatypes.

As I have mentioned I would like to store my custom data types as **binary** data, ~~not as String~~. (I have tried returning the Base 64 encoded String value, and the high level API will force storing it as `String`.)
(On the other hand this will be my next request: feed binary fields with Base 64 encoded Strings encoded by the application, not by your `JSONWriter` -- e.g. by specifying this in a new field of @DynamoDBAttribute.)

**Comment by breedloj** [comment]
Fair enough, thanks for the request.  This seems like a feature that would be useful for a number of users.  As such I've added it as an item to our backlog and will update this issue once there's activity to report.

**Comment by Andy0708** [comment]
Why not allow people to specify a dynamic type, something like this:

```
public interface DynamoDBMarshaller<S, T> {
    T marshall(S var1);
    T unmarshall(Class<T> var1, S var2);
}
```

I ran into the same problem because I wanted my Java entity class to contain a ```ProductType``` enum instead of an integer, so I did like the below.

```
@DynamoDBAttribute(attributeName = "ProductID")
@DynamoDBMarshalling(marshallerClass = ProductTypeConverter.class)
private ProductType productType;
```

At the time of implementing the marshaller class, I could see a type mismatch coming. It would be silly to make another marshaller interface specific to byte marshalling. Just let people choose both types, because why make assumptions on how people want to use the interface? I just ran into this assumption that the column should always be converted to a string, and I am left with the choice of finding a workaround, which could be to just change the column type, but I also don't want to change the column type because of my application code!

Please update the interface so that both types can be specified if possible - if it's not a big problem in regards to backwards compatibility.

Thanks!

**Comment by shorea** [comment]
The new @DynamoDBTypeConverted annotation allows marshalling of binary types.
