### ISSUE TITLE
DynamoDB: Support getter and setter less fields.

### ISSUE THREAD

**Issue by gkristjansson** [aws/aws-sdk-java#547]
It would be super nice not having to define getters and setters for POJO when using mapping. The annotations are already allow to be placed on fields, but requires getters and to present. Often the encapsulation argument does not always clearly apply, since in lots of cases the type that you are using for storage is just used for that and is not accessible else where in the code base.

**Comment by zhangzhx** [comment]
Could you give me a concrete example that why you want a getter and setter less fields? The POJO is not only used to store data retrieved from DynamoDB, it also could be used to modify data and save to DynamoDB. The getter and setter are essential to make that happen.

**Comment by Dimes** [comment]
Getters and setters are compile time contracts about what is allowed on an object. The DynamoDBMapper is using reflection to set the internal state of a class. The mapper has no need to respect the compile-time contract, and requiring the use of setters makes perfectly valid application logic impossible. For instance, I should be able to model a persisted class with `final` instance variables, but `final` fields are impossible to use with setters. In some sense, DynamoDB is used for persisting application state. Why should any persistence library force the application to conform to a certain type of API when Java's reflection API already contains the required functionality for persisting state?

Can you give an example when getters and setters need to be used?

**Comment by kdabir** [comment]
@Dimes I totally agree with you on this. I usually try to mark as many fields `final` as possible and get required data in constructor(s) or through some kind of builders, but try to keep the model as immutable as possible. 

How I am dealing with this is creating dumb model classes for dynamo mapper (under a different pacakge), and then mapping them to/from my richer Domain model.

**Comment by shorea** [comment]
You can also define a read only interface and return that to your domain logic. The setters would only be visible and used by your mapping layer.

**Comment by kepkap** [comment]
Hi guys,
+1 vote for this issue. 

having explicit public setters on persisted and presumably rich-modelled entity is something you want to avoid. This constraint opens the door to anemic domain model antipattern.  

I am totally fine with java bean nature for simple entities though. 

Still evaluating dynamodb for our project (migrating from mongodb), so I am up for this  issue in advance. 

thnx

**Comment by rage-shadowman** [comment]
IMO, immutability is a necessity in any code that runs more than 1 thread. This way we can create immutable model objects that we can pass around without worrying about any bad actors modifying the data from underneath us, since they will have to build their own snapshot and leave ours alone.

If I send you something to store in the database, and some other thread modifies the object while you are in the process of storing the data, you can't be sure if you used the correct data or not (you could've gotten half of my old data mixed with half of the new data, which breaks some expected invariant). This can be incredibly difficult to debug. Sure you could try to lock on something that all setters also lock on, but you still have to worry about bad actors (or those who forgot to set the lock before modifying the data).

A much better solution is to use immutable objects. Getters are fine if you don't want to use reflection to read state when storing data to the database. Mutable builder classes are fine for loading data from the database. It's much easier to debug and find bad actors when you reduce your multi-threading complexity by using immutable objects everywhere.

To use Jackson as an example... Jackson will let you use constructors whose arguments were annotated with `@JsonProperty("myPropertyName")` or even builders when you annotated the class with `@JsonDeserialize(builder = MyClass.Builder.class)`.

**Comment by debora-ito** [comment]
Hey @gkristjansson @dimes @kdabir @kepkap @rage-shadowman, 

the SDK team has reviewed the feature request list for V1, and since they're concentrating efforts on V2 new features they decided to not implement this one in V1. It's still being considered for the DynamoDB Mapper refactor in V2, see the referenced issue above. I'll go ahead and close this one.

Please feel free to comment on the V2 issue with your use case, and reach out if you have further questions.
