### ISSUE TITLE
Issue in DynamoDBReflector::getSetter

### ISSUE THREAD

**Issue by txu0393** [aws/aws-sdk-java#582]
In class com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBReflector (line 255):
Cannot find setter method for class if it's inherited (and not overridden) from its parent class. This method should look for the setter method in the super class if the method is not overridden.

**Comment by txu0393** [comment]
After exploring around, i figured out how to reproduce this issue and how to hotfix the problem.
Basically if we had:
```
class AbstractClass<T> {
    protected T genericField;

    public void setGenericField(T genericField) {
        this.genericField = genericField;
    }
}
```
and
```
class NotAbstractClassA extends AbstractClass<SomeDynamoDBDocumentClass> {
}
```
An exception will be thrown because a setter method is not found. I was able to get around this by overriding the setter from the parent class, even though this shouldn't be necessary.
```
class NotAbstractClassA extends AbstractClass<SomeDynamoDBDocumentClass> {
    @Override
    public void setGenericField(SomeDynamoDBDocumentClass genericField) {
        this.genericField = genericField;
    }
}
```

**Comment by zhangzhx** [comment]
Currently, dynamoDB Mapper doesn't support inheritance. It only scans annotations within the class itself instead of scanning its supper classes as well. The workaround would be the way you used, ie. override the relevant setters and getters. Since Java reflection has a big performance impact, we may not consider supporting this.
