### ISSUE TITLE
Is Transfer.uploadDirectory more efficient than Transfer.upload?

### ISSUE THREAD

**Issue by liujiayi771** [aws/aws-sdk-java#663]
if I write a function called uploadFile, the code is:
```
TransferManager tx = new TransferManager(credentialProviderChain.getCredentials());
upload = tx.upload(bucketName, s3FileName, localFile);
upload.waitForCompletion();
tx.shutdownNow();
```
I create a new TransferManager object every time I upload a single file, and shutdown it.
I use a loop to upload every single file in a directory, is it less efficient than upload the directory using Transfer.uploadDirectory directly?

By the way, if I want to upload many single file to S3, do I need to create a new TransferManager object and shutdown it every time I upload a file? Does this way take more time using to connect to the S3 server?

I'm poor in English, sorry about that.

**Comment by varunnvs92** [comment]
Hi liujiayi771,

**I use a loop to upload every single file in a directory, is it less efficient than upload the directory using Transfer.uploadDirectory directly?**
There is no difference in performance when you upload every single file in a directory or just using TranferManager.uploadDirectory to upload the entire directory. UploadDirectory() method is a convenience for you as this does the work of looping through all the files.

**By the way, if I want to upload many single file to S3, do I need to create a new TransferManager object and shutdown it every time I upload a file? Does this way take more time using to connect to the S3 server?**
We recommend creating a single instance of TransferManager and using it for all of your operations. Because every time you create a transferManager, you are establishing a connection with S3 and it takes time. This affects performance of your application.

[](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManager.html)
The above link refers to docs page which explains this "TransferManager is responsible for managing resources such as connections and threads; share a single instance of TransferManager whenever possible. TransferManager, like all the client classes in the AWS SDK for Java, is thread safe. Call TransferManager.shutdownNow() to release the resources once the transfer is complete."

Please feel free to reach out to us if you have more questions.

Thank you.

**Comment by varunnvs92** [comment]
Closing the issue. Feel free to reopen if you have more comments.
