### ISSUE TITLE
CountingInputStream doesn't take into account 'skip'

### ISSUE THREAD

**Issue by diwakergupta** [aws/aws-sdk-java#68]
Compare the AWS implementation [1] with Guava's [2]

[1] https://github.com/aws/aws-sdk-java/blob/master/src/main/java/com/amazonaws/util/CountingInputStream.java
[2] https://code.google.com/p/guava-libraries/source/browse/guava/src/com/google/common/io/CountingInputStream.java

I actually ran into this when trying to use the count as a condition and hit subtle/spurious error that took many hours to debug :-(

The Guava implementation is also more robust in terms of handing mark/reset.

**Comment by hanshuo-aws** [comment]
Sorry for the silence here.
<code>CountingInputStream</code> is only intended for internal usage by the SDK, and in reality it's only used to wrap a service response stream in order to calculate the <code>BytesProcessed</code> metrics. We don't suggest use this class as a general utility for your own purpose.
Feel free to reopen if you find any malfunctioning within the SDK caused by this issue.
