### ISSUE TITLE
V4 signature behaviour change  1.9.19 -> 1.11.4

### ISSUE THREAD

**Issue by adrianbk** [aws/aws-sdk-java#727]
We are attempting to upgrade from `1.9.19` to `1.11.4` but it appears that something has changed with respect to the "complicated dance" described [here](https://github.com/aws/aws-sdk-java/issues/360). 

When attempting to put an object with `1.11.4`, using a virtual-hosted–style url (without specifying the region), it fails with the following exception: 
```
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'ap-southeast-2' (Service: Amazon S3; Status Code: 400; Error Code: AuthorizationHeaderMalformed; Request ID: xxxxx9), S3 Extended Request ID: xxxxxxxxxxxxxxxxxxxxxxxxxx
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1305)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:852)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:630)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:367)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3787)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1399)

```

I'm wondering what has changed to cause this to stop working and if there is any way to enable or configure the client to behave as it did in `1.9.19`?

**Comment by varunnvs92** [comment]
@adrianbk 
I was not able to reproduce the issue. 
Can you provide us code which triggers this exception. Please give us details on how you are creating the client. 
Is the client configured with a region or endpoint?

**Comment by adrianbk** [comment]
@varunnvs92 Here's how we create the client: https://github.com/gradle/gradle/blob/7b14ba6f79d740bcaa1c05a914999047a5d4ae1f/subprojects/resources-s3/src/main/java/org/gradle/internal/resource/transport/aws/s3/S3Client.java#L126-L126 we are using `org.gradle.internal.resource.transport.aws.s3.S3RegionalResource`

**Comment by amedeiros** [comment]
I am also experiencing this same issue upgrading from 1.10.62 to 1.11.6. This is happening on `getBucketLocation` for me.

```
com.amazonaws.services.s3.model.AmazonS3Exception: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-central-1' (Service: Amazon S3; Status Code: 400; Error Code: AuthorizationHeaderMalformed; Request ID: REDACTED)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1305)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:852)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:630)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:367)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3787)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3729)
        at com.amazonaws.services.s3.AmazonS3Client.getBucketLocation(AmazonS3Client.java:716)
        at com.amazonaws.services.s3.AmazonS3Client.getBucketLocation(AmazonS3Client.java:722)
```

We are setting the region on our AWS clients `.setRegion(Region)`

**Comment by varunnvs92** [comment]
@adrianbk 
I see the issue now. In 1.9.19, we were internally retrying the requests if client is either not configured with a region or if client is configured with US standard (us-east-1) region.

In 1.11.x, the behavior is same if client is not configured with a region. But if you explicitly set the region and the bucket is in different region, we don't retry and throw the error. The reason is we want the customer know that they have provided wrong region and so the request failed. This is a breaking change and that is the reason we introduced it in a new major version.

In your code, I see that you configure the client [here](https://github.com/gradle/gradle/blob/7b14ba6f79d740bcaa1c05a914999047a5d4ae1f/subprojects/resources-s3/src/main/java/org/gradle/internal/resource/transport/aws/s3/S3Client.java#L170-L175). In [S3RegionalResource class](https://github.com/gradle/gradle/blob/7b14ba6f79d740bcaa1c05a914999047a5d4ae1f/subprojects/resources-s3/src/main/java/org/gradle/internal/resource/transport/aws/s3/S3RegionalResource.java#L70-L74), you set the region to **us-east-1** if you cannot derive the region from URI. Try removing the logic where you default to us-east-1 when you don't know the region. This should fix the issue.

Thanks. Let me know if you have more questions.

**Comment by adrianbk** [comment]
Thanks @varunnvs92, that was indeed it and we have fixed via https://github.com/gradle/gradle/commit/3c1c3eba02ef404f9643decb560d3d2c1cbf877e.

**Comment by amedeiros** [comment]
@varunnvs92 This still seems like an issue though with getBucketLocation. I was before able to make a request for a buckets location regardless of the region of the client which for us is the purpose of making that call so that we can filter out buckets not in the current clients region.

**Comment by amedeiros** [comment]
@varunnvs92 This so far only seems to be an issue with us-east-1 (US). I cannot request a buckets location with a client setup for us-east-1 if that bucket is in any other region. However, I can request a bucket that is in us-east-1 from us-west-1 setup client or any other region for that matter. I am able to request a buckets location where the buckets location is in us-west-2 from a client configured with ap-southeast-1. 

I am not sure why just in us-east-1 you cannot request a location for a bucket in another region, but this is not the behavior for any other region.

**Comment by amedeiros** [comment]
Not setting the region on us-east-1 does seem to work. Although I'm not really sure this is desired behavior or not.

**Comment by fernomac** [comment]
Despite recent efforts to make it look more "normal," US Standard/us-east-1 still has a bit more history than newer S3 instances. For other regions, the SDK sends requests to `${bucket}.s3-${region}.amazonaws.com`, which always resolves to the S3 instance in the given region. The SDK signs the request for the appropriate region, and everything works out nicely (assuming you got the region right, or are calling getBucketRegion in which case it doesn't matter).

For US Standard/us-east-1, the SDK uses `${bucket}.s3.amazonaws.com`, which resolves to the S3 instance *in the region where the bucket is actually hosted*. If you're using SigV4 and the request is signed for us-east-1, however, if it ends up anywhere else it will be rejected. There is no `s3-us-east-1.amazonaws.com` currently; `s3-external-1.amazonaws.com` is the closest thing. It sounds like the underlying instance is now pretty close to parity with other instances if you hit it via s3-external-1?

If the SDK is now defaulting to SigV4 when configured for US Standard/us-east-1, perhaps it should also be defaulting to use s3-external-1 when so configured? This would break people sending unauthenticated requests on a client configured for US Standard/us-east-1 and expecting them to end up in the right place, but that's already happened for authenticated requests and it'd be nice if the behavior was consistent.

And/or, it now seems pretty clear that S3 is moving US Standard to act like/be branded like a normal instance running in us-east-1, and won't be standing up a separate us-east-1 instance. Perhaps they should point `s3-us-east-1.amazonaws.com` at it so clients can stop special-casing it all together?

**Comment by amedeiros** [comment]
@fernomac Thank you for the explanation. It would be nice if S3 was more consistent. Currently I am instead not setting the region on the client if the region we are going to make requests against is us-east-1 and this seems to resolve the problem, but is a pivot and special use case.

**Comment by varunnvs92** [comment]
@amedeiros 
I agree that the behavior is not consistent and its weird that the request fails only when the client is configured with us_east_1 and bucket is in different region. I will be raising a ticket to Amazon S3 to check if this is the desired behavior and will get back to you. Thank you for bringing up this case.

@fernomac 
Thank you for your explanation. I agree with you that S3 should use s3-us-east-1.amazonaws.com instead of global s3.amazonaws.com. I will ask Amazon S3 team to check if they have it in their timeline. And what do you mean when you mentioned this "**If the SDK is now defaulting to SigV4 when configured for US Standard/us-east-1, perhaps it should also be defaulting to use s3-external-1 when so configured?"**
Can you elaborate more on this?

**Comment by fernomac** [comment]
@varunnvs92 currently if you explicitly configure a client for us-east-1, you're using the s3.amazonaws.com endpoint (so the request may end up somewhere that's not us-east-1). That worked out okay (if strangely different than other regions) pre-SigV4, but if you're now SigV4 signing requests for us-east-1 they'll be rejected if they end up somewhere that's not us-east-1.

It seems like it would be more consistent to instead use the s3-external-1.amazonaws.com endpoint when the user explicitly asks for us-east-1 - that way the request will always land in us-east-1, as it does when you configure the client for any other region, and the signature will always be correct (although it may fail because the bucket's actually somewhere else).

**Comment by varunnvs92** [comment]
@fernomac Thanks for the explanation. Totally makes sense.
