### ISSUE TITLE
1.11 is not backwards compatible with 1.10 because of SetQueueAttributesResult

### ISSUE THREAD

**Issue by rdifalco** [aws/aws-sdk-java#763]
1.11 introduced a new class calls `SetQueueAttributesResult` and changed the signature of `AmazonSQS#setQueueAttributes` to an instance of this class. That means that no code that was compiled with 1.10 can be used with code that is compiled with 1.11. So any libraries that used SQS 1.10 cannot be used by a 1.11 project. 

The really ugly thing is that this is essentially a null class. I mean this has to be a bug. Why break code just to return an instance of a class that can never provide any data?  This method should be changed back to return void. This was a pretty sloppy change. Otherwise you should use semver and change from 1.10.X to 2.X for this change.

**Comment by shorea** [comment]
Robert, our versioning scheme treats 1.10 and 1.11 as separate major versions so they aren't intended to be compatible with one another. We made this change to prevent binary incompatible changes in the future. If a service starts defining an output for an API action (which is not a breaking change for them) then it would break binary compatibility in the Java SDK. To prevent this in the future we decided to take the hit once and generate empty POJOs for all operations that do not define an output.

**Comment by rdifalco** [comment]
Is that somewhere in the documentation? We only found the issue after messing around with dependencies for two days (we use other libraries that also use the AWS SDK). Googling around brought up no such information on 1.11 not being backwards compatible with 1.10. Would appreciate a link.

**Comment by rdifalco** [comment]
Since you broke all 1.10 based libraries, are you going to add new regions into 1.10.X?

**Comment by shorea** [comment]
We mentioned the change in https://aws.amazon.com/releasenotes/Java/9979983567247718 but it's a bit abstract and doesn't call out SQS specifically.

You can actually use new regions without updating. 
client.setRegion(RegionUtils.getRegion("ap-south-1"));

**Comment by shorea** [comment]
KCL now supports 1.11.

**Comment by cozos** [comment]
Hello,

> our versioning scheme treats 1.10 and 1.11 as separate major versions so they aren't intended to be compatible with one another

If semver "minor versions" are major versions in the AWS SDK, then what are semver "patch versions" (i.e. 1.11.x). Can we expect that to be backwards compatible?

**Comment by millems** [comment]
Going forward, we will avoid backwards-incompatible code changes without a major version bump. This applies to 2.x and 1.x.

Here's our formal policy going forward:
1. SDK jars MUST be binary backwards-compatible with jars of the same major version (e.g. 1.12.x, if ever released, will be binary backwards-compatible with 1.11.x).
2. This guarantee only applies to classes that the SDK team considers "public" classes. This is admittedly a bit ambiguous in 1.x, but in 2.x, anything annotated with `@SdkPublicApi` is considered a "public" class.
3. This guarantee does not extend to our dependencies, which we may have to upgrade for security reasons. That said, if we do a 'risky' dependency upgrade we will do it with a minor version bump so that it is less likely surprise you. (e.g. We may upgrade from Jackson-2.6.x to Jackson-2.12.x, but only as part of an upgrade from 1.11.x to 1.12.x).
4. This guarantee does not currently extend to our "internal intermodule APIs" (i.e. anything annotated in 2.x with `@SdkProtectedApi`. We may have to 'break' these APIs for security reasons, but we will try our best not to, and we will only ever do it as part of a minor version bump. (e.g. We may break our internal `JacksonUtils` API which is used by a few other modules as part of an upgrade from 2.x.y to 2.{x+1}.0, because it will allow us to remove Jackson-databind as a dependency).

**Comment by cozos** [comment]
Thanks for the in depth response. Could you also tell me about existing semver "patch" versions. I'm specifically interested in 1.11.x. For example, would these be backwards compatible?

1.11.3xx -> 1.11.9xx
1.11.3xx -> 1.11.6xx
1.11.6xx -> 1.11.9xx

**Comment by millems** [comment]
I'm fairly sure that there will be no binary backwards incompatibilities between patch versions as of 1.11.0.

A few caveats that I can think of (sorry): 
* There may be some minor behavioral changes because of bug fixes if you were to, say, jump from 1.11.0 to the latest version since 1.11.x has been out for a very long time. We sometimes have to make tough calls on behavioral changes, so we only do it when we're fairly sure it won't affect anything other than a few people, and it fixes things for a large number of people.
* There are a few cases where service teams accidentally release broken APIs on 1.11.{x} and removed it in 1.11.{x+k} for some small version of k. We only allow service teams to do this if the APIs are broken (always throw an exception), so you're unlikely to get broken by this.
