### ISSUE TITLE
Bad UUIDUnmarshaller implementation

### ISSUE THREAD

**Issue by bademux** [aws/aws-sdk-java#773]
It is not the best idea to marshal UUID to string, because UUID can be represented by only 16 bytes (two longs)
Amazon SDK forces us do to it in non optimal way - currently there are no way to do it right.
Please give user ability to implement own marshaller or fix existing one.

Weak solution was implemented here #353

**Comment by varunnvs92** [comment]
@bademux 
Can you provide us some more information on how you are using the SDK. What is the use case that is giving you the issue?

You can also provide you own custom marshallers for Amazon DynamoDB. 
https://java.awsblog.com/post/Tx1K7U34AOZBLJ2/Using-Custom-Marshallers-to-Store-Complex-Objects-in-Amazon-DynamoDB

We do accept pull requests. Thank you.

**Comment by bademux** [comment]
@varunnvs92 thank you for suggestion, but it isn't the case. There are no way not write custom marshaller for byte[] (see #537 for more info)
The only way I know is writing ugly code:

```java
    @DynamoDBHashKey
    private ByteBuffer id;
    @DynamoDBIgnore
    private UUID uuid;

   @DynamoDBIgnore
    public UUID getUuid() {
        if (uuid == null && id != null) {
            uuid = toUuid(id);
        }
        return uuid;
    }
    @DynamoDBIgnore
    public void setUuid(UUID uuid) {
        this.uuid = uuid;
        this.id= toByteBuffer(uuid);
    }
    /**
     * @deprecated only for dynamodb, use getUuid
     */
    @Deprecated
    public ByteBuffer getId() {   return id;   }
    /**
     * @deprecated only for dynamodb, use setUuid
     */
    @Deprecated
    public void setId(ByteBuffer id) {
        this.uuid = null;
        this.id= id;
    }
```

Another way is to go deep into the library and write own com.amazonaws.services.dynamodbv2.datamodeling.ConversionSchema 

@david-at-aws how about new ConversionSchema V3 with new UUIDmarshaler ?

**Comment by fernomac** [comment]
(@david-at-aws is no longer -at-aws, so take this opinion with an appropriately-sized grain of salt)

A v3 schema seems like overkill for this; IMO that should be reserved for changes in the underlying DynamoDB data model (V2 originated when DynamoDB added native support for Booleans, Lists, and Maps). #742 added the ability to easily build a custom ConversionSchema based on one of the standard ones by overriding the marshaler/unmarshaler pair for a particular type; that might fit your requirements in the short term?

If you're interested in something more built-in, I'd be happy to :+1: (in a purely moral-support sense, since I'm no longer a committer on this project) a pull request adding an equivalent of [@DynamoDBNativeBoolean](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBNativeBoolean.java) that instructs the mapper to store the value as a Binary attribute.

**Comment by bademux** [comment]
@fernomac thanks! I will play with @DynamoDBNativeBoolean.
It will be great to hear what solution for UUID can be accepted by Amazon.

**Comment by bademux** [comment]
if someone look for solution: https://gist.github.com/bademux/8af228eed3a6370e49148f7040bb5ecb

**Comment by bademux** [comment]
Unfortunately I'm not able to use ConversionSchema builders due to mess with dependencies https://github.com/awslabs/amazon-sqs-java-messaging-lib/issues/22
Can anyone fix it?
Thanks

**Comment by shorea** [comment]
Working on getting the messaging lib updated.

**Comment by shorea** [comment]
Sorry for the delay, an updated version of the messaging lib was just released.
