### ISSUE TITLE
CapacityManager availableCapacity condition

### ISSUE THREAD

**Issue by gsharma** [aws/aws-sdk-java#782]
In CapacityManager acquire():
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/CapacityManager.java#L64

Per the docs, maybe this condition should return false instead of short circuiting the acquisition conditions to follow:
        if (availableCapacity < 0) {
            return true;
        }

**Comment by breedloj** [comment]
Hey Gaurav, thanks for reaching out to us.  This is actually by design as the CapacityManager is designed to effectively operate in a no-op mode if it's initialized with a negative capacity, which happens if the retry throttling feature is not enabled: https://github.com/aws/aws-sdk-java/blob/34f4dddc16f1caa1ab773d3f493d621d7c18484b/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L288-L290

I'll add a comment for this to avoid any confusion.  Thanks again.
