### ISSUE TITLE
Amazon Glacier SDK

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#783]
Hi
Can you please be consistent at Amazon Glacier SDK at the returned classes from the list & describe methods?
i.e. com.amazonaws.services.glacier.AmazonGlacierClient.listVaults returns list of DescribeVaultOutput that holds the values
while com.amazonaws.services.glacier.AmazonGlacierClient.listVaults.describeVault returns DescribeVaultResult that holds the values. 
Can DescribeVaultResult return DescribeVaultOutput??
this will help me having cleaner and consistent code
Thanks

**Comment by shorea** [comment]
I see what you mean, I agree it's not super ideal. This code is generated from Glacier's service model so we are tied to how they choose to represent their service. Since changing this would be a breaking change for Glacier I don't see this happening soon. For now the best suggestion I have is to write a simple adapter to translate the flattened vault in DescribeVaultResult into the DescribeVaultOutput representation. A reflection based approach may be more future proof in case attributes are adding later on.
