### ISSUE TITLE
MultipleFileDownload does not provide a getSubTransfers() method

### ISSUE THREAD

**Issue by c-n-d** [aws/aws-sdk-java#785]
Hi Team,

The [MultipleFileUpload](https://github.com/aws/aws-sdk-java/blob/a51792ec9d34263c12de5231131b42bd7dc544d9/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/MultipleFileUpload.java#L35-L38) interface defines a method for accessing the underlying transfers:

``` java
public Collection<? extends Upload> getSubTransfers();
```

`getSubTransfers()` is implemented by [MultipleFileUploadImpl](https://github.com/aws/aws-sdk-java/blob/a51792ec9d34263c12de5231131b42bd7dc544d9/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/MultipleFileUploadImpl.java#L80-L86):

``` java
public Collection<? extends Upload> getSubTransfers() {
    return Collections.unmodifiableCollection(subTransfers);
}
```

[MultipleFileDownload](https://github.com/aws/aws-sdk-java/blob/a51792ec9d34263c12de5231131b42bd7dc544d9/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/MultipleFileDownload.java) does not seem to define an analogous method. Is it possible to otherwise access the SubTransfers of MultipleFileDownload and if not, would it be possible to add `getSubTransfers()` to MultipleFileDownload?

``` java
public Collection<? extends Download> getSubTransfers();
```

Is there a recommended way of accessing the SubTransfers of MultipleFileDownload (specifically key and version of each downloaded object)?

**Comment by kiiadi** [comment]
Thanks for the feature request, if others up-vote this one we can raise the priority.

**Comment by debora-ito** [comment]
Hi @c-n-d, the SDK team has reviewed the feature request list for V1, and since they're concentrating efforts on V2 new features they decided to not implement this one in V1. It's still being considered for the TransferManager refactor in V2, see the referenced issue above. I'll go ahead and close this.

Please feel free to comment on the V2 issue with your use case, and reach out if you have further questions.
