### ISSUE TITLE
S3 REST call through Datapower

### ISSUE THREAD

**Issue by naren3k** [aws/aws-sdk-java#798]
We are integrating an in-house ECM to use S3 as repository .
Websphere Application Server >Datapower> AWS S3.
When I make a call through data power for an document > 2KB, I get exception from AWS saying ''Network Connection error and idle connections will be timeout"

If I look at TcP traffic, I can see some pockets are getting lost and AWS timing out in process.

We cehcked firewall rules and they are okay, datapower configuraiton also seems okay.

Anyclue where should I be looking 
![aws_tcp_trace](https://cloud.githubusercontent.com/assets/12582815/17275350/9fad00e8-573f-11e6-8d75-abb0678bd82b.JPG)
at ?

**Comment by fernomac** [comment]
That 2000+ byte `TCP segment of a reassembled PDU` packet look suspicious, given that 1500 is the usual [MTU](https://en.wikipedia.org/wiki/Maximum_transmission_unit) over the Internet. Your system's presumably configured to use a higher MTU? Path MTU discovery *should* kick in when you try to send a packet that's too large for the path it's trying to traverse, but (from the linked wikipedia page):

>Unfortunately, increasing numbers of networks drop ICMP traffic (for example, to prevent denial-of-service attacks), which prevents path MTU discovery from working. One often detects such blocking in the cases where a connection works for low-volume data but hangs as soon as a host sends a large block of data.

Which sounds a lot like what you're seeing here. If so (and if you can't change the firewall that's blocking ICMP Datagram Too Big to allow path MTU discovery to work automatically), manually dropping the MTU on your system's Internet-facing interface should help.

Given the smaller (1460 bytes of payload + 40 bytes of IP+TCP header = 1500 bytes) retransmits which also aren't making it through, I'm guessing your actual path MTU is smaller than 1500 bytes, maybe because you're bouncing through an IPSec tunnel at some point along the way? Maybe drop to 1400 to see if that fixes things, then work your way back up until you find the limit?

**Comment by naren3k** [comment]
Hi, Thanks for the catch. :+1: 
however, the other TCP packet with length 855 was also never acknowledged as well :/

**Comment by naren3k** [comment]
re-opening this..accidentally closed

**Comment by fernomac** [comment]
There's an ACK for the data in the 855-byte frame immediately before the first retransmit (Ack=1240).

**Comment by shorea** [comment]
Closing issue. Feel free to reopen if there's more to report.
