### ISSUE TITLE
Using S3 buckets for blob storage in AEM.

### ISSUE THREAD

**Issue by jayproulx** [aws/aws-sdk-java#827]
I realize this is a use case for AEM, but I thought I'd report this bug here.

https://github.com/aws/aws-sdk-java/blob/1d3471d831d07078739b06f5f1006c990323ab4a/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/Region.java#L283

By default Region.java returns us-east-1 as the region when there s3RegionId is null.  If I don't specify a region connecting to S3 fails, even if us-standard is supposed to be the default.

Caused by: java.lang.IllegalArgumentException: Cannot create enum from us-east-1 value!
	at com.amazonaws.services.s3.model.Region.fromValue(Region.java:257)
	at org.apache.jackrabbit.oak.blob.cloud.aws.s3.S3Backend.init(S3Backend.java:158)
	... 37 common frames omitted

http://svn.apache.org/viewvc/jackrabbit/oak/trunk/oak-blob-cloud/src/main/java/org/apache/jackrabbit/oak/blob/cloud/aws/s3/S3Backend.java?view=markup#l153

S3Backend asks com.amazonaws.regions.Regions for a region when none is provided, this in turn asks EC2MetadataUtils.getEC2InstanceRegion() for a region which PROBABLY correctly returns us-east-1, which is of course not a valid enum from https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/Region.java

And in turn, as above that's the default value from Region.java anyway.

This is a similar issue which was closed. https://github.com/aws/aws-sdk-java/issues/405

This looks like it's still an outstanding problem, either us-east-1 needs to resolve to us-standard as the default (so that for several use cases, either EC2MetadataUtils or you're looking for a real, accepted default).

**Comment by shorea** [comment]
This is an increasingly popular request (#758). It seems reasonable to me but some other members of the team expressed concerns with taking this change. I'll touch base with everyone tomorrow and figure out what's the best option for supporting these types of use cases.

**Comment by shorea** [comment]
Clsoing this issue in favor of #758.

I will say one thing about the enum. If you are vending a library that's deployed to customers applications, it's not forward compatible to rely on the enum. If a customer deploys that library onto an EC2 host in a new region (i.e. one that the particular version of the SDK doesn't know about) then the fromValue call will fail and the customer will have to update their SDK to the latest version to use the library in that region. When vending code we recommend using the string identifiers for regions instead of using the enum. If there are APIs that only accept the enum this is a mistake, please let us know and we will add an appropriate overload that takes a string.
