### ISSUE TITLE
How to distinct prestes from aws transcoding job if all providing same quality?

### ISSUE THREAD

**Issue by singhvikram704** [aws/aws-sdk-java#886]
I am transcoding a video from any format to **HLS formats** using AWS Elastic transcoding service. I am using five presets in single job for adaptive bit rate. If video is of high input quality then video transcodes in different outputs qualities like 224p,270p, 360p,540p,720p. But if **video is of low input quality** then video transcodes in different **output qualities** like 224p,270p, **360p,360p,360p.** For low input quality there is three similar output quality i.e. 360p,360p,360p which is unnecessary cost of transcoding. How to **avoid two presets for output quality 360p from aws elastic transcoding job?** Want to generate only output quality like 224p, 270p, 360p.

**Comment by kiiadi** [comment]
@singhvikram704 this might be more of a question for the AWS Elastic Transcoding service team rather than the Java SDK - but let me see if I can help before I engage them. I'm not overly familiar with the Transcoding API - can you provide an example code-snippet that demonstrates the problem you're seeing? I've had a bit of a look through the [documentation](http://docs.aws.amazon.com/elastictranscoder/latest/developerguide/working-with-presets.html) and the [API reference](http://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/Welcome.html) and it's not obvious to me how one associates a preset with a job through the SDK.

**Comment by kiiadi** [comment]
@singhvikram704 sorry I think I might be confused with what you're asking here. The above is just the sample code right? Found [here](https://s3.amazonaws.com/codesamples/ets/latest/javasamples.zip)?

Can you show me how you're calling ElasticTranscoding from Java in your code? From what I've read the presets cover more than just the output quality they also define aspect ratio, audio etc.
There are several presets that seem to use 360p:
Webm VP9 360p (1351620000001-100260)
Generic 360p 4:3 (1351620000001-000050)
Generic 360p 16:9 (1351620000001-000040)

Which probably explains why you're seeing it more than once.

How are you getting to the list of qualities you've listed above?

**Comment by kiiadi** [comment]
Closing aged issue, please feel free to reopen if you require further assistance.
