### ISSUE TITLE
Support redirect (302)

### ISSUE THREAD

**Issue by dadoonet** [aws/aws-sdk-java#903]
Hi guys,

I got [this demand recently on a project](https://github.com/elastic/elasticsearch-cloud-aws/issues/278) where I'm using AWS SDK and I wonder if this is something you can support internally in the Java SDK as a new `followRedirect` option or something?

Unless this is already supported and I missed it in docs?

Thanks!

**Comment by dagnir** [comment]
Hi @dadoonet, you're correct the SDK [does not follow redirects](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/apache/client/impl/ApacheHttpClientFactory.java#L55). Unfortunately, this would be a breaking change since it will change the behavior in of our clients.

**Comment by dadoonet** [comment]
@dagnir Thanks for confirming. Could this because an option (false by default) so it does not break anything unless you explicitly opt-in?

**Comment by dagnir** [comment]
I will bring it up with the rest of the team to see if it makes sense for us to support this configuration.

**Comment by dagnir** [comment]
Hi @dadoonet, after much consideration, we have decided that we will not be supporting this feature in the SDK. One reason for this decision is that we feel it would be too confusing for the majority of AWS customers. This is because aside from S3, which does send 3xx responses, it is not part of the service contract in AWS to send redirect responses, so it's not something that should need to be accounted for. Adding support for this feature would also complicate the code as there are certain parts of the S3 and core runtime codebases that depends on the current behavior and we would need to make sure that that functionality would still work even in the presence of automatic redirect following; such an undertaking could also have the potential to introduce subtle bugs that could also affect customers who are not opting into this feature.

**Comment by dadoonet** [comment]
Understood. Thanks for the feedback.
