### ISSUE TITLE
Query api always returns 0 when Select is set to COUNT only

### ISSUE THREAD

**Issue by Jimexist** [aws/aws-sdk-java#915]
When i try to query a table using an index,
```java
QuerySpec querySpec = new QuerySpec()
            .withHashKey(...)
            .withRangeKeyCondition(...)
            .withSelect(Select.COUNT);
ItemCollection<QueryOutcome> queryResult = ordersIndex.query(querySpec);
```

Using this, the top level `queryResult` will always return `ItemCollection#getAccumulatedScannedCount` of 0, while:

```java
for (Page<Item, QueryOutcome> page : queryResult.pages()) {
   page.getLowLevelResult().getQueryResult().getCount();
}
```
will report the correct count.

**Comment by Jimexist** [comment]
or i have to manually do a `queryResult.firstPage();` to fetch at least the first page in order for the query result to return correct count.

**Comment by dagnir** [comment]
Hi @Jimexist, I believe that is expected behavior. Per the documentation of [`ItemCollection#getAccumulatedScannedCount`](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/document/ItemCollection.html#getAccumulatedScannedCount--), the operation returns the scanned count so far and the the queries are not actually made to DynamoDB until you attempt to iterate over the results. Take for example [`QueryCollection`](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/document/internal/QueryCollection.java#L47). You can see that it does two things: it sends the actual query to DynamoDB, and also updates the stats, which is consistent with what you're seeing.

**Comment by dagnir** [comment]
Closing this issue. Please feel to reopen if you have further questions or concerns.
