### ISSUE TITLE
CloudWatch Events - missing Java model classs

### ISSUE THREAD

**Issue by the4yeast** [aws/aws-sdk-java#916]
It seems like there is no model class representing the CloudWatch Events schedule notification, described at the bottom of http://docs.aws.amazon.com/AmazonCloudWatch/latest/events/EventTypes.html.
A sample class is in https://forums.aws.amazon.com/thread.jspa?threadID=221851.

**Comment by varunnvs92** [comment]
I apologize that I am not entirely sure what the problem is. You mentioned that there is no model class for scheduled Events. I also see that there are no classes for other event types like Amazon EBS Events etc.

From my understanding, there won't be any model classes for specific event types. You can create the events by using [putEvents](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/cloudwatchevents/AmazonCloudWatchEventsClient.html#putEvents-com.amazonaws.services.cloudwatchevents.model.PutEventsRequest-) operation. An example of using putEvents: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/AddEventsPutEvents.html

Let me know if I misunderstood the question and give me some more information on what you are looking for.

**Comment by zhangzhx** [comment]
Are you saying there is no modeled ScheduleEvent for Lambda function? If so, thanks for the request. I will reach out to Lambda team and ask them to add this Event. You can also report this directly to them at their [forum](https://forums.aws.amazon.com/forum.jspa?forumID=186).
