### ISSUE TITLE
DBInstancePort is always set to 0 when retriving instances

### ISSUE THREAD

**Issue by sallaby** [aws/aws-sdk-java#924]
Using AmazonRDSClient when retrieving a list of DBInstances:

`client.describeDBInstances().getDBInstances()`

Unfortunately all of them have a dbInstancePort set to "0" regardless of the actual value, the other properties appear to be correct.

Accessing the same RDS Instances via the CLI the port is given correctly with no problem at all.

**Comment by kiiadi** [comment]
@sallaby definitely odd that it's coming back with 0 - having run a bit of test my end that's what the RDS service returns in the response. I also get 0 when calling via the CLI:

`aws rds describe-db-instances --query DBInstances[0].DbInstancePort`

So it looks like a service-side issue to me rather than the SDK. As a work around can you grab the port from the end-point instead? 

`rds.describeDBInstances().getDBInstances().get(0).getEndpoint().getPort()`

What type of DB are you creating? (I did my test with mySQL)

**Comment by sallaby** [comment]
@kiiadi Ah, good idea.  The endpoint method works perfectly.  

The DBs are Postgres.

**Comment by kiiadi** [comment]
@sallaby - even with Postgres I still get a 0 for the port when using the CLI

Hopefully the endpoint method gives you a way forward, I'll raise this to the service team - but I'm going to close this issue for now. I'll come back on this when I hear back from them.

**Comment by bgoyal** [comment]
Same issue here. Are there any planned fixes for this issue?

**Comment by muvaf** [comment]
I'm experiencing the same issue; it always returns 0 in Go SDK as well as AWS CLI output. Even in the [example response in the doc](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeDBInstances.html#API_DescribeDBInstances_ResponseElements), the port is 0. @kiiadi Is there somewhere that we can give a thumbs-up or something to increase the importance of the bug?
