### ISSUE TITLE
SpringActivityWorker.addActivitiesImplementation does not use the DataConverter set in setDataConverter method; uses default instead

### ISSUE THREAD

**Issue by jonkerlinger** [aws/aws-sdk-java#925]
When calling setActivitiesImplementation or addActivitiesImplementation on the SpringActivityWorker, the single-arg POJOActivityImplementationFactory.addActivitiesImplementation, which ultimately will only use the default DataConverter or the Activities annotation-specified DataConverter. Even though the POJO implementation of SpringActivityWorker allows users to specify the DataConverter, it is not used when adding ActivitiesImplementations.

To work around it, I've had to extend SpringActivityWorker with something like this:
```
    @Override
    public List<ActivityType> addActivitiesImplementation(Object activitiesImplementation) {
        try {
            Field field = SpringActivityWorker.class.getDeclaredField("factory");
            field.setAccessible(true);
            POJOActivityImplementationFactory factory = (POJOActivityImplementationFactory) field.get(this);

            return factory.addActivitiesImplementation(activitiesImplementation, factory.getDataConverter());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
```

The override works fine for now, but is hacky. It seems that since setDataConverter sets the factory DataConverter, then that value should also be passed into the addActivitiesImplementation call, or the POJO factory should use the dataConverter field if present, rather than just looking at the annotation.

**Comment by kiiadi** [comment]
@jonkerlinger the SWF library is now housed in a different github repo (https://github.com/aws/aws-swf-flow-library) - I've moved the issue to that repo (https://github.com/aws/aws-swf-flow-library/issues/13).

What you're proposing seems like a simple enough fix (ie calling `POJOActivityImplementationFactory.addActivitiesImplementation(Object, DataConverter)` instead of `POJOActivityImplementationFactory.addActivitiesImplementation(Object)`) - but I must admit I'm not massively familiar with SWF so I'm not sure what the ramifications might (ie: is this backwards compatible) - what if other customers are relying on this (admittedly odd) behaviour?

**Comment by jonkerlinger** [comment]
@kiiadi, thank you for following up in new repo
