### ISSUE TITLE
Request to set a bucket lifecycle rule on an s3 bucket fails with invalid xml on 1.11.62, 1.11.63

### ISSUE THREAD

**Issue by dneray** [aws/aws-sdk-java#929]
Getting the following error:

> The XML you provided was not well-formed or did not validate against our published schema 

The following code can reproduce the issue:
```
s3 = new AmazonS3Client();
		final List< BucketLifecycleConfiguration.Rule > bucketLifeCycleRules = new LinkedList<>();

		bucketLifeCycleRules.add( new BucketLifecycleConfiguration.Rule().withId( "expirationRule" )
			.withExpirationInDays( 1 )
			.withStatus(
							BucketLifecycleConfiguration.ENABLED ) );
		s3.setBucketLifecycleConfiguration(
											"<bucketName>", new BucketLifecycleConfiguration().withRules( bucketLifeCycleRules ) );

```

If I add an empty LifecycleFilter then the problem goes away. This was working in build 1.11.60, I have not tested build 1.11.61 but I have observed the issue in 1.11.62 and 1.11.63

**Comment by shorea** [comment]
This is due to an unfortunate bug in the marshaller that required us to make a breaking change to support the new lifecycle filters. Previously, the only filter options were prefix and it was a required param. Due to the bug, if prefix was not provided we would treat that as an empty prefix to match the whole bucket instead of failing the request. To support the new filters introduced we had to stop sending Prefix when not set since all filter types are mutually exclusive. Explicitly setting a prefix or better yet using the new life cycle filter will fix the issue.
