### ISSUE TITLE
DynamoDBMapper with ReturnItemCollectionMetrics

### ISSUE THREAD

**Issue by tsuikm** [aws/aws-sdk-java#953]
I noticed that in the doPutItem() or doUpdateItem(), the UpdateItemRequest() or PutItemRequest() ReturnItemCollectionMetric is not set. Is there a way to set this to SIZE and have a way for the DynamoDBMapper to return the metric result?

**Comment by dagnir** [comment]
Hi @tsuikm, there is no way to retrieve the metrics when using the mapper at the moment. I've marked this as Feature Request.

**Comment by debora-ito** [comment]
Hi @tsuikm, the SDK team has reviewed the feature request list for V1, and since they're concentrating efforts on V2 new features they decided to not implement this one in V1. It's still being considered for the DynamoDB Mapper refactor in V2, see the referenced issue above. I'll go ahead and close this one.

Please feel free to comment on the V2 issue with your use case, and reach out if you have further questions.
