### ISSUE TITLE
remove all unnecessary imports

### ISSUE THREAD

**Issue by muellerc** [aws/aws-sdk-java#961]
We should remove all unnecessary import statements from the source to clean it up a bit.

**Comment by kiiadi** [comment]
@muellerc thanks for the submission - however the majority of our model objects are actually generated from the service model; our templating engine deals with several different types of service and thus we often include imports that aren't strictly necessary.

I agree we can probably do a better job of reducing the number of unused imports because it does clutter up the generated code. I can have a bit of a look at some of our templates and see if we can make them a bit more intelligent.

On a separate note, in our next iteration of the SDK we're looking to add better separation of what is and is not auto generated.

**Comment by muellerc** [comment]
Hi Kyle,
I guess you are talking about the com.amazonaws:aws-java-sdk-code-generator module.
If I'm right, I could also have a look and provide a patch for the first step. Is this fine for you?

Thanks,
Christian

**Comment by kiiadi** [comment]
@muellerc thank you for helping us curate the code-base having a clean set of classes is definitely something that we want!

The code generator has been updated to remove unused imports in generated classes now see [`UnusedImportRemover.java`](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-code-generator/src/main/java/com/amazonaws/codegen/emitters/UnusedImportRemover.java). To prevent confusion around those classes that are generated vs not, we've also annotated all of our generated classes with [`javax.annotation.Generated`](https://docs.oracle.com/javase/7/docs/api/javax/annotation/Generated.html) for example https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sns/src/main/java/com/amazonaws/services/sns/AmazonSNS.java#L45

**Comment by muellerc** [comment]
Hi Kyle,
thanks a lot!  It's a really good improvement. I will have a closer look at the generator.
